### ISSUE TITLE
Exception Message: Value cannot be null.  Paramater name: Key

### ISSUE THREAD

**Issue by malscent** [JasperFx/marten#1007]
## Error
```
at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Baseline.ConcurrentCache`2.Fill(TKey key, Func`2 onMissing)
at Marten.Events.EventSelector.<ResolveAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Marten.Linq.SelectorExtensions.<ReadAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

## Resolution

Resolution was that the library being used that accessed marten was out of date compared to the data stored within the database.  This caused Marten to throw an exception due to a unknown event type.

## Corrective Action

Improve Exception handling in [EventSelector, Line 85](https://github.com/JasperFx/marten/blob/master/src/Marten/Events/EventSelector.cs#L85)

**Comment by jeremydmiller** [comment]
Fix is ready, just need to clear some other things out first
