### ISSUE TITLE
Child list can not be populated

### ISSUE THREAD

**Issue by siberianguy** [JasperFx/marten#1015]
I'm trying to query Trades object with the following schema:

```
    public class Trades : StorageItem
    {
        public string Exchange { get; set; }
        public string CurrencyPair { get; set; }
        public IEnumerable<Trade> TradeItems { get; set; }
        
        public Trades(string exchange, string currencyPair, IEnumerable<Trade> trades)
        {
            Exchange = exchange;
            CurrencyPair = currencyPair;
            TradeItems = trades;
        }
    }
    
    public class Trade
    {
        public string TradeId { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public OrderSide Side { get; set; }
        
        public Trade(string tradeId, decimal price, decimal quantity, OrderSide side)
        {
            TradeId = tradeId;
            Price = price;
            Quantity = quantity;
            Side = side;
        }
    }
```
As results I get an exception that it could not be populated:
```
{Newtonsoft.Json.JsonSerializationException: Cannot create and populate list type System.Linq.Enumerable+SelectEnumerableIterator`2[System.Object,Core.Model.Trade]. Path 'TradeItems.$values', line 1, position 252.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken(JTokenReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Marten.Services.JsonNetSerializer.FromJson(Type type, TextReader reader)
   at Marten.Services.IdentityMap`1.<>c__DisplayClass9_0`1.<Get>b__0(Object _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.Services.IdentityMap`1.Get[T](Object id, Type concreteType, TextReader json, Nullable`1 version)
   at Marten.Services.IdentityMap`1.Get[T](Object id, TextReader json, Nullable`1 version)
   at Marten.Schema.DocumentStorage`1.Resolve(Int32 startingIndex, DbDataReader reader, IIdentityMap map)
   at Marten.Linq.WholeDocumentSelector`1.Resolve(DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Linq.SelectorExtensions.Read[T](ISelector`1 selector, DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Linq.QueryHandlers.ListQueryHandler`1.Handle(DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Services.CommandRunnerExtensions.<>c__DisplayClass2_0`1.<Fetch>b__0(NpgsqlCommand c)
   at Marten.Services.ManagedConnection.Execute[T](NpgsqlCommand cmd, Func`2 func)
   at Marten.Services.CommandRunnerExtensions.Fetch[T](IManagedConnection runner, IQueryHandler`1 handler, IIdentityMap map, QueryStatistics stats, ITenant tenant)
   at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Core.Bot.BotCreator.CreateDocumentStore(AppSettings appSettings) in /Users/alexidsa/Code/CryptoDreamTeam/CryptoDreamTraderSharp/Core/Bot/Bot/BotCreator.cs:line 89
   at Core.Bot.BotCreator.Create(Func`4 botCreator) in /Users/alexidsa/Code/CryptoDreamTeam/CryptoDreamTraderSharp/Core/Bot/Bot/BotCreator.cs:line 21
   at ExchangeImplementation.Bot.Program.<Main>d__0.MoveNext() in /Users/alexidsa/Code/CryptoDreamTeam/CryptoDreamTraderSharp/Bots/ExchangeImplementation/Bot/Program.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ExchangeImplementation.Bot.Program.<Main>(String[] args)}
```
I'm confused cause the same class was serialised and deserialised in RavenDb without any problems. It's clear the problem is related to TradeItems collection but I can't figure out from exception what exactly went wrong...

**Comment by jeremydmiller** [comment]
@siberianguy I'd strongly recommend turning this:

```
public IEnumerable<Trade> TradeItems { get; set; }
```

into one of these two:

```
public IList<Trade> TradeItems { get; set; }
// or
public Trade[] TradeItems { get; set; }
```

You've set the property to a Linq expression that implements `IEnumerable<Trade>` somewhere, and that object can't be serialized. Plus you might easily have some double iteration problems from doing that anyway. 

I'm going to close this one just for the sake of bookkeeping because there's nothing to do here in Marten.

For just questions -- and a faster response (sorry) -- can you use Gitter instead? https://gitter.im/JasperFx/marten?utm_source=share-link&utm_medium=link&utm_campaign=share-link
