### ISSUE TITLE
Strongly-typed nested class in Select() throws exception

### ISSUE THREAD

**Issue by AKlaus** [JasperFx/marten#1026]
How to return a collection of a strongly-typed class with a nested class, like below?
```C#
sess.Query<Model>().Select(user => new UserViewDto
{
	Id = user.Id,
	Contact = new ContactReference { Id = user.ContactId, Name = contact.Name }
});
```
where
```C#
public class UserViewDto
{
	public Guid Id { get; set; }
	public ContactReference Contact { get; set; }
	public UserViewDto()
}
public class ContactReference 
{
	public Guid Id { get; set; }
	public string Name { get; set; }
	public ContactReference()
}
```

Currently, an attempt to return in `Select()` a strongly-typed nested class (like above) throws a "_Sequence contains no elements_" exception:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Linq
  StackTrace:
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Marten.Schema.Field..ctor(MemberInfo[] members)
   at Marten.Schema.JsonLocatorField..ctor(String dataLocator, EnumStorage enumStyle, Casing casing, MemberInfo[] members)
   at Marten.Schema.FieldCollection.<>c__DisplayClass8_0.<FieldFor>b__1(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.Linq.TargetObject.SetterBinding.ToJsonBuildObjectPair(IQueryableDocument mapping)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Marten.Linq.TargetObject.ToSelectField(IQueryableDocument mapping)
   at Marten.Linq.TargetObject.ToSelector[T](IQueryableDocument mapping, Boolean distinct)
   at Marten.Linq.SelectorParser.ChooseSelector[T](String dataLocator, ITenant tenant, IQueryableDocument mapping, QueryModel query, SelectManyQuery subQuery, ISerializer serializer, IIncludeJoin[] joins)
   at Marten.Linq.Model.LinqQuery`1.BuildSelector(IIncludeJoin[] joins, QueryStatistics stats, SelectManyQuery subQuery, IIncludeJoin[] includeJoins)
   at Marten.Linq.Model.LinqQuery`1..ctor(DocumentStore store, QueryModel model, IIncludeJoin[] joins, QueryStatistics stats)
   at Marten.Linq.MartenQueryable`1.ToLinqQuery()
   at Marten.Linq.MartenQueryable`1.toDiagnosticHandler(FetchType fetchType)
   at Marten.Linq.MartenQueryable`1.BuildCommand(FetchType fetchType)
   at My Class Here.<GetItem>d__5.MoveNext() 
```

**Comment by AKlaus** [comment]
It might be related to JasperFx/marten#396...

**Comment by AKlaus** [comment]
There are two things I'd like to achieve:
1. Having a nested structure;
1. Using strongly-typed objects everywhere.

The first one can be achieved by using [Javascript Transformations](http://jasperfx.github.io/marten/documentation/documents/advanced/javascript_transformations/). Perhaps, it even would works if I modify the code to:
```C#
sess.Query<Model>().Select(user => new 
{
	Id = user.Id,
	Contact = new { Id = user.ContactId, Name = contact.Name }
});
```
However, I can't achieve the second goal of using strong types.

@jeremydmiller, would you recommend to try using Dapper here?

**Comment by jeremydmiller** [comment]
I don't see Dapper doing any better here. EF Core maybe. 

The javascript transform will still let you use strong types, as long as what JSON it returns can be deserialized into your type.

**Comment by isengrim613** [comment]
I have met this as well.

this code did not work:
```
using (var session = _documentStore.OpenSession())
{
    return await session.Query<Entity>()
        .Where(entity => entity.TenantId == tenantId)
        .Select(entity => new Account(entity))
        .ToListAsync();
}
```

This is the generated exception:
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Marten.Schema.Field..ctor(EnumStorage enumStorage, MemberInfo[] members)
   at Marten.Schema.JsonLocatorField..ctor(String dataLocator, EnumStorage enumStyle, Casing casing, MemberInfo[] members)
   at Marten.Schema.FieldCollection.<>c__DisplayClass8_0.<FieldFor>b__1(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.Schema.FieldCollection.FieldFor(IEnumerable`1 members)
   at Marten.Linq.SingleFieldSelector`1..ctor(IQueryableDocument mapping, MemberInfo[] members, Boolean distinct)
   at Marten.Linq.SelectorParser.ToSelector[T](String dataLocator, ITenant tenant, IQueryableDocument mapping)
   at Marten.Linq.SelectorParser.ChooseSelector[T](String dataLocator, ITenant tenant, IQueryableDocument mapping, QueryModel query, SelectManyQuery subQuery, ISerializer serializer, IIncludeJoin[] joins)
   at Marten.Linq.Model.LinqQuery`1.BuildSelector(IIncludeJoin[] joins, QueryStatistics stats, SelectManyQuery subQuery, IIncludeJoin[] includeJoins)
   at Marten.Linq.Model.LinqQuery`1..ctor(DocumentStore store, QueryModel model, IIncludeJoin[] joins, QueryStatistics stats)
   at Marten.Linq.MartenQueryable`1.executeAsync[TResult](Func`2 source, CancellationToken token)
   at Marten.Linq.MartenQueryable`1.ToListAsync[TResult](CancellationToken token)
   at Marten.QueryableExtensions.ToListAsync[T](IQueryable`1 queryable, CancellationToken token)
   ...
   (redacted)
```


Workaround: don't use Marten's select. Use regular linq select:
```
using (var session = _documentStore.OpenSession())
{
    var result = await session.Query<Entity>()
        .Where(entity => entity.TenantId == tenantId)
        .ToListAsync();

   return result.Select(entity => new Account(entity))
         .ToList();
}
```

**Comment by jeremydmiller** [comment]
or `Select(e => new Account{Entity = entity})`. Constructor functions aren't supported in the Select() support.

**Comment by jeremydmiller** [comment]
I'm afraid this one's gonna get "fixed" by adding a better exception message telling you that you can't use constructors and you'll have to use object initializers instead.
