### ISSUE TITLE
Including Document with a subclass hierarchy causes an InvalidCastException

### ISSUE THREAD

**Issue by brokethebuild** [JasperFx/marten#1060]
Including documents with a subclass hierarchy results in a 
_"Can't cast database type jsonb to Guid"} | System.InvalidCastException_

I've see this error a couple of ways, but all related to either _Marten.Schema.Hierarchies.SubClassDocumentStorage.Resolve_
_Marten.Schema.HierarchicalDocumentStorage.Resolve_ 
...
`var version = reader.GetFieldValue<Guid>(3);`

Reproduce Steps:

1. Configure the schema with a document that has subclasses
`StoreOptions(
                _ =>
                {
	                _.Schema.For<User>().AddSubClass<SuperUser>().AddSubClass<AdminUser>();
	                _.Schema.For<Issue>();
                });`

2. Query and include the document
`
		    var user = new User { Id = System.Guid.NewGuid() };
		    var issue = new Issue { Id = System.Guid.NewGuid(), ReporterId = user.Id};
		    theSession.Store(user);
		    theSession.Store(issue);
		    theSession.SaveChanges();
			var users = new List<User>();
			var issues = theSession.Query<Issue>().Include(i => i.ReporterId, users).ToList();
`

Here's a partial stacktrace:
`System.InvalidCastException : Can't cast database type jsonb to Guid
   at Npgsql.NpgsqlDataReader.<ReadColumn>d__1021.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter1.GetResult()
   at Npgsql.NpgsqlDataReader.<GetFieldValue>d__981.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask1.get_Result()
   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
   at Marten.Schema.HierarchicalDocumentStorage1.Resolve(Int32 startingIndex, DbDataReader reader, IIdentityMap map)
   at Marten.Services.Includes.IncludeSelector2.Resolve(DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Linq.IncludeSelector1.Resolve(DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Linq.SelectorExtensions.Read[T](ISelector1 selector, DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Linq.QueryHandlers.ListQueryHandler1.Handle(DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Services.CommandRunnerExtensions.<>c__DisplayClass2_01.<Fetch>b__0(NpgsqlCommand c)
   at Marten.Services.ManagedConnection.Execute[T](NpgsqlCommand cmd, Func2 func)
   at Marten.Services.CommandRunnerExtensions.Fetch[T](IManagedConnection runner, IQueryHandler1 handler, IIdentityMap map, QueryStatistics stats, ITenant tenant)
   at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase1.GetEnumerator()
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   ...`

**Comment by jeremydmiller** [comment]
Fixed by #1065. Will be in 2.10.0 soon.
