### ISSUE TITLE
[Marten.CommandLine] System.ArgumentException: An item with the same key has already been added. 

### ISSUE THREAD

**Issue by bradyclifford** [JasperFx/marten#1077]
When using the `Marten.CommandLine` library, we are getting the following error when trying to execute the `dump` command:
```
System.ArgumentException: An item with the same key has already been added. Key: patch_doc
```

Note that we are currently using Marten 1.5 with the same compatible `Marten.CommandLine` library. Yes I know, we should be on 2.0 at least, but we have constraints where I work.

Will follow-up with a comment that includes stacktrace and will look into the Marten code myself to see if I can identify the culprit.  For the time being, wanted to get this out in the open.

**Comment by bradyclifford** [comment]
@matneyx

**Comment by bradyclifford** [comment]
```ERROR: System.ArgumentException: An item with the same key has already been added. Key: patch_doc
   at System.Collections.Generic.Dictionary`2.TryInsert(TK
ey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Marten.DocumentStore..cto
r(StoreOptions options)
   at Marten.CommandLine.MartenInput.CreateStore()
   at Marten.CommandLine.MartenCommand`1.Execute(T input)
   at Oakton.OaktonCo
mmand`1.Oakton.IOaktonCommand.Execute(Object input)
   at Oakton.CommandRun.Execute()
   at Oakton.CommandExecutor.<>c__DisplayClass15_0.<Execute>b__0()

  at Oakton.CommandExecutor.execute(Func`1 execute)```
