### ISSUE TITLE
Compiled query using Any() function throw an Exception

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/marten#1090]
Having a fairly simple compiled query that does an `Any()` on a string value or a guid value (the only two property types I've tried) throws the following exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Linq
  StackTrace:
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Marten.Linq.Compiled.ContainmentParameterVisitor.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Marten.Linq.Compiled.CompiledQueryMemberExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at Marten.Linq.QueryHandlers.QueryHandlerFactory.findSetters(IQueryableDocument mapping, Type queryType, Expression expression, ISerializer serializer)
   at Marten.Linq.QueryHandlers.QueryHandlerFactory.buildCachedQuery[TDoc,TOut](Type queryType, ICompiledQuery`2 query)
   at Marten.Linq.QueryHandlers.QueryHandlerFactory.HandlerFor[TDoc,TOut](ICompiledQuery`2 query, QueryStatistics& stats)
   at Marten.QuerySession.Query[TDoc,TOut](ICompiledQuery`2 query)
   at MartenCompiledQueryError.Program.Main(String[] args) in C:\Users\CeeGee\Source\MartenCompiledQueryError\MartenCompiledQueryError\Program.cs:line 33
```

A simple project that recreates the problem can be found here: https://gist.github.com/CodingGorilla/93a5e8204c9dd00b047e18a986fdfaae

**Comment by mysticmind** [comment]
This issue related to the issue #784.
