### ISSUE TITLE
Connection String set CommandTimeout is ignored, default of 30 is used

### ISSUE THREAD

**Issue by adonnelly** [JasperFx/marten#1178]
Occasionally a query will timeout after 30 seconds despite having set the command timeout set to 0. On inspection of the exception raised by Marten I can see the command Timeout was set to 30. 
>var connectionStringBuilder = new NpgsqlConnectionStringBuilder {
                    Host = connectionSettings.Host,
                    Database = connectionSettings.Database,
                    Username = connectionSettings.Username,
                    Password = connectionSettings.Password,
                    CommandTimeout = 0,
                    ConnectionIdleLifetime = 0,
                    Timeout = 0,
                    Port = connectionSettings.Port,
                    MaxPoolSize = connectionSettings.MaxPoolSize};

>var documentStore = DocumentStore.For(_ =>
                {
                    _.Connection(connectionStringBuilder.ToString());
                    _.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
                });
var session = store.OpenSession();
var query = $"SELECT entityid FROM mt_doc_entity WHERE id = ANY(?) GROUP BY entityid;";
var values = session.Query<string>(query, Ids.ToList());

After 30 seconds an exception is raised

>{Npgsql.NpgsqlException (0x80004005): Exception while reading from stream ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---

When I examine the exception I can see the command timeout was set to 30.

![image](https://user-images.githubusercontent.com/724582/51988172-f62a2a00-249b-11e9-8fd5-c57258a39ea4.png)

rest of exception
{Marten.MartenCommandException: Marten Command Failure:
SELECT id FROM mt_doc_entity WHERE id = ANY(:arg0) GROUP BY id;

Exception while reading from stream ---> Npgsql.NpgsqlException: Exception while reading from stream ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Npgsql.ReadBuffer.Ensure(Int32 count, Boolean async, Boolean dontBreakOnTimeouts)
   --- End of inner exception stack trace ---
   at Npgsql.ReadBuffer.Ensure(Int32 count, Boolean async, Boolean dontBreakOnTimeouts)
   at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteReader()
   at Marten.Services.CommandRunnerExtensions.<>c__DisplayClass2_0`1.<Fetch>b__0(NpgsqlCommand c) in C:\Projects\marten\src\Marten\Services\CommandRunnerExtensions.cs:line 51
   at Marten.Services.ManagedConnection.Execute[T](NpgsqlCommand cmd, Func`2 func) in C:\Projects\marten\src\Marten\Services\ManagedConnection.cs:line 271
   --- End of inner exception stack trace ---
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e) in C:\Projects\marten\src\Marten\Services\ManagedConnection.cs:line 196
   at Marten.Services.ManagedConnection.Execute[T](NpgsqlCommand cmd, Func`2 func) in C:\Projects\marten\src\Marten\Services\ManagedConnection.cs:line 277
   at Marten.Services.CommandRunnerExtensions.Fetch[T](IManagedConnection runner, IQueryHandler`1 handler, IIdentityMap map, QueryStatistics stats, ITenant tenant) in C:\Projects\marten\src\Marten\Services\CommandRunnerExtensions.cs:line 49
   at Marten.QuerySession.Query[T](String sql, Object[] parameters) in C:\Projects\marten\src\Marten\QuerySession.cs:line 72

    Command: {Npgsql.NpgsqlCommand}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: {Npgsql.NpgsqlException (0x80004005): Exception while reading from stream ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Npgsql.ReadBuffer.Ensure(Int32 count, Boolean async, Boolean dontBreakOnTimeouts)
   at Npgsql.ReadBuffer.Ensure(Int32 count, Boolean async, Boolean dontBreakOnTimeouts)
   at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behaviorBoolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteReader()
   at Marten.Services.CommandRunnerExtensions.<>c__DisplayClass2_0`1.<Fetch>b__0(NpgsqlCommand c) in C:\Projects\marten\src\Marten\Services\CommandRunnerExtensions.cs:line 51
   at Marten.Services.ManagedConnection.Execute[T](NpgsqlCommand cmd, Func`2 func) in C:\Projects\marten\src\Marten\Services\ManagedConnection.cs:line 271}

**Comment by jokokko** [comment]
While easy to fix, supporting CommandTimeout set in cstring and still allowing its override in session options requires some signature changes (since cstring lives in ConnectionFactory, a few other places default timeout to 30).
