### ISSUE TITLE
.OrderBy() fails when retrieving value from subcollection

### ISSUE THREAD

**Issue by robert-skarzycki** [JasperFx/marten#1217]
Having that model (https://gist.github.com/robert-skarzycki/c0c26f32e0000c17faabc6c5debde55c) and data inserting code (https://gist.github.com/robert-skarzycki/aa92e11a27fdb33ea8f89e59ea90329d), this query fails:
```
var res = session
                .Query<Root>()
                .OrderBy(p => p.ChildsLevel1.Count()).ToList();
```
with following exception:
```
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Linq.dll: 'Sequence contains no elements'
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Marten.Schema.Field..ctor(EnumStorage enumStorage, MemberInfo[] members)
   at Marten.Schema.JsonLocatorField..ctor(String dataLocator, EnumStorage enumStyle, Casing casing, MemberInfo[] members)
   at Marten.Schema.FieldCollection.<>c__DisplayClass8_0.<FieldFor>b__1(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.Schema.DocumentMappingExtensions.JsonLocator(IQueryableDocument mapping, Expression expression)
   at Marten.Linq.Model.LinqQuery`1.writeOrderByFragment(CommandBuilder sql, Ordering clause)
   at Marten.Linq.Model.LinqQuery`1.writeOrderClause(CommandBuilder sql)
   at Marten.Linq.Model.LinqQuery`1.ConfigureCommand(CommandBuilder sql, Int32 limit)
   at Marten.Util.CommandBuilder.ToCommand(ITenant tenant, IQueryHandler handler)
   at Marten.Services.CommandRunnerExtensions.Fetch[T](IManagedConnection runner, IQueryHandler`1 handler, IIdentityMap map, QueryStatistics stats, ITenant tenant)
   at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[...]
```

Actually, I'm trying to have even more complex query over subcollection elements (i.e. to get one "child" item and retrieve value from it to order by - e.g. order parents by oldest child age), but it fails even with much simpler queries.

**Comment by oskardudycz** [comment]
@robert-skarzycki we'll try to get this in https://github.com/JasperFx/marten/issues/1201

**Comment by jeremydmiller** [comment]
I'm gonna call this one too as part of #744

**Comment by jeremydmiller** [comment]
@robert-skarzycki It's taken forever, but I'm dealing with this one right now as part of the big V4 Linq overhaul.
