### ISSUE TITLE
JsonNetSerializer OutOfMemoryException on very large object graphs

### ISSUE THREAD

**Issue by leypascua** [JasperFx/marten#1233]
Hi, we've hit a snag when trying to fetch a (very) large object graph, below is the (redacted) stack trace:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at Marten.Services.JsonNetSerializer.ToJson(Object document)
   at Marten.Services.TrackedEntity..ctor(Object id, ISerializer serializer, Type documentType, Object document, TextReader json)
   at Marten.Services.DirtyTrackingIdentityMap.ToCache(Object id, Type concreteType, Object document, TextReader json, UnitOfWorkOrigin origin)
   at Marten.Services.IdentityMap`1.<>c__DisplayClass9_0`1.<Get>b__0(Object _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.Services.IdentityMap`1.Get[T](Object id, Type concreteType, TextReader json, Nullable`1 version)
   at Marten.Services.IdentityMap`1.Get[T](Object id, TextReader json, Nullable`1 version)
   at Marten.Schema.DocumentStorage`1.Resolve(Int32 startingIndex, DbDataReader reader, IIdentityMap map)
   at Marten.Linq.WholeDocumentSelector`1.Resolve(DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Linq.QueryHandlers.OneResultHandler`1.Handle(DbDataReader reader, IIdentityMap map, QueryStatistics stats)
   at Marten.Services.CommandRunnerExtensions.<>c__DisplayClass2_0`1.<Fetch>b__0(NpgsqlCommand c)
   at Marten.Services.ManagedConnection.<>c__DisplayClass37_0`1.<Execute>b__0()
   at Marten.NulloRetryPolicy.Execute[TResult](Func`1 operation)
   at Marten.Services.ManagedConnection.Execute[T](NpgsqlCommand cmd, Func`2 func)
   at Marten.Services.CommandRunnerExtensions.Fetch[T](IManagedConnection runner, IQueryHandler`1 handler, IIdentityMap map, QueryStatistics stats, ITenant tenant)
   at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteSingle[T](QueryModel queryModel, Boolean returnDefaultWhenEmpty)
   at Remotion.Linq.Clauses.StreamedData.StreamedSingleValueInfo.ExecuteSingleQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSingleValueInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
```

We may need to break the object into smaller parts but maybe this is a legit bug so I'm filing it.

Thanks!

**Comment by leypascua** [comment]
Seems that the object graph is too big to be serialized into a string variable in [TrackedEntity.cs](https://github.com/JasperFx/marten/blob/master/src/Marten/Services/TrackedEntity.cs)

**Comment by mysticmind** [comment]
@leypascua it would help if you could provide a repro use case for us to troubleshoot this.

**Comment by jeremydmiller** [comment]
@leypascua Interesting. Can you shift to a lighter weight session instead of the "dirty checking" session? That would get you around the memory issue. That probably isn't super efficient with that large of an object anyway.

**Comment by jeremydmiller** [comment]
@mysticmind I think I'd look to beat this first with documentation, then by maybe shifting the TrackedEntity to use a byte[] or stream?

**Comment by leypascua** [comment]
@mysticmind Unfortunately, my specific use-case contains sensitive info so can't share it. 
@jeremydmiller I think Marten should prevent large object graphs to be persisted in the first place. Else, it should be possible to set this up via configuration (where it tries to use a FileStream as a backing store instead of a string/bytearray/MemoryStream when it encounters an OutOfMemoryException on certain objects that may need it.

**Comment by leypascua** [comment]
Here's a simple test to demonstrate the issue:

```
public class TrackedEntityTests
    {
        static readonly LargeObjectTest instance = InitializeTestSubject();

        [Fact]
        public void detect_changes_on_large_object()
        {
            JsonNetSerializer serializer = new JsonNetSerializer();
            // throws an OutOfMemoryException
            var te = new TrackedEntity(Guid.NewGuid(), serializer, typeof(LargeObjectTest), instance, null);

            te.DetectChange();
        }

        private static LargeObjectTest InitializeTestSubject()
        {
            var result = new LargeObjectTest();
            string base64EncodedValue = "".PadLeft(1024200, '0');

            Parallel.For(0, 999999, idx =>
            {
                result.Values.Add(new LargeObjectTest.Payload
                {
                    Open = decimal.MaxValue,
                    High = decimal.MaxValue,
                    Low = decimal.MaxValue,
                    Close = decimal.MaxValue,
                    OrderBookBase64 = base64EncodedValue
                });
            });

            return result;
        }
    }

    public class LargeObjectTest
    {   
        public LargeObjectTest()
        {
            this.Values = new List<Payload>();
        }

        public IList<Payload> Values { get; set; }

        public class Payload
        {
            public decimal Open { get; set; }
            public decimal High { get; set; }
            public decimal Low { get; set; }
            public decimal Close { get; set; }
            public decimal Volume { get; set; }
            public string OrderBookBase64 { get; set; }
        }
    }
```

**Comment by jeremydmiller** [comment]
@leypascua Again, is there any reason why you can't just switch to a lightweight session instead of a dirty checking session to sidestep this issue?

**Comment by leypascua** [comment]
Already did that, thanks for the suggestion.  Feel free to close the issue if there's no plan in fixing this for now.

**Comment by oskardudycz** [comment]
@leypascua I assume that using lightweight session solved the case.

I'm afraid that until we work more on streaming (https://github.com/JasperFx/marten/issues/585) not much will be done in this topic.

I'm closing it for now. Feel free to write if you have more questions, findings, etc. - we'll reopen then.

**Comment by leypascua** [comment]
Not sure why, but the exception is thrown in a rather unpredictable manner.

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at Marten.Services.JsonNetSerializer.ToJson(Object document)
   at Marten.Schema.DocumentStorage`1.RegisterUpdate(String tenantIdOverride, UpdateStyle updateStyle, UpdateBatch batch, Object entity)
   at Marten.Services.DocumentStorageOperation.Persist(UpdateBatch batch, ITenant tenant)
   at Marten.Services.UnitOfWork.determineChanges(UpdateBatch batch)
   at Marten.Services.UnitOfWork.buildChangeSet(UpdateBatch batch)
   at Marten.Services.UnitOfWork.ApplyChanges(UpdateBatch batch)
   at Marten.DocumentSession.SaveChanges()
```

This is after using LightweightSession
