### ISSUE TITLE
Fix flaky `Marten.Testing.Examples.MultiTenancy.use_multiple_tenants` test

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#1236]
```
[xUnit.net 00:00:49.8800387]     Marten.Testing.Examples.MultiTenancy.use_multiple_tenants [FAIL]
Failed   Marten.Testing.Examples.MultiTenancy.use_multiple_tenants
Error Message:
 System.InvalidOperationException : Marten cannot derive updates for objects public.mt_doc_user
Stack Trace:
   at Marten.Schema.SchemaPatch.AssertPatchingIsValid(AutoCreate autoCreate) in /home/travis/build/JasperFx/marten/src/Marten/Schema/SchemaPatch.cs:line 162
   at Marten.Schema.SchemaPatch.Apply(NpgsqlConnection conn, AutoCreate autoCreate, ISchemaObject[] schemaObjects) in /home/travis/build/JasperFx/marten/src/Marten/Schema/SchemaPatch.cs:line 208
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature) in /home/travis/build/JasperFx/marten/src/Marten/Storage/Tenant.cs:line 128
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType) in /home/travis/build/JasperFx/marten/src/Marten/Storage/Tenant.cs:line 112
   at Marten.Storage.Tenant.EnsureStorageExists(Type featureType) in /home/travis/build/JasperFx/marten/src/Marten/Storage/Tenant.cs:line 78
   at Marten.Storage.Tenant.StorageFor(Type documentType) in /home/travis/build/JasperFx/marten/src/Marten/Storage/Tenant.cs:line 165
   at Marten.Storage.LightweightTenant.StorageFor(Type documentType) in /home/travis/build/JasperFx/marten/src/Marten/Storage/DefaultTenancy.cs:line 57
   at Marten.DocumentSession.Store[T](T[] entities) in /home/travis/build/JasperFx/marten/src/Marten/DocumentSession.cs:line 127
   at Marten.Testing.Examples.MultiTenancy.use_multiple_tenants() in /home/travis/build/JasperFx/marten/src/Marten.Testing/Examples/MultiTenancy.cs:line 30
CREATE OR REPLACE FUNCTION public.mt_immutable_timestamp(value text) RETURNS timestamp without time zone LANGUAGE sql IMMUTABLE AS $function$
    select value::timestamp
$function$;
CREATE OR REPLACE FUNCTION public.mt_immutable_timestamptz(value text) RETURNS timestamp with time zone LANGUAGE sql IMMUTABLE AS $function$
    select value::timestamptz
$function$;
DROP TABLE IF EXISTS public.mt_doc_intdoc CASCADE;
CREATE TABLE public.mt_doc_intdoc (
    id                  integer CONSTRAINT pk_mt_doc_intdoc PRIMARY KEY,
    data                jsonb NOT NULL,
    mt_last_modified    timestamp with time zone DEFAULT transaction_timestamp(),
    mt_version          uuid NOT NULL default(md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar 
);
COMMENT ON TABLE public.mt_doc_intdoc IS 'origin:Marten.IDocumentStore, Marten, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null';
CREATE OR REPLACE FUNCTION public.mt_upsert_intdoc(doc JSONB, docDotNetType varchar, docId integer, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
DECLARE
  final_version uuid;
BEGIN
INSERT INTO public.mt_doc_intdoc ("data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pk_mt_doc_intdoc
  DO UPDATE SET "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp();
  SELECT mt_version FROM public.mt_doc_intdoc into final_version WHERE id = docId ;
  RETURN final_version;
END;
$function$;
CREATE OR REPLACE FUNCTION public.mt_insert_intdoc(doc JSONB, docDotNetType varchar, docId integer, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
BEGIN
INSERT INTO public.mt_doc_intdoc ("data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp());
  RETURN docVersion;
END;
$function$;
CREATE OR REPLACE FUNCTION public.mt_update_intdoc(doc JSONB, docDotNetType varchar, docId integer, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
DECLARE
  final_version uuid;
BEGIN
  UPDATE public.mt_doc_intdoc SET "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp() where id = docId;
  SELECT mt_version FROM public.mt_doc_intdoc into final_version WHERE id = docId ;
  RETURN final_version;
END;
$function$;
DROP TABLE IF EXISTS public.mt_hilo CASCADE;
CREATE TABLE public.mt_hilo (
    entity_name    varchar CONSTRAINT pk_mt_hilo PRIMARY KEY,
    hi_value       bigint default 0
);
COMMENT ON TABLE public.mt_hilo IS 'origin:Marten.IDocumentStore, Marten, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null';
CREATE OR REPLACE FUNCTION public.mt_get_next_hi(entity varchar) RETURNS int AS $$
DECLARE
	current_value bigint;
	next_value bigint;
BEGIN
	select hi_value into current_value from public.mt_hilo where entity_name = entity;
	IF current_value is null THEN
		insert into public.mt_hilo (entity_name, hi_value) values (entity, 0);
		next_value := 0;
	ELSE
		next_value := current_value + 1;
		update public.mt_hilo set hi_value = next_value where entity_name = entity;
	END IF;
	return next_value;
END
$$ LANGUAGE plpgsql;
-- public.mt_get_next_hi Diff
DROP FUNCTION public.mt_get_next_hi(entity character varying) cascade;
-- public.mt_get_next_hi Diff
CREATE OR REPLACE FUNCTION public.mt_get_next_hi(entity varchar) RETURNS int AS $$
DECLARE
	current_value bigint;
	next_value bigint;
BEGIN
	select hi_value into current_value from public.mt_hilo where entity_name = entity;
	IF current_value is null THEN
		insert into public.mt_hilo (entity_name, hi_value) values (entity, 0);
		next_value := 0;
	ELSE
		next_value := current_value + 1;
		update public.mt_hilo set hi_value = next_value where entity_name = entity;
	END IF;
	return next_value;
END
$$ LANGUAGE plpgsql;
```

See details: https://travis-ci.org/JasperFx/marten/builds/511127895?utm_medium=notification&utm_source=email

**Comment by mysticmind** [comment]
@oskardudycz there are couple more flaky tests as well.

**Comment by oskardudycz** [comment]
@mysticmind that's true, we can link them here and fix them in single PR. Those that I saw seems to be related to using different document store configuration for the same document type (eg. `User`).

**Comment by mysticmind** [comment]
```
[xUnit.net 00:00:12.8985169]     Marten.Testing.Linq.query_with_dates_Tests.can_select_DateTimeOffset_and_will_return_localtime [FAIL]
Failed   Marten.Testing.Linq.query_with_dates_Tests.can_select_DateTimeOffset_and_will_return_localtime
Error Message:
 Shouldly.ShouldAssertException : 3/26/19 5:25:45 AM +00:00
    should be
3/26/19 5:25:45 AM +00:00
    but was not
Stack Trace:
   at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
   at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected)
   at Marten.Testing.SpecificationExtensions.ShouldBeEqualWithDbPrecision(DateTimeOffset actual, DateTimeOffset expected) in /home/travis/build/JasperFx/marten/src/Marten.Testing/SpecificationExtensions.cs:line 201
   at Marten.Testing.Linq.query_with_dates_Tests.can_select_DateTimeOffset_and_will_return_localtime() in /home/travis/build/JasperFx/marten/src/Marten.Testing/Linq/query_with_dates_Tests.cs:line 28
```

**Comment by mysticmind** [comment]
```
[xUnit.net 00:02:10.5584069]     Marten.Testing.MultiTenancy.can_generate_database_objects_when_tenanted.do_not_blow_up [FAIL]
Failed   Marten.Testing.MultiTenancy.can_generate_database_objects_when_tenanted.do_not_blow_up
Error Message:
 System.InvalidOperationException : Marten cannot derive updates for objects public.mt_doc_user
Stack Trace:
   at Marten.Schema.SchemaPatch.AssertPatchingIsValid(AutoCreate autoCreate) in C:\projects\marten\src\Marten\Schema\SchemaPatch.cs:line 162
   at Marten.Schema.SchemaPatch.Apply(NpgsqlConnection conn, AutoCreate autoCreate, ISchemaObject[] schemaObjects) in C:\projects\marten\src\Marten\Schema\SchemaPatch.cs:line 208
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature) in C:\projects\marten\src\Marten\Storage\Tenant.cs:line 128
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType) in C:\projects\marten\src\Marten\Storage\Tenant.cs:line 112
   at Marten.Storage.Tenant.EnsureStorageExists(Type featureType) in C:\projects\marten\src\Marten\Storage\Tenant.cs:line 78
   at Marten.Testing.MultiTenancy.can_generate_database_objects_when_tenanted.do_not_blow_up() in C:\projects\marten\src\Marten.Testing\MultiTenancy\can_generate_database_objects_when_tenanted.cs:line 21
CREATE OR REPLACE FUNCTION public.mt_immutable_timestamp(value text) RETURNS timestamp without time zone LANGUAGE sql IMMUTABLE AS $function$
    select value::timestamp
$function$;
....
....
```

**Comment by mysticmind** [comment]
```
[xUnit.net 00:00:36.0057681]     Marten.Testing.Bugs.Bug_962_initial_data_populate_causing_null_ref_ex.initial_data_should_populate_db [FAIL]
Failed   Marten.Testing.Bugs.Bug_962_initial_data_populate_causing_null_ref_ex.initial_data_should_populate_db
Error Message:
 System.InvalidOperationException : Marten cannot derive updates for objects public.mt_doc_user
Stack Trace:
   at Marten.Schema.SchemaPatch.AssertPatchingIsValid(AutoCreate autoCreate) in /home/travis/build/mysticmind/marten/src/Marten/Schema/SchemaPatch.cs:line 149
```
