### ISSUE TITLE
Exception when filtering on `uint` property

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#1256]
When trying to filter on a `uint` property using a linq query, I get an exception:

```
42883: operator does not exist: jsonb = integer ---> Npgsql.PostgresException: 42883: operator does not exist: jsonb = integer
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1012
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 444
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1217
   at Marten.Services.CommandRunnerExtensions.<>c__DisplayClass3_0`1.<<FetchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Marten.Services.ManagedConnection.<>c__DisplayClass41_0`1.<<ExecuteAsync>b__0>d.MoveNext()
```

The linq query is standard `.Where(x => x.MyUIntProperty == 123)`

If I inspect the command text that Marten is generating for the linq query, it looks like:

`CAST(d.data -> 'Message' ->> 'MyUIntProperty' as jsonb) = :arg3)`

**Comment by cocowalla** [comment]
As a workaround, for now I've been able to use a combination of `MatchesSql` and a cast to `int`:

`x => x.MatchesSql("(d.data ->> 'MyUIntProperty')::bigint = ?", (int)myUInt))`

**Comment by cocowalla** [comment]
I found [TypeMappings](https://github.com/JasperFx/marten/blob/f327ba3925c8cf2738b86a66f36d3a6c1840df34/src/Marten/Util/TypeMappings.cs) and tried various combinations of `RegisterMapping()`, but none seemed to work. Not sure if this is the right path tho.

**Comment by jeremydmiller** [comment]
I'm taking this one this morning.

**Comment by jeremydmiller** [comment]
And it looks like we need to take this up with the Npgsql team

**Comment by jeremydmiller** [comment]
I tried again this morning, and I was able to get a fix in.
