### ISSUE TITLE
Occasionally getting MartenCommandException instead of EventStreamUnexpectedMaxEventIdException

### ISSUE THREAD

**Issue by wastaz** [JasperFx/marten#1465]
Sometimes, instead of an `Marten.Services.EventStreamUnexpectedMaxEventIdException` I get the following exception thrown instead.

From what I can see, this is still an optimistic concurrency exception in the event store, and it "cleans up" on a retry, but when you cant depend on the correct exception getting thrown....it makes exception handling a bit messy.

This has been an issue that I have seen for a long time (but Ive been too lazy to create an issue for it, sorry). So its nothing that has been introduced recently.

```
	
Exception=Marten.Exceptions.MartenCommandException: Marten Command Failure:$
select public.mt_append_event(stream := :arg4, stream_type := :arg5, tenantid := :arg6, event_ids := :arg7, event_types := :arg8, dotnet_types := :arg9, bodies := :arg10)$
$
23505: duplicate key value violates unique constraint "pk_mt_events_stream_and_version"
 ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "pk_mt_events_stream_and_version"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Marten.Services.UpdateBatch.executeCallbacksAsync(NpgsqlCommand cmd, CancellationToken tkn, BatchCommand batch, List`1 list)
   at Marten.Services.UpdateBatch.<>c__DisplayClass27_1.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Marten.Services.ManagedConnection.ExecuteAsync(NpgsqlCommand cmd, Func`3 action, CancellationToken token)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "pk_mt_events_stream_and_version"
    Detail: Key (stream_id, version)=(33243dda-99af-4968-864a-aa1365dac215, 11) already exists.
    Where: SQL statement "insert into public.mt_events
			(seq_id, id, stream_id, version, data, type, tenant_id, mt_dotnet_type)
		values
			(seq, event_id, stream, event_version, body, event_type, tenantid, dotnet_types[index])"
PL/pgSQL function mt_append_event(uuid,character varying,character varying,uuid[],character varying[],character varying[],jsonb[]) line 37 at SQL statement
    SchemaName: public
    TableName: mt_events
    ConstraintName: pk_mt_events_stream_and_version
    File: nbtinsert.c
    Line: 433
    Routine: _bt_check_unique
   --- End of inner exception stack trace ---
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Services.ManagedConnection.ExecuteAsync(NpgsqlCommand cmd, Func`3 action, CancellationToken token)
   at Marten.Services.UpdateBatch.ExecuteAsync(CancellationToken token)
   at Marten.Services.UnitOfWork.ApplyChangesAsync(UpdateBatch batch, CancellationToken token)
   at Marten.DocumentSession.SaveChangesAsync(CancellationToken token)
```

**Comment by oskardudycz** [comment]
@wastaz I think that you're hitting [the last guard](https://media.giphy.com/media/njYrp176NQsHS/giphy.gif) - so the unique constraint that's blocking the safe when the code logic won't block it (eg. because of the parallel processing).
I think that we can map this exception as you suggested.
