### ISSUE TITLE
Exception when mixing Attributes and StoreOptions for Schema

### ISSUE THREAD

**Issue by ParthaBoocha** [JasperFx/marten#1593]
Marten v3.13.2, .NET Core v3.1, XUnit v2.4.0

I have most of my Schema Mappings via Attributes on Data Models, but couldn't find a way to define SubClass mapping via attributes. So, as a compromise I tried to define that via MartenRegistry/StoreOptions and got the following error when I did that:

```
  Error Message:
   System.TypeInitializationException : The type initializer for 'Data.Tests.TestSessionFactory' threw an exception.
---- System.InvalidOperationException : Sequence contains no elements
  Stack Trace:
     at Data.Tests.TestSessionFactory..ctor()
   at Data.Tests.ParentModelTests..ctor() in /Users/zzz/code/yyy/Data.Tests/ParentModelTests.cs:line 17
----- Inner Stack Trace -----
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Marten.Schema.UniqueIndexAttribute.Modify(DocumentMapping mapping, MemberInfo member)
   at Marten.Schema.DocumentMapping.<>c__DisplayClass27_0.<applyAnyMartenAttributes>b__9(MartenAttribute att)
   at Baseline.Reflection.ReflectionExtensions.ForAttribute[T](MemberInfo provider, Action`1 action)
   at Marten.Schema.DocumentMapping.<applyAnyMartenAttributes>b__27_2(PropertyInfo prop)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Schema.DocumentMapping.applyAnyMartenAttributes(Type documentType)
   at Marten.Schema.DocumentMapping..ctor(Type documentType, StoreOptions storeOptions)
   at Marten.Schema.SubClassMapping..ctor(Type documentType, DocumentMapping parent, StoreOptions storeOptions, String alias)
   at Marten.Schema.DocumentMapping.AddSubClass(Type subclassType, String alias)
   at Marten.MartenRegistry.DocumentMappingExpression`1.<>c__DisplayClass28_0.<AddSubClass>b__0(DocumentMapping`1 mapping)
   at Marten.MartenRegistry.DocumentMappingExpression`1.<>c__DisplayClass26_0.<set_alter>b__0(StoreOptions o)
   at Marten.MartenRegistry.Apply(StoreOptions options)
   at Marten.StoreOptions.ApplyConfiguration()
   at Marten.DocumentStore..ctor(StoreOptions options)
   at Marten.DocumentStore.For(Action`1 configure)
   at Data.Tests.TestSessionFactory..cctor() in /Users/zzz/code/yyy/Data.Tests/TestSessionFactory.cs:line 12
```
To troubleshoot, I removed the UniqueIndex mapping attribute and added it alongside the SubClass mapping on StoreOptions and the exception went away and my tests passed.

Is there anything I am missing? Or is it not advisable to mix and match Schema mapping and I shall pick one approach and stick to it?
Alternatively, can I define SubClass mapping via Attributes? Because that would be my preferred method.

Thanks.

**Comment by mysticmind** [comment]
@ParthaBoocha It would help if you could provide us a repro code or add a failing unit test for us to check.

**Comment by ParthaBoocha** [comment]
[marten.zip](https://github.com/JasperFx/marten/files/5581090/marten.zip)
Thanks @mysticmind . The attached zip file has the stripped down code to recreate the exception. Simply run `dotnet test Data.Tests/Data.Tests.csproj`

To fix exception:
1. Comment line # 12 in Models/User.cs file
2. Uncomment line # 23 in Bootstrapper.cs file

**Comment by mysticmind** [comment]
@ParthaBoocha Thanks you, will check and keep you posted.

**Comment by mysticmind** [comment]
@ParthaBoocha I have identified the issue and it is bug, we will fix it soon. In the interim, use the fluent interface when you want to add unique index on a sub-classed doc.

**Comment by jeremydmiller** [comment]
I don't think this is an issue any longer and there's no recent activity.
