### ISSUE TITLE
Support for Npgsql 5's connection multiplexing

### ISSUE THREAD

**Issue by Hawxy** [JasperFx/marten#1646]
http://www.npgsql.org/doc/release-notes/5.0.html#connection-multiplexing

I did some quick testing with this today, however it requires _all_ database operations to be async:

```
Synchronous command execution is not supported when multiplexing is on
   at Marten.Schema.SchemaPatch.Apply(NpgsqlConnection conn, AutoCreate autoCreate, ISchemaObject[] schemaObjects)
```

```
System.NotSupportedException: Synchronous command execution is not supported when multiplexing is on
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar()
   at Marten.Schema.DatabaseGenerator.IsNotInPgDatabase(String catalog, String maintenanceDb)
   at Marten.Schema.DatabaseGenerator.<>c__DisplayClass6_0.<CreateDb>b__0()
   at Marten.Schema.DatabaseGenerator.CreateDb(ITenant tenant, TenantDatabaseCreationExpressions config)
   at Marten.Schema.DatabaseGenerator.CreateDatabases(ITenancy tenancy, Action`1 configure)
```

**Comment by karelg** [comment]
@Hawxy  I guess there might be a problem also with ambient transactions when using connection multiplexing cause normally transactions would not work over multiple connections?

**Comment by jeremydmiller** [comment]
@Hawxy We can do this as part of 4.0, but there's gonna be some `GetAwaiter().GetResult()` action in there. Might as well do it now though.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] `IDocumentSchema` needs to be async all the way down. Do `GetAwaiter().GetResult()` as necessary **outside** of these services
- [ ] `ITenantSchema` async turtles all the way down

**Comment by jeremydmiller** [comment]
This is done in a branch.
