### ISSUE TITLE
Starting stream without events fails

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#1648]
Having such test when we're startin stream and saving it without events ends with failure

```csharp
using System;
using Marten.Exceptions;
using Marten.Integration.Tests.TestsInfrasructure;
using SharpTestsEx;
using Xunit;

namespace Marten.Integration.Tests.EventStore.Stream
{
    public class StreamStarting: MartenTest
    {
        public class IssueCreated
        {
            public Guid IssueId { get; set; }
            public string Description { get; set; }
        }

        public class IssueUpdated
        {
            public Guid IssueId { get; set; }
            public string Description { get; set; }
        }

        public class IssuesList { }

        [Fact]
        public void GivenNoEvents_WhenStreamIsStarting_ThenEventsAreSavedWithoutError()
        {
            var @event = new IssueCreated { IssueId = Guid.NewGuid(), Description = "Description" };

            var streamId = EventStore.StartStream<IssuesList>(@event.IssueId);

            Session.SaveChanges();

            streamId.Should().Not.Be.Null();
        }

        [Fact]
        public void GivenOneEvent_WhenStreamIsStarting_ThenEventsAreSavedWithoutError()
        {
            var @event = new IssueCreated { IssueId = Guid.NewGuid(), Description = "Description" };

            var streamId = EventStore.StartStream<IssuesList>(@event.IssueId, @event);

            streamId.Should().Not.Be.Null();

            Session.SaveChanges();
        }
    }
}
```

Error details:

```
  Failed Marten.Integration.Tests.EventStore.Stream.StreamStarting.GivenNoEvents_WhenStreamIsStarting_ThenEventsAreSavedWithoutError [102 ms]
  Error Message:
   System.InvalidOperationException : Cannot read a non-nullable collection of elements because the returned array contains nulls. Call GetFieldValue with a nullable array instead.
  Stack Trace:
     at Npgsql.TypeHandlers.ArrayHandler.ReadArray[TRequestedElement](NpgsqlReadBuffer buf, Boolean async, Int32 expectedDimensions)
   at Npgsql.TypeHandlers.ArrayHandler.Read[TRequestedArray](NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
   at Npgsql.TypeHandlers.ArrayHandler.Read[TRequestedArray](NpgsqlReadBuffer buf, Int32 len, FieldDescription fieldDescription)
   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
   at Marten.Events.AppendEventsOperation.Postprocess(DbDataReader reader, IList`1 exceptions)
   at Marten.Internal.UpdateBatch.applyCallbacks(IReadOnlyList`1 operations, DbDataReader reader)
   at Marten.Internal.UpdateBatch.ApplyChanges(IMartenSession session)
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChanges()
   at Marten.Integration.Tests.EventStore.Stream.StreamStarting.GivenNoEvents_WhenStreamIsStarting_ThenEventsAreSavedWithoutError() in C:\projects\eventsourcing-netcore\Marten.Integration.Tests\EventStore\Stream\StreamStarting.cs:line 32
```

**Comment by jokokko** [comment]
Btw. is there a use case for an empty stream? So it would basically just be metadata with version of 0. Or rather in Marten add guard & assert earlier that output is not null or empty and output a more descriptive exception?

**Comment by jeremydmiller** [comment]
Yeah, can we go with @jokokko 's suggestion and use a guard condition to make it throw if it detects teh `StartStream()` with no events?

**Comment by oskardudycz** [comment]
@jokokko @jeremydmiller I think that this makes sense.

**Comment by jeremydmiller** [comment]
This is actually a duplicate w/ #1388. Or the same fix would knock out both issues.
