### ISSUE TITLE
Identity map exception when adding not-found document to session

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#166]
If you attempt to load a document but it doesn't exist in the database, then an entry is added to the identity map with "null" for the document. If you then attempt to add a document with that Id to the session, :boom: - exception.

@jeremydmiller has confirmed this is a bug and not a feature. :)

**Comment by jeffdoolittle** [comment]
I added a test that exposes the bug. The resulting exception is:

> Test 'Marten.Testing.TrackingSession.document_session_load_not_found_then_stored_IdentityMap_Tests.then_a_document_can_be_added_with_then_specified_id' failed:
	System.InvalidOperationException : Document 'Marten.Testing.Documents.User' with same Id already added to the session.
	Services\IdentityMap.cs(74,0): at Marten.Services.IdentityMap.Store[T](Object id, T entity)
	at Marten.GeneratedCode.UserStorage.Store(IIdentityMap map, Object id, Object entity)
	DocumentSession.cs(74,0): at Marten.DocumentSession.Store[T](T[] entities)
	TrackingSession\document_session_load_not_found_then_stored_Tests.cs(22,0): at Marten.Testing.TrackingSession.document_session_load_not_found_then_stored_Tests`1.then_a_document_can_be_added_with_then_specified_id()
