### ISSUE TITLE
Greater than LINQ query using a float throws exception. It does work with double however!

### ISSUE THREAD

**Issue by superlogical** [JasperFx/marten#170]
````csharp
public class ProductDto
{
    public Guid Id { get; set; }

    public string Title { get; set; }
    public string Description { get; set; }

    public float Price { get; set; }
    public float? SalePrice { get; set; }

    public List<ImageDto> Images { get; set; }

    public ProductDto()
    {
        Images = new List<ImageDto>();
    }
}

[Route("")]
public ActionResult Index()
{
    using (var session = store.LightweightSession(IsolationLevel.ReadCommitted))
    {
        var products = session.Query<ProductDto>().Where(x => x.Price > 10.34f).ToList();
        return Json(products);
    }
}

System.Collections.Generic.KeyNotFoundException was unhandled by user code
  HResult=-2146232969
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at Marten.Util.TypeMappings.GetPgType(Type memberType)
       at Marten.Schema.Field..ctor(MemberInfo[] members)
       at Marten.Schema.Field..ctor(MemberInfo member)
       at Marten.Schema.JsonLocatorField..ctor(MemberInfo member)
       at Marten.Schema.DocumentMapping.<>c__DisplayClass58_0.<FieldFor>b__0(String name)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at Marten.Schema.DocumentMapping.FieldFor(MemberInfo member)
       at Marten.Schema.DocumentMapping.FieldFor(IEnumerable`1 members)
       at Marten.Linq.MartenExpressionParser.JsonLocator(IDocumentMapping mapping, Expression expression)
       at Marten.Linq.MartenExpressionParser.buildSimpleWhereClause(IDocumentMapping mapping, BinaryExpression binary)
       at Marten.Linq.MartenExpressionParser.GetWhereFragment(IDocumentMapping mapping, BinaryExpression binary)
       at Marten.Linq.MartenExpressionParser.ParseWhereFragment(IDocumentMapping mapping, Expression expression)
       at Marten.Linq.DocumentQuery.buildWhereClause()
       at Marten.Linq.DocumentQuery.ConfigureCommand(NpgsqlCommand command)
       at Marten.Linq.MartenQueryExecutor.BuildCommand(QueryModel queryModel)
       at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
       at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
       at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
       at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
       at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
       at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       

````

**Comment by jeremydmiller** [comment]
@superlogical I would have tried to get you to do the PR for this, but it was tiny and I had the Marten codebase open anyway. This will be rolled into v0.8 or any v0.7.2+ nuget that comes up.

Do you want this sooner rather than later?
