### ISSUE TITLE
Schema migration fails if there are multiple schema changes containing index changes

### ISSUE THREAD

**Issue by VilleHakli** [JasperFx/marten#1822]
In Marten v4 alpha 11 when migrating database schema, exception is thrown if there are multiple schema changes containing index changes.

```
Marten.Exceptions.MartenSchemaException
DDL Execution for 'All Configured Changes' Failed!

drop index concurrently if exists bugs.mt_doc_testdocument_idx_first_name;
drop index concurrently if exists bugs.mt_doc_testdocument_idx_last_name;
CREATE INDEX mt_doc_testdocument_idx_first_name ON bugs.mt_doc_testdocument USING btree ( lower(data ->> 'FirstName'));
CREATE INDEX mt_doc_testdocument_idx_last_name ON bugs.mt_doc_testdocument USING btree ( lower(data ->> 'LastName'));

   at Marten.Storage.TenantSchema.ApplyAllConfiguredChangesToDatabase(Nullable`1 withCreateSchemaObjects) in C:\marten\src\Marten\Storage\TenantSchema.cs:line 159
   at Marten.Testing.Bugs.Bug_xxxx_recreating_index_fails_if_there_are_more_than_one_change.should_be_able_to_migrate_schema_with_multiple_schema_changes() in C:\marten\src\Marten.Testing\Bugs\Bug_1822_recreating_index_fails.cs:line 39
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

Npgsql.PostgresException
0A000: DROP INDEX CONCURRENTLY must be first action in transaction
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Weasel.Postgresql.SchemaMigration.ApplyAll(NpgsqlConnection conn, DdlRules rules, AutoCreate autoCreate, Action`1 logSql, Action`2 onFailure)
   at Marten.Storage.TenantSchema.ApplyAllConfiguredChangesToDatabase(Nullable`1 withCreateSchemaObjects) in C:\marten\src\Marten\Storage\TenantSchema.cs:line 153
```

Test case to reproduce the issue
```csharp
using System;
using System.Threading.Tasks;

using Bug1822;

using Marten.Schema;
using Marten.Testing.Harness;

using Weasel.Postgresql;

using Xunit;

namespace Marten.Testing.Bugs
{
    public class Bug_1822_recreating_index_fails_if_there_are_more_than_one_change: BugIntegrationContext
    {
        [Fact]
        public async Task should_be_able_to_migrate_schema_with_multiple_schema_changes()
        {
            using var documentStore = SeparateStore(x =>
            {
                x.AutoCreateSchemaObjects = AutoCreate.All;
                x.Schema.For<TestDocument>()
                    .Index(y => y.FirstName, index => index.Casing = ComputedIndex.Casings.Lower)
                    .Index(y => y.LastName, index => index.Casing = ComputedIndex.Casings.Lower);
            });

            await documentStore.Advanced.Clean.CompletelyRemoveAllAsync();
            await documentStore.Schema.ApplyAllConfiguredChangesToDatabase(AutoCreate.All);

            using var secondDocumentStore = SeparateStore(x =>
            {
                x.AutoCreateSchemaObjects = AutoCreate.All;
                x.Schema.For<TestDocument>()
                    .Index(y => y.FirstName, index => index.Casing = ComputedIndex.Casings.Upper)
                    .Index(y => y.LastName, index => index.Casing = ComputedIndex.Casings.Upper);
            });

            await documentStore.Schema.ApplyAllConfiguredChangesToDatabase(AutoCreate.All);
        }
    }
}

namespace Bug1822
{
    public class TestDocument
    {
        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
```

The test case is somewhat hacky as it uses two different document stores, but I couldn't come up with other solution to migrate existing schema.

**Comment by VilleHakli** [comment]
Using PostgreSQL 11.5 (docker image ionx/postgres-plv8:11.5).
