### ISSUE TITLE
> Alpha11, UpsertProblems

### ISSUE THREAD

**Issue by xevilmaxx** [JasperFx/marten#1854]
Hi, recently i tried an upgrade to version: **Alpha 11** (**also r1 and r2**).
I have following issue in upsert:
Basically it tells:
**There isnt contraint: _pk_mt_doc_transit_ for table: _mt_doc_transit_**

But its not really true, **constraint exists but its named in following syntax:** **_mt_doc_transit_pkey_**

---

`
2021-07-06 16:41:49.6762|ERROR|LibRtDb.Services.TransitsService|Marten.Exceptions.MartenCommandException: Marten Command Failure:$
select parko_rts.mt_upsert_transit(:p0, :p1, :p2, :p3);$
$
42704: il vincolo "pk_mt_doc_transit" per la tabella "mt_doc_transit" non esiste
 ---> Npgsql.PostgresException (0x80004005): 42704: il vincolo "pk_mt_doc_transit" per la tabella "mt_doc_transit" non esiste
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marten.NulloRetryPolicy.Execute[TResult](Func`1 operation)
   at Marten.Services.ManagedConnection.ExecuteReader(NpgsqlCommand command)
  Exception data:
    Severity: ERRORE
    SqlState: 42704
    MessageText: il vincolo "pk_mt_doc_transit" per la tabella "mt_doc_transit" non esiste
    Where: istruzione SQL "INSERT INTO parko_rts.mt_doc_transit ("data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pk_mt_doc_transit
  DO UPDATE SET "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp()"
funzione PL/pgSQL parko_rts.mt_upsert_transit(jsonb,character varying,bigint,uuid) riga 5 a istruzione SQL
    File: d:\pginstaller_13.auto\postgres.windows-x64\src\backend\catalog\pg_constraint.c
    Line: 968
    Routine: get_relation_constraint_attnos
   --- End of inner exception stack trace ---
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Baseline.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(NpgsqlCommand command, Exception exception)
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Services.ManagedConnection.ExecuteReader(NpgsqlCommand command)
   at Marten.Internal.UpdateBatch.ApplyChanges(IMartenSession session)
--- End of stack trace from previous location ---
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Marten.Internal.UpdateBatch.ApplyChanges(IMartenSession session)
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatch(IUpdateBatch batch)
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChanges()
   at LibRtDb.Services.TransitsService.UpdateTransit(Transit NewTransit) in C:\Users\maxym.oboyshev\source\repos\ParkO_V3\ADVANCED_RTS\RT_DB\LibRtDb\Services\TransitsService.cs:line 392
Marten Command Failure:$
select parko_rts.mt_upsert_transit(:p0, :p1, :p2, :p3);$
$
42704: il vincolo "pk_mt_doc_transit" per la tabella "mt_doc_transit" non esiste
`

**Comment by jeremydmiller** [comment]
@xevilmaxx Did you try to upgrade a Marten 3 database to Marten 4 when this occurs? This wouldn't happen from a fresh v4. We've had some periodic reports about this.

**Comment by xevilmaxx** [comment]
Actually for some time I've used:
 v4 alpha 9
After upgrade problems started.

For now i downgraded to V3 and all works fine.

When I had problems with latest v4 i even tried to drop whole db and let system recreate it, but it hasn't produced any noticeable change.

**Comment by jeremydmiller** [comment]
@xevilmaxx Can you give us anything that would help us reproduce this? I think @oskardudycz hit something similar converting an existing database from v3 to v4 quite awhile back, but otherwise, this isn't something other people are reporting and all our existing tests pass of course.

**Comment by xevilmaxx** [comment]
Hi,
Here is the code that is executed on strtup to create new DB if there is nothing, or insert missing tables:

```
public static DocumentStore GetContext()
        {
            try
            {

                if(Context == null)
                {

                    //var cfg = GetConfigs();
                    var connectionString = GetConnectionString();

                    log.Debug($"Connection String: {connectionString}");

                    Context = DocumentStore.For(_ => 
                    {

                        //Custom connection string
                        _.Connection(connectionString);

                        _.NameDataLength = 250;

                        //Custom Schema Name
                        _.DatabaseSchemaName = "ParkO_RTS";

                        //add json indexes also
                        // Add a gin index to Company's json data storage
                        //may be commented if performance is poor and you dont need do much readings
                        _.Schema.For<Transit>().GinIndexJsonData();
                        _.Schema.For<User>().GinIndexJsonData();
                        _.Schema.For<JsonDeviceConfigs>().GinIndexJsonData();
                        _.Schema.For<DynamicKey>().GinIndexJsonData();
                        _.Schema.For<Event>().GinIndexJsonData();
                        _.Schema.For<LanguageResource>().GinIndexJsonData();
                        _.Schema.For<SerialNumber>().GinIndexJsonData();

                        //My custom override for comparing objects not supported by Marten natively (for now alpha-8)
                        //Doable only in Marten >= v4
                        //_.Linq.MethodCallParsers.Add(new LinqEqualsExt());

                    });

                }
                return Context;

            }
            catch(Exception ex)
            {
                log.Error(ex);
                return null;
            }
        }

````

When error happened i tried following things:
1. Export main tables data in CSV
2. Drop Existing DB
3. Re-compile my program
3. Re-run my program
4. It re-created DB anew (checked generated functions but they were wrong as noted in first comment of issue)
5. I imported data back from CSV file
6. Re-run software again, so i can work with correct data, but errors still persisted
7. Rolled back to v3, and all worked

Sorry, maybe i dont really understand what means migrate from v3 to v4.
And in case of v4, how to re-create DB anew correctly.
By the way, i'm using **DocumentStore** feature only.

Thanks in advance.

**Comment by tonykaralis** [comment]
I have the same issue as well, upsert functions use new constraint names but the constraint names themselves haven't changed.

**Comment by oskardudycz** [comment]
@tonykaralis @amferguson, would you be so kind as to provide:
- document store configurations (old and new) - at least with the document type that's failing,
- create a statement for the failing table?

That'd help us to tackle that case. Thank you in advance!

**Comment by tonykaralis** [comment]
@amferguson the Document store config is usually just the c# code where you register all the documents etc with marten. If you use something like pgAdmin to administer your db then you can just right click on the table and select CreateScript which should show you the script used to create the table. I would assume that should suffice.

**Comment by amferguson** [comment]
Oh, gotcha. Related to a conversation @jeremydmiller and I had on gitter (and #1931), I was also making some changes to the duplicated columns, so perhaps too much all at once?

Old config:
```
var serializer = new JsonNetSerializer();
serializer.Customize(config =>
{
   config.SerializationBinder = new CustomJsonSerializationBinder(); //Moved a type at some point, so this overrides BindToType to tell it to check both assemblies
});
var store = DocumentStore.For(config =>
    {
        config.Connection(connectionString);
        config.AutoCreateSchemaObjects = AutoCreate.None;
        config.Schema.Include<ApplicationRegistry>();
        config.Serializer(serializer); 
    });
```

Old ApplicationRegistry
```
For<Application>()
    Duplicate(a => a.ApplicationNumber)
    Duplicate(a => a.VinOrSectionNumbers)
    Duplicate(a => a.ApplicationCategory)
    Duplicate(a => a.ApplicationType)
    Duplicate(a => a.TrustedPartyId)
    Duplicate(a => a.LastUpdatedDate)
    Duplicate(a => a.Status.StatusType); //source of my issue in #1931 


    this.For<Application>().Index(a => a.Owner.FullPartyName);
    this.For<Application>().Index(a => a.IsCurrentTitle);
    this.For<Application>().Index(a => a.IssuedDate); //Apparently this never actually worked based on the docs?
```

New Config
```
var store = DocumentStore.For(config =>
    {
        config.Connection(connectionString);
        config.Schema.Include<ApplicationRegistry>();
        config.Serializer(serializer); //same serializer as above

        //Needed to maintain compatibility for 2.x => 4.x
        config.Advanced.DuplicatedFieldEnumStorage = EnumStorage.AsString;
        config.Advanced.DuplicatedFieldUseTimestampWithoutTimeZoneForDateTime = false;
    });
```

New ApplicationRegistry
```
this.For<Application>()
      .Duplicate(a => a.LastUpdatedDate);

this.For<Application>().Index(a => a.ApplicationNumber,     indexConfig => { indexConfig.IsConcurrent = true; } );
this.For<Application>().Index(a => a.VinOrSectionNumbers,   indexConfig => { indexConfig.IsConcurrent = true; } );
this.For<Application>().Index(a => a.ApplicationType,       indexConfig => { indexConfig.IsConcurrent = true; } );
this.For<Application>().Index(a => a.ApplicationCategory,   indexConfig => { indexConfig.IsConcurrent = true; } );
this.For<Application>().Index(a => a.TrustedPartyId,        indexConfig => { indexConfig.IsConcurrent = true; } );
this.For<Application>().Index(a => a.Owner.FullPartyName,   indexConfig => { indexConfig.IsConcurrent = true; } );
this.For<Application>().Index(a => a.Status.StatusType,     indexConfig => { indexConfig.IsConcurrent = true; } );
this.For<Application>().Index(a => a.IsCurrentTitle,        indexConfig => { indexConfig.IsConcurrent = true; } );
this.For<Application>().Index(a => a.IssuedDate,            indexConfig => { indexConfig.IsConcurrent = true; } ); 
```

Exception:
```
Exception in UpdateStatus in $....
Marten.Exceptions.MartenCommandException: Marten Command Failure:$
select public.mt_upsert_application(:p0, :p1, :p2, :p3, :p4, :p5);$
$
42704: constraint "pkey_mt_doc_application_id" for table "mt_doc_application" does not exist
 ---> Npgsql.PostgresException (0x80004005): 42704: constraint "pkey_mt_doc_application_id" for table "mt_doc_application" does not exist
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Marten.Services.ManagedConnection.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
  Exception data:
    Severity: ERROR
    SqlState: 42704
    MessageText: constraint "pkey_mt_doc_application_id" for table "mt_doc_application" does not exist
    Where: SQL statement "INSERT INTO public.mt_doc_application ("last_updated_date", "data", "mt_dotnet_type", "id", "mt_doc_type", "mt_version", mt_last_modified) VALUES (arg_last_updated_date, doc, docDotNetType, docId, docType, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pkey_mt_doc_application_id
  DO UPDATE SET "last_updated_date" = arg_last_updated_date, "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_doc_type" = docType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp()"
PL/pgSQL function mt_upsert_application(timestamp with time zone,jsonb,character varying,bigint,character varying,uuid) line 5 at SQL statement
    File: pg_constraint.c
    Line: 810
    Routine: get_relation_constraint_oid
   --- End of inner exception stack trace ---
```
[existing_table.txt](https://github.com/JasperFx/marten/files/7375315/existing_table.txt)
