### ISSUE TITLE
Problems with upgrade to marten v4.

### ISSUE THREAD

**Issue by DariuszFirek** [JasperFx/marten#1876]
I couldn't find any migration guide for switching from v3 to v4. Is there any?

A little bit of backstory.  
Our team is strugling with update to Marten v4. And we have to do it as our fairly big production system is forcing us to move to new version of npgsql, which is not supported in marten v3.x. We have some dependencies which force us to move to new npgsql (like using newest EF at the same time).

Couple of problems we encountered:

1. We have dozens of projections, we can handle changes in declaration etc. But removal of overloads from ViewProjection<T, Guid> allowing to search for items to apply like:
`public ViewProjection<TView, TId> ProjectEvent<TEvent>(Func<IDocumentSession, TEvent, List<TId>> viewIdsSelector, Action<IDocumentSession, TView, TEvent> handler, bool onlyUpdate = false)` is removing a feature that was used by us heavly.
Now its only one `Identity<TEvent>()`, or `Identities<TEvent>()` but we lost ability to query to find where to apply. 
I saw some newer RCs have some custom grouping - but it's not explained anywhere how to use it properly. Or how to replace old projections with something working in v4.
It looks like it was tackled with https://github.com/JasperFx/marten/issues/1784

Also DeleteEvent<> is gone from ViewProjection.

We battled that with custom base `ViewProjectionExtended` class derived from `EventProjection` with added all missing overloads like before but it's far from optimal.

2. Some of linq extensions (like `.AnyTenant()`) now throw exceptions if passed collection is not MartenQueryable, which makes writing tests/mocking painfull. 

3. We managed to run our app with new marten (after a lot of custom code to handle these projections) but it died after few hours because of 
```Npgsql.NpgsqlException (0x80004005): The connection pool has been exhausted, either raise MaxPoolSize (currently 100) or Timeout (currently 15 seconds) ---> System.TimeoutException: The operation has timed out.```
We haven't changed anything regarding connection handling - should we? It was running without any issues on previous version of marten.

4. I don't really know if that's the case, but how much was the migration/building schema mechanism changed? I didn't really had a chance to verify this behaviour, but it looks like before the first usage of DocumentStore was creating the whole schema. 
Now it's behaving like tables are created during first usage of particular document/table. This is good, but when we run some tests there are numerous threads trying to create the same tables, which causes random test to fail, because of some concurency issues. 
This looks like:
```Cyclic dependency between documents detected. The types are: [someClass], [otherClass]
   at Marten.Storage.StorageFeatures.Build(Type type, StoreOptions options)
   at Marten.Storage.StorageFeatures.MappingFor(Type documentType)
   at Marten.Storage.StorageFeatures.FindFeature(Type featureType)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType, CancellationToken token)
   at Marten.Storage.Tenant.EnsureStorageExists(Type featureType)
   at Marten.Internal.StorageCheckingProviderGraph.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFor(Type documentType)
   at Marten.Linq.Parsing.LinqHandlerBuilder..ctor(MartenLinqQueryProvider provider, IMartenSession session, Expression expression, ResultOperatorBase additionalOperator, Boolean forCompiled)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token, ResultOperatorBase op)
   at Marten.Linq.MartenLinqQueryable`1.AnyAsync(CancellationToken token)
   at Marten.QueryableExtensions.AnyAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Marten.QueryableExtensions.AnyAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken token)```
And happens at random occassions.

**Comment by DariuszFirek** [comment]
We dropped the idea of update unless we have final v4 - a lot of thing moving.

* You're right - DeleteEvent() is there, I messed that up with that EventProjections stuff we tried to use
* We didn't use Async deamon yet, all projections were inline (at least for now), mainly because in the past async deamon didn't handle well multitenancy. We'll have another try with final version of marten, maybe there was something wrong in one of previous betas.
* I agree that it should be tested via intergration test, but someone in our team probably wanted to test some service doing queries via unit test, at least constructing the query probably. We sometimes try to do it, as our project is really large, and integration tests are taking a lot of time (it's like 20+ minutes for whole pipeline)
* We can probably handle schema creation by forcing creation of all of the tables at one thread, but it would be nice to handle that case better, because now it throws some 'CircularDependency' exceptions.

As for use case of old projections. the main problem are some handlers, where we use overloads with IDocumentSession to find ids of items to have events applied.
In very simplified version (without asyncs etc) they look like this:

```
public class ChildProjection : ViewProjection<Child, Guid>
{
    public ChildProjection()
    {
        ProjectEventAsynt<ParentUpdated>((documentSession, @event) => GetChildrenIds(documentSession, @event), Apply);
    }

    private List<Guid> GetChildrenIds(IDocumentSession documentSession, ParentUpdated @event)
    {
        return documentSession.Query<Child>().Where(x => x.ParentId == @event.AggregateId).Select(x => x.Id).ToList();
    }

    public void Apply(Child item, ParentUpdated @event)
    {
        item.ParentName = @event.Name;
    }
}
```
So we would like to migrate from using this overload with `GetChildrenIds` to something using the new way. Should that be this grouping, FanOut? I don't really know which is the proper, most supported way. Also since these projections are inline (data consistency is crucial as this is finance system) it would be great to make it as fast as possible.
