### ISSUE TITLE
Generated constructor not found in v4

### ISSUE THREAD

**Issue by willhausman** [JasperFx/marten#1883]
I am trying to event source my aggregates, but keep getting this exception, using Marten v4.0.0-rc.5:

```
    System.MissingMethodException : Constructor on type 'Marten.Generated.AggregateProjection_Domain_Model_Aggregate_InlineHandler' not found.
    Stack Trace:
       at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Marten.Events.Aggregation.AggregateProjection`1.BuildRuntime(DocumentStore store)
   at Marten.Events.Aggregation.AggregateProjection`1.Build(DocumentStore store)
   at Marten.Events.Projections.ProjectionOptions.<>c__DisplayClass11_0.<BuildInlineProjections>b__1(ProjectionSource x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Marten.Events.Projections.ProjectionOptions.BuildInlineProjections(DocumentStore store)
   at Marten.Events.EventGraph.<>c__DisplayClass14_0.<.ctor>b__2()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Marten.Events.EventGraph.ProcessEventsAsync(DocumentSessionBase session, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
```

I have existing conventions for other aggregates that I was trying to stick to.  Typically, my aggregates look something like this:

```csharp
public class Party : AggregateBase
{
  public string Key { get; protected init; } = Guid.NewGuid().ToString();
  public string Name { get; protected set; }

  public Party(string name) { Name = name; }
  protected Party(string key, string name) { Key = key; Name = name; } // deserialization ctor

  public void ChangeName(string newName) {
    RaiseEvent(new NameChanged(Key, Name, newName));
    Name = newName;
  }
}
```

Where `AggregateBase` provides a list of domain events and `RaiseEvent()` for managing those events within the class, a string `Key`, and equality overrides.  `RaiseEvent()` just appends events to the list until changes are committed.

Changing that to use the v4 event store looks like this:

```csharp
public class Party : AggregateBase
{
  public string Key { get; protected set; }
  public string Name { get; protected set; }

  public Party(string name) {
    var @event = new PartyCreated(Guid.NewGuid().ToString(), name);
    Apply(@event);
    RaiseEvent(@event); 
  }
  protected Party() { }

  public void ChangeName(string newName) {
    var @event = new NameChanged(Key, Name, newName);
    Apply(@event);
    RaiseEvent(@event);
  }
  
  private void Apply(PartyCreated @event) {
    Key = @event.Key;
    Name = @event.Name;
  }

  private void Apply(NameChanged @event) {
    Name = @event.NewName;
  }
}
```

When configuring the event store, I have specified the following options:
```csharp
options.Events.StreamIdentity = StreamIdentity.AsString;
options.Events.TenancyStyle = TenancyStyle.Conjoined;
options.Events.DatabaseSchemaName = "parties";
options.Events.MetadataConfig.CausationIdEnabled = true;
options.Events.MetadataConfig.CorrelationIdEnabled = true;

options.Events.AddEventType(typeof(PartyCreated));
options.Events.AddEventType(typeof(NameChanged));

options.Projections.SelfAggregate<Party>().Identity(p => p.Key);
```

I run into the problem when trying to setup my test. I never get past `SaveChangesAsync()`.

```csharp
public async Task should_return_aggregate() {
  using var session = OpenDocumentSession();
  var party = new Party("name");
  session.Events.StartStream<Party>(party.Key, party.Events);
  await session.SaveChangesAsync().ConfigureAwait(false);

  var result = await session.Events.AggregateStreamAsync<Party>(party.Key).ConfigureAwait(false);
  
  result.Should().NotBeNull();
}
```

Any help would be greatly appreciated.

**Comment by oskardudycz** [comment]
@willhausman, the issue is with the `public Party(string name)` constructor. Currently, Marten will:
- check if there is a single parameter constructor,
- if it finds it, then assumes that it should be used during the aggregation - to be used with the first event in the stream,
- if it does not contain the type that should be an event, then it will fail.

The same logic goes for the static method with `Create` in a name. Currently, you can ignore that check using the `MartenIgnore` attribute. We probably need to make validation more explicit or some settings to enable/disable it. I'll try to add a test for that later on.

**Comment by willhausman** [comment]
@oskardudycz I see how that would affect the sample code I provided, although I still could not provide my entire codebase. My actual class does not have a constructor with a single parameter like that.  I have 4 arguments, two primitives, an enum, and a complex type to be stored in an enumerable.

**Comment by oskardudycz** [comment]
@willhausman, could you provide an example closer to the real class that you're facing the issue? As you see, many factors can impact this issue. We might not be able to reproduce/fix that without a good example.
