### ISSUE TITLE
Marten v4.2.0 PendingChanges incorrect when doing Insert and Update in the same transaction

### ISSUE THREAD

**Issue by mronnblom-cint** [JasperFx/marten#1994]
We're trying to upgrade from Marten 3.13.5 to 4.2.0. If we try to do this (simplified):
```
_documentSession.Insert(project);
// Update something on project
_documentSession.Update(project);
await _documentSession.SaveChangesAsync();
```
With v4 _documentSession.PendingChanges contains a UpdateProjectOperation, whereas in v3 there will be an InsertDocument operation. With v4 the commit fails with this exception (which is rather cryptic):
```
System.InvalidCastException
  HResult=0x80004002
  Message=Column 'mt_update_project' is null.
  Source=Npgsql
  StackTrace:
   at Npgsql.ThrowHelper.ThrowInvalidCastException_NoValue(FieldDescription field)
   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
   at Npgsql.NpgsqlDataReader.GetFieldValueAsync[T](Int32 ordinal, CancellationToken cancellationToken)
   at Marten.Internal.Operations.StorageOperation`2.<postprocessConcurrencyAsync>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Marten.Generated.UpdateProjectOperation.<PostprocessAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Marten.Internal.UpdateBatch.<ApplyCallbacksAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Marten.Internal.UpdateBatch.<ApplyChangesAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Marten.Internal.UpdateBatch.<ApplyChangesAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Marten.Internal.Sessions.DocumentSessionBase.<ExecuteBatchAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Marten.Internal.Sessions.DocumentSessionBase.<ExecuteBatchAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Marten.Internal.Sessions.DocumentSessionBase.<SaveChangesAsync>d__54.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MyProject.Infrastructure.MartenUnitOfWork.<CommitAsync>d__3.MoveNext() in C:\source\Foo\src\MyProject.Infrastructure\MartenUnitOfWork.cs:line 33
```

Let me know if you need more info/configuration.

**Comment by jeremydmiller** [comment]
I'm taking a look right now.

**Comment by jeremydmiller** [comment]
I've got a "working" reproduction in code at least. **But**, you shouldn't be issuing an INSERT then an UPDATE on the same exact document in the exact same document session. That's not gonna work w/ the optimistic concurrency turned on. Were you depending on the `PendingChanges()` here to make that work somewhere else in your code?

**Comment by jeremydmiller** [comment]
@mronnblom-cint To be honest, I'm not sure that I'm inclined to make many changes here because this is a really unusual usage. My advice is to use the PendingChanges above to check if the user is already being updated. I'm making one very small change to make the concurrency check fail cleanly, which I feel like is the right approach here.

**Comment by mronnblom-cint** [comment]
@jeremydmiller I disagree it's "really unusual". Lets take a simple example for a "User" object:
1. You have one method that creates a new object, `CreateUser`. This method does `documentSession.Insert`.
2. You have another method, `UpdateUserEmailFromFooSystem`. This method fetches the users email from a remote source and does  `documentSession.Update`.
3. You want to run `UpdateUserEmailFromFooSystem` both for a new user and sometimes for an existing user when the email has changed in FooSystem, and naturally you don't want to duplicate that code.

Maybe a stupid example abstraction-wise, but hopefully you get the idea. I.e. there are code path(s) you want to reuse both for new users and for existing ones, and those code paths should be agnostic to that fact.

I just now tested to replace `Insert+Update` with `Store+Store`, and that works. So Marten *does* allow multiple `Store` commands within the same session, but not `Insert+Update`. That is poor design and inconsistent IMO. Not a big deal for me though, since using `Store` works, but you loose some control then.

**Comment by jeremydmiller** [comment]
@mronnblom-cint  If you wanna do the pull request for your specific problem here to latch `Update()` so that it doesn't place another operation in the exact same document session and transaction for the same document similar to `Store()`, we'll happily take that.
