### ISSUE TITLE
Intermittent `CommandText property has not been initialized` error during projection updates

### ISSUE THREAD

**Issue by kluhman** [JasperFx/marten#1995]
Running rebuilds of a projection, I intermittently get this error. Restarting the daemon generally resolves the issue, but it does make it difficult to run a complete rebuild without restarting in the middle

```
System.InvalidOperationException: CommandText property has not been initialized
   at Npgsql.NpgsqlCommand.ProcessRawQuery(Boolean standardConformingStrings, Boolean deriveParameters)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Marten.Services.ManagedConnection.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Baseline.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(NpgsqlCommand command, Exception exception)
   at Marten.Services.ManagedConnection.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Services.ManagedConnection.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
   at Marten.Events.Daemon.ProjectionUpdateBatch.Page.ApplyChangesAsync(IList`1 exceptions, IMartenSession session, CancellationToken token)
   at Marten.Events.Daemon.ProjectionUpdateBatch.Marten.Internal.IUpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
   at Marten.Events.Daemon.ShardAgent.ExecuteBatch(ProjectionUpdateBatch batch)
   at Marten.Events.Daemon.ShardAgent.ExecuteBatch(ProjectionUpdateBatch batch)
   at Marten.Events.Daemon.ShardAgent.<>c__DisplayClass32_0.<<processRange>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters)
```

**Comment by jeremydmiller** [comment]
Closed by #1996
