### ISSUE TITLE
Blazor app - deadlock on IQuerySession.Query<T>()

### ISSUE THREAD

**Issue by lukblazewicz** [JasperFx/marten#2030]
Hey,

We're using Marten v4.3.0, trying to retrieve data using the simplest query possible (without filtering) `IQuerySession.Query<T>()`. The method never returns - until it throws a timeout exception as follows:
```
System.TimeoutException: The operation has timed out.
at Marten.Util.TimedLock.Lock(TimeSpan timeout)
at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature, CancellationToken token)
at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType, CancellationToken token)
at Marten.Storage.Tenant.EnsureStorageExists(Type featureType)
at Marten.Internal.StorageCheckingProviderGraph.StorageFor[T]()
at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
at Marten.Internal.Sessions.QuerySession.StorageFinder`1.Find(QuerySession session)
at Marten.Internal.Sessions.QuerySession.StorageFor(Type documentType)
at Marten.Linq.Parsing.LinqHandlerBuilder..ctor(MartenLinqQueryProvider provider, IMartenSession session, Expression expression, ResultOperatorBase additionalOperator, Boolean forCompiled)
at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token)
at Marten.Linq.MartenLinqQueryable`1.ToListAsync[TResult](CancellationToken token)
at Marten.QueryableExtensions.ToListAsync[T](IQueryable`1 queryable, CancellationToken token)
...  [our Blazor application call stack]
at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Our assumption is that there is a sync over async issue inside Tenant.cs: https://github.com/JasperFx/marten/blob/f7e9d583cb76a1b893bd82f9b0eb2e759f09ccb4/src/Marten/Storage/Tenant.cs#L77
...where GetAwaiter().GetResult() is blocking the underlying asynchronous calls.

We're currently exploring some hacky workarounds (such as setting `AutoCreateSchemaObjects` to `None`) but we feel the issue should be addressed at the library level.  

Thanks a lot.

**Comment by jeremydmiller** [comment]
@lukblazewicz Right now, I don't think anybody from the Marten team is familiar with Blazor. applying all database changes upfront, then setting AutoCreate to None is what I would have recommended for production usage regardless.

**Comment by lukblazewicz** [comment]
@jeremydmiller 

Thanks for the answer - good to hear that we're hacking only a little (if the workaround is actually a recommended production setting). 

Anyway, let's keep the issue open please, so that the actual bug can be addressed at some point.

**Comment by jeremydmiller** [comment]
@lukblazewicz ,

So about that: "Anyway, let's keep the issue open please, so that the actual bug can be addressed at some point."

Would you be willing to help? As I was trying to allude to earlier, we don't have any Blazor folks working on Marten right now if this turns out to be an Npgsql + Blazor specific issue.

**Comment by jeremydmiller** [comment]
At a minimum though, we could opt to use `EnsureStorageExistsAsync()` wherever possible going forward. That might alleviate some of this. But I absolutely recommend running AutoCreate.None at production time. I'm hopefully working up a way to make the "CreateOrUpdate & dynamic code gen at dev time" while being "AutoCreate.None & pre-built code" at production time as part of Marten 5.

**Comment by lukblazewicz** [comment]
When it comes to giving a hand with this issue, I don't feel confident enough to interfere with Marten's internals at such a low level. I'm happy to help with reproduction of the issue and testing potential solutions (or any other assistance we could provide), but the vision of rewriting Tenant's sync/async specificities on our own seems too ambitious at the moment.
