### ISSUE TITLE
OrderBy dynamic property Missing in v4

### ISSUE THREAD

**Issue by jonathonc** [JasperFx/marten#2035]
This was working fine in v3, but not after we upgraded to 4.3.1

Example of the code that causes the issue
```
var records = await session.Query<Audit>()
    .OrderBy($"{request.SortProp} {request.SortOrder}")
    .ToPagedListAsync(request.PageNumber, request.PageSize);
```

This is the error we get

```
System.NotSupportedException: Specified method is not supported.
   at Marten.Linq.MartenLinqQueryProvider.CreateQuery(Expression expression)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.InternalOrderBy(IQueryable source, ParsingConfig config, String ordering, IComparer comparer, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.OrderBy(IQueryable source, ParsingConfig config, String ordering, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.OrderBy[TSource](IQueryable`1 source, ParsingConfig config, String ordering, Object[] args)
```

**Comment by mysticmind** [comment]
Looks like the same issue reported in https://github.com/JasperFx/marten/issues/1808

**Comment by jonathonc** [comment]
@mysticmind This was working in v3 though? 

Can you help point me in the right direction to how this was implemented in v3? Happy to try and work on a PR

**Comment by mysticmind** [comment]
@jonathonc v4 had a large revamp on may things. Let me check and get back to you later today on this.

**Comment by apereiratl** [comment]
There's an easier way to do this. 

```
public static IQueryable<T> OrderBy<T>(this IQueryable<T> query, string sortBy, SortDirection sortDirection)
        {
            return sortDirection == SortDirection.Ascending ? query.OrderBy(new[] { Tuple.Create(sortBy, SortDirection.Ascending) }) : query.OrderBy(new[] { Tuple.Create(sortBy, SortDirection.Descending) });
        }

        public static IQueryable<T> OrderBy<T>(this IQueryable<T> query, IEnumerable<Tuple<string, SortDirection>> order)
        {
            var expr = ApplyOrderBy(typeof(T), query.Expression, order);
            return query.Provider.CreateQuery<T>(expr);
        }

        static Expression MakePropPath(Expression objExpression, string path)
        {
            return path.Split('.').Aggregate(objExpression, Expression.PropertyOrField);
        }

        static Expression ApplyOrderBy(Type entityType, Expression queryExpr, IEnumerable<Tuple<string, SortDirection>> order)
        {
            var param = Expression.Parameter(entityType, "e");
            var isFirst = true;
            foreach (var tuple in order)
            {
                var lambda = Expression.Lambda(MakePropPath(param, tuple.Item1), param);
                var methodName =
                    isFirst ? tuple.Item2 == SortDirection.Descending ? nameof(Queryable.OrderByDescending) : nameof(Queryable.OrderBy)
                    : tuple.Item2 == SortDirection.Descending ? nameof(Queryable.ThenByDescending) : nameof(Queryable.ThenBy);

                queryExpr = Expression.Call(typeof(Queryable), methodName, new[] { entityType, lambda.Body.Type }, queryExpr, lambda);
                isFirst = false;
            }

            return queryExpr;
        }
```

**Comment by jeremydmiller** [comment]
@jonathonc It was a very late addition to v3 that happened when we were neck deep in v4 where the Linq internals changed a lot. I *think* there's some PR going to add that to v4.
