### ISSUE TITLE
DefaultTenantUsageDisabledException when async daemon processes async projections

### ISSUE THREAD

**Issue by elexisvenator** [JasperFx/marten#2073]
.Net 6.0.1
Marten 5.0.0-alpha.5

I have created an async projection and I noticed that when the projection is persisted (aka not a live projection) then the async daemon fails to create it.  As per my config below, I have conjoined multitenancy enabled and default tenant id disabled. The projection works fine when the default tenant id is enabled.
There are also no events in the system currently - just an empty database.

Config:
```c#
builder.Services.AddMarten(options =>
{
    options.Connection(
        "Server=localhost;Port=5432;Database=marten;User Id=postgres;Password=postgres;");

    // Multi tenancy
    options.Policies.AllDocumentsAreMultiTenanted();
    options.Advanced.DefaultTenantUsageEnabled = false;
    options.Events.TenancyStyle = TenancyStyle.Conjoined;

    options.Events.StreamIdentity = StreamIdentity.AsString;

    // Add projections
    options.Projections.Add<DocumentProjection>(ProjectionLifecycle.Async);
}).AddAsyncDaemon(DaemonMode.Solo);
```

Projection and events:
```c#
// events
public record CreateDoc(string DocumentId, string Owner, string Content);
public record ChangeDocOwner(string DocumentId, string OldOwner, string NewOwner);
public record UpdateDoc(string DocumentId, string Content);

// projection
public record Document([property: Identity] string DocumentId, string Owner, string Content);

public class DocumentProjection : AggregateProjection<Document>
{
    public static DocumentProjection Instance { get; } = new();

    public Document Create(CreateDoc @event)
    {
        return new Document(DocumentId: @event.DocumentId, Owner: @event.Owner, Content: @event.Content);
    }

    public Document Apply(UpdateDoc @event, Document current)
    {
        return current with { Content = @event.Content };
    }

    public Document Apply(ChangeDocOwner @event, Document current)
    {
        return current with { Owner = @event.NewOwner };
    }
}
```

Stack trace: 

```
Marten.Events.Daemon.AsyncProjectionHostedService: Information: Starting projection agent for 'Identity: Document:All'
Marten.Events.Daemon.AsyncProjectionHostedService: Error: Error when trying to start projection shard 'Document:All'

Marten.Events.Daemon.ShardStartException: Failure while trying to stop 'Document:All'
 ---> Marten.Exceptions.DefaultTenantUsageDisabledException: Default tenant *DEFAULT* usage is disabled. Ensure to create a session by explicitly passing a non-default tenant in the method arg or SessionOptions.
   at Marten.Services.SessionOptions.Initialize(DocumentStore store, CommandRunnerMode mode)
   at Marten.DocumentStore.QuerySession(String tenantId)
   at Marten.DocumentStore.QuerySession()
   at Marten.Events.Daemon.EventFetcher..ctor(IDocumentStore store, ISqlFragment[] filters)
   at Marten.Events.Daemon.ShardAgent.Start(ProjectionDaemon daemon)
   at Marten.Events.Daemon.ProjectionDaemon.<>c__DisplayClass21_0.<<StartShard>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Marten.Events.Daemon.ProjectionDaemon.<>c__DisplayClass21_0.<<StartShard>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters)
Marten.Events.Daemon.AsyncProjectionHostedService: Information: Starting projection agent for 'Identity: Document:All'
Marten.Events.Daemon.AsyncProjectionHostedService: Error: Error when trying to start projection shard 'Document:All'

Marten.Events.Daemon.ShardStartException: Failure while trying to stop 'Document:All'
 ---> Marten.Exceptions.DefaultTenantUsageDisabledException: Default tenant *DEFAULT* usage is disabled. Ensure to create a session by explicitly passing a non-default tenant in the method arg or SessionOptions.
   at Marten.Services.SessionOptions.Initialize(DocumentStore store, CommandRunnerMode mode)
   at Marten.DocumentStore.QuerySession(String tenantId)
   at Marten.DocumentStore.QuerySession()
   at Marten.Events.Daemon.EventFetcher..ctor(IDocumentStore store, ISqlFragment[] filters)
   at Marten.Events.Daemon.ShardAgent.Start(ProjectionDaemon daemon)
   at Marten.Events.Daemon.ProjectionDaemon.<>c__DisplayClass21_0.<<StartShard>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Marten.Events.Daemon.ProjectionDaemon.<>c__DisplayClass21_0.<<StartShard>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters)
Marten.Events.Daemon.AsyncProjectionHostedService: Information: Starting projection agent for 'Identity: Document:All'
Marten.Events.Daemon.AsyncProjectionHostedService: Error: Error when trying to start projection shard 'Document:All'

Marten.Events.Daemon.ShardStartException: Failure while trying to stop 'Document:All'
 ---> Marten.Exceptions.DefaultTenantUsageDisabledException: Default tenant *DEFAULT* usage is disabled. Ensure to create a session by explicitly passing a non-default tenant in the method arg or SessionOptions.
   at Marten.Services.SessionOptions.Initialize(DocumentStore store, CommandRunnerMode mode)
   at Marten.DocumentStore.QuerySession(String tenantId)
   at Marten.DocumentStore.QuerySession()
   at Marten.Events.Daemon.EventFetcher..ctor(IDocumentStore store, ISqlFragment[] filters)
   at Marten.Events.Daemon.ShardAgent.Start(ProjectionDaemon daemon)
   at Marten.Events.Daemon.ProjectionDaemon.<>c__DisplayClass21_0.<<StartShard>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Marten.Events.Daemon.ProjectionDaemon.<>c__DisplayClass21_0.<<StartShard>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters)
Marten.Events.Daemon.AsyncProjectionHostedService: Information: Starting projection agent for 'Identity: Document:All'
Marten.Events.Daemon.AsyncProjectionHostedService: Error: Error when trying to start projection shard 'Document:All'

Marten.Events.Daemon.ShardStartException: Failure while trying to stop 'Document:All'
 ---> Marten.Exceptions.DefaultTenantUsageDisabledException: Default tenant *DEFAULT* usage is disabled. Ensure to create a session by explicitly passing a non-default tenant in the method arg or SessionOptions.
   at Marten.Services.SessionOptions.Initialize(DocumentStore store, CommandRunnerMode mode)
   at Marten.DocumentStore.QuerySession(String tenantId)
   at Marten.DocumentStore.QuerySession()
   at Marten.Events.Daemon.EventFetcher..ctor(IDocumentStore store, ISqlFragment[] filters)
   at Marten.Events.Daemon.ShardAgent.Start(ProjectionDaemon daemon)
   at Marten.Events.Daemon.ProjectionDaemon.<>c__DisplayClass21_0.<<StartShard>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at Marten.Events.Daemon.ProjectionDaemon.<>c__DisplayClass21_0.<<StartShard>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters)
```

**Comment by jeremydmiller** [comment]
@elexisvenator Are there any events in the mt_events table where the tenant_id is "*Default*"?
