### ISSUE TITLE
AppendExclusive example code from documentation does not work

### ISSUE THREAD

**Issue by vmartos** [JasperFx/marten#2143]
Hi!

The code sample from the following page https://martendb.io/events/appending.html#serialized-access-to-the-stream (AppendExclusive) does not seem to work, when saving changes it throws the following exception:

Marten.Exceptions.EventStreamUnexpectedMaxEventIdException
  HResult=0x80131500
  Message=Unexpected starting version number for event stream 'f09e05a1-df8f-4b83-a343-1a3e760a4093', expected 3 but was 1
  Source=Marten
  StackTrace:
   at Marten.Events.StreamAction.PrepareEvents(Int64 currentVersion, EventGraph graph, Queue`1 sequences, IMartenSession session)
   at Marten.Events.EventGraph.<ProcessEventsAsync>d__87.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Marten.Internal.Sessions.DocumentSessionBase.<SaveChangesAsync>d__54.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TestMartenAppendExclusive.Program.<Main>d__0.MoveNext() in C:\Users\v.martos\source\repos\TestMartenAppendExclusive\TestMartenAppendExclusive\Program.cs:line 46

the code sample is the following:

```
using Marten;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Weasel.Postgresql;

namespace TestMartenAppendExclusive
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();
            var databaseSchema = "test_marten";

            var martenConfiguration = serviceCollection.AddMarten(options =>
            {
                options.Connection("Username=admin;Password=changeit;Host=localhost;Port=5432");
                options.Events.DatabaseSchemaName = databaseSchema;
                options.DatabaseSchemaName = databaseSchema;
                options.AutoCreateSchemaObjects = AutoCreate.All;

                options.Policies.AllDocumentsAreMultiTenanted();
            });

            using var documentSession = martenConfiguration.InitializeStore();
            using var session = documentSession.OpenSession();
            
            var streamId = Guid.NewGuid();

            session.Events.StartStream(streamId, new EventForTest(Guid.NewGuid()));

            await session.SaveChangesAsync();

            await session.Events.AppendExclusive(streamId);

            var events = new List<EventForTest> { new(Guid.NewGuid()), new(Guid.NewGuid()) };

            // The next call can just be Append()
            session.Events.Append(streamId, events);

            // This will commit the unit of work and release the
            // lock on the event stream
            await session.SaveChangesAsync();
        }
    }

    public record EventForTest(Guid Id);
}

```

Version of Marten: 4.3.1

I expect this to do a database lock first on the stream itself, and then be able to append events, and when SaveChangesAsync() is called it should Save in the store the two events and remove the lock. 

Is there a bug? or is the AppendExclusive never intended to be called without events? For my use case it is useful to first do a lock in the database, then load a projection to know the current state before appending new events.

**Comment by vmartos** [comment]
@jeremydmiller Hi, thanks for looking at it. 

I already created a PR with the failed test here: https://github.com/JasperFx/marten/pull/2144, I marked it as a draft, let me know if you need anything else.
