### ISSUE TITLE
BulkInsert throws NullReferenceException when document has a nested duplicate index of type Int

### ISSUE THREAD

**Issue by darraghjones** [JasperFx/marten#2160]
The unit test below throws the following exception:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ValidateAndGetLengthCustom[TAny](TAny value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter`1.ValidateAndGetLength()
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlParameter param, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlDbType npgsqlDbType)
   at Marten.Generated.DocumentStorage.PersonBulkLoader389020440.LoadRow(NpgsqlBinaryImporter writer, Person document, Tenant tenant, ISerializer serializer)
   at Marten.Internal.CodeGeneration.BulkLoader`2.LoadIntoTempTable(Tenant tenant, ISerializer serializer, NpgsqlConnection conn, IEnumerable`1 documents)
   at Marten.Storage.BulkInsertion.loadDocuments[T](IEnumerable`1 documents, IBulkLoader`1 loader, BulkInsertMode mode, NpgsqlConnection conn)
   at Marten.Storage.BulkInsertion.bulkInsertDocuments[T](IReadOnlyCollection`1 documents, Int32 batchSize, NpgsqlConnection conn, BulkInsertMode mode)
   at Marten.Storage.BulkInsertion.BulkInsert[T](IReadOnlyCollection`1 documents, BulkInsertMode mode, Int32 batchSize)
   at Marten.DocumentStore.BulkInsert[T](IReadOnlyCollection`1 documents, BulkInsertMode mode, Int32 batchSize)
   at MartenBulk.Tests.BulkInsertTest() in C:\Users\Darragh.Jones\temp\MartenBulk\MartenBulk\UnitTest1.cs:line 31
```

Note that this only seems to happen when the duplicate index is nested, and when it's a number.

```
using System;
using Marten;
using Microsoft.Extensions.DependencyInjection;
using NUnit.Framework;
using Weasel.Core;

namespace MartenBulk;

public class Tests
{
    private IDocumentStore store;

    [SetUp]
    public void Setup()
    {
        var serviceCollection = new ServiceCollection();
        store = serviceCollection.AddMarten(options =>
        {
            options.Connection("host=localhost;database=test;username=postgres;password=password;");
            options.CreateDatabasesForTenants(c => c.ForTenant());
            options.AutoCreateSchemaObjects = AutoCreate.All;
            options.Schema.For<Person>().Duplicate(x => x.HomeAddress.HouseNumber); // this causes a null-ref exception at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ValidateAndGetLengthCustom
            //options.Schema.For<Person>().Duplicate(x => x.HomeAddress.StreetName); // this seems to work fine
        }).InitializeStore();
    }

    [Test]
    public void BulkInsertTest()
    {
        var people = new[] { new Person(Guid.NewGuid(), new Address(string.Empty, 0)) };
        store.BulkInsert(people, BulkInsertMode.OverwriteExisting);
    }
}

public record Person(Guid Id, Address HomeAddress);
public record Address(string StreetName, int HouseNumber);
```

**Comment by darraghjones** [comment]
I actually get the same error if I use a nullable int without nesting... i.e.
```
...
    options.Schema.For<Address>().Duplicate(x => x.Altitude);
...

    [Test]
    public void BulkInsertAddress()
    {
        var docs = new[] { new Address(Guid.NewGuid(),  string.Empty, 0, 5) };
        store.BulkInsert(docs, BulkInsertMode.OverwriteExisting);
    }

public record Address(Guid Id, string StreetName, int HouseNumber, int? Altitude = null);
```

**Comment by jeremydmiller** [comment]
xUnit test to reproduce this:

```
using System;
using LamarCodeGeneration;
using Marten;
using Marten.Testing.Harness;
using Xunit;

namespace DocumentDbTests.Bugs
{
#if NET6_0_OR_GREATER
    public class Bug_2160_bulk_insert_with_nested_duplicate_field : BugIntegrationContext
    {
        [Fact]
        public void BulkInsertTest()
        {
            StoreOptions(options =>
            {
                options.SetApplicationProject(GetType().Assembly);
                options.GeneratedCodeMode = TypeLoadMode.Auto;
                options.Schema.For<Person>()
                    .Duplicate(x =>
                        x.HomeAddress
                            .HouseNumber); // this causes a null-ref exception at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ValidateAndGetLengthCustom
                //options.Schema.For<Person>().Duplicate(x => x.HomeAddress.StreetName); // this seems to work fine
            });

            var people = new[] { new Person(Guid.NewGuid(), new Address(string.Empty, 0)) };
            theStore.BulkInsert(people, BulkInsertMode.OverwriteExisting);
        }
    }

    public record Person(Guid Id, Address HomeAddress);
    public record Address(string StreetName, int HouseNumber);
#endif
}

```

**Comment by jeremydmiller** [comment]
@darraghjones I might push to get 5.1 out before I get to this. Do you have to use a duplicate field in the meantime? If this is just for indexing, a computed index might be more efficient anyway.

**Comment by darraghjones** [comment]
Actually, in our performance tests we noticed the difference between calling `session.Store<T>(IEnumerable<T> entities)` and using `BulkInsert` was minimal, so we've decided not to use BulkInsert. Therefore we're in no rush for a fix, cheers.

**Comment by jeremydmiller** [comment]
Huh, how many entities at a time? It definitely makes a measurable difference at scale. And I meant for optimizing reads, now writes when I was referring to using a computed index rather than a duplicated field

**Comment by darraghjones** [comment]
in my case i'm saving around 5k entities. in my tests this takes around 4 seconds with either approach. however, it seems `bulkinsert` still takes around 4 seconds if i increase this to 15k for example, whereas `store` takes 9s, and for 50k, `bulkinsert` still only takes around 4s, and now `store` takes 40s.

**Comment by mysticmind** [comment]
After a long troubleshooting session, have zeroed in this issue to be an issue with Npgsql and not Marten. See a minimum repro below:

```cs
var conn = new NpgsqlConnection(connStr);
conn.Open();

using var cmd = new NpgsqlCommand("create table if not exists person(house_number integer)", conn);
cmd.ExecuteNonQuery();

using var writer = conn.BeginBinaryImport("COPY person(house_number) FROM STDIN BINARY");
var person = new Person(Guid.NewGuid(), new Address(1));
writer.StartRow();
writer.Write(person.Address?.HouseNumber, NpgsqlDbType.Integer);
writer.Complete();

public record Person(Guid Id, Address Address);
public record Address(int HouseNumber);
```

The above results in an exception as below:

```
/Users/babuannamalai/tinker_room/npgsql_bulkinsert_test/npgsql_bulkinsert_test/bin/Debug/net6.0/npgsql_bulkinsert_test
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ValidateAndGetLengthCustom[TAny](TAny value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter`1.ValidateAndGetLength()
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlParameter param, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlDbType npgsqlDbType)
   at Program.<Main>$(String[] args) in /Users/babuannamalai/tinker_room/npgsql_bulkinsert_test/npgsql_bulkinsert_test/Program.cs:line 16
```

In summary, `writer.write(...)` with input like `person.Address?.HouseNumber` with nullable type is tripping Npgsql. I will need to raise a bug in Npgsql repo.

**Comment by mysticmind** [comment]
Raised this issue https://github.com/npgsql/npgsql/issues/4417 in in Npgsql repo

**Comment by mysticmind** [comment]
If you run through the issue raised in the npgsql repo, nullable types are not supported for COPY operation. Currently they are only fixing NRE so that it throws the right exception i.e.`InvalidCastException`

**Comment by jeremydmiller** [comment]
@mysticmind Yikes, thanks for chasing that down Babu!

**Comment by jeremydmiller** [comment]
I'm closing this as there's nothing we can do about it.
