### ISSUE TITLE
System.Text.Json serializer issue when deserializing List<string>

### ISSUE THREAD

**Issue by toanxyz** [JasperFx/marten#2192]
To reproduce the issue, we have a few classes as below:

The DTO model:
```
public record ProductRecord(List<string> ImageUris)
```

The database model:
```
public class Product
{
    public string Id { get; set; }
    public List<string> ImageUris { get; set; } = new();
}
```

The JSON value in database:
```
{
  "Id": "Product-1",
  "ImageUris": [
    "https://theurl.com/Product1"
  ],
}
```

The LINQ query:
```
var productsQuery = _session
    .Query<Product>()
    .Select(p => new ProductRecord(p.ImageUris))
    .ToList();
```

When using NewtonsoftJson with the default serializer, there is no issue. The generated query is:
```
Marten executed in 24 ms, SQL: select jsonb_build_object(CAST(d.data ->> 'ImageUris' as jsonb)) as data from public.mt_doc_product
```

However, when using System.Text.Json `options.UseDefaultSerialization(serializerType: Marten.Services.Json.SerializerType.SystemTextJson);`, the exception happened with the following details:

```
Marten.Exceptions.MartenCommandException: Marten Command Failure:$
select jsonb_build_object('ImageUris', CAST(d.data ->> 'ImageUris' as varchar[])) as data from public.mt_doc_product$
$
22P02: malformed array literal: "["https://theurl.com/Product1"]"
DETAIL: "[" must introduce explicitly-specified array dimensions.
---> Npgsql.PostgresException (0x80004005): 22P02: malformed array literal: "["https://theurl.com/Product1"]"
DETAIL: "[" must introduce explicitly-specified array dimensions.
at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
Exception data:
Severity: ERROR
SqlState: 22P02
MessageText: malformed array literal: "["https://theurl.com/Product1"]"
Detail: "[" must introduce explicitly-specified array dimensions.
File: arrayfuncs.c
Line: 271
Routine: array_in
--- End of inner exception stack trace ---
at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
at Baseline.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(NpgsqlCommand command, Exception exception)
at Marten.Internal.Sessions.QuerySession.handleCommandException(NpgsqlCommand cmd, Exception e)
at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token)
```

I think because of the "CAST(d.data ->> 'ImageUris' as varchar[])". For Newtonsoft.Json, it was "CAST(d.data ->> 'ImageUris' as jsonb)". The generated query is also quite different between Newtonsoft and System.Text, not just this List type, but only the List type cause the issue so far.

Now to avoid this issue, we have to move back to Newtonsoft.Json.

**Comment by jeremydmiller** [comment]
@toanxyz The SQL generation in the Linq provider does not vary by serializer type. With the obvious workaround being "just use Newtonsoft because everything just works", we might not get to this anytime soon unless you want to try to push through a fix -- which I'd bet comes down to introducing a type converter to customize our STJ usage. Other folks have done that so far.
