### ISSUE TITLE
Using LINQ to query a document with a `DateTime` property, stored as UTC, with a `UTC` Kind `DateTime` throws an exception

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#2198]
Failing Test PR incoming.

Example code:
```
theSession.Query<Target>().Where(x => x.Date > DateTime.UtcNow)
```

Stack Trace:
```
    System.InvalidCastException : Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
    Stack Trace:
       at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampHandler.ValidateAndGetLength(DateTime value, NpgsqlParameter parameter)
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marten.NulloRetryPolicy.Execute[TResult](Func`1 operation) in /Users/ericgreen/OSS/marten/src/Marten/NulloRetryPolicy.cs:line 19
   at Marten.Internal.Sessions.QuerySession.ExecuteReader(NpgsqlCommand command) in /Users/ericgreen/OSS/marten/src/Marten/Internal/Sessions/QuerySession.Connection.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Baseline.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   ```

**Comment by toanxyz** [comment]
This is the breaking change of Npgsql 6.0 (https://www.npgsql.org/efcore/release-notes/6.0.html)

The quick solution below will keep the same behavior, however I don’t think it’s a long term solution.
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

In our project, we decided to migrate to use DateTimeOffset since we don’t want to use NodaTime which can add more dependencies to the existing project.

**Comment by ericgreenmix** [comment]
Right, I know about the Npgsql 6 changes.

From their docs:
```
In many cases, it makes sense to store UTC timestamps in the database. To do this, migrate your timestamp without time zone columns to timestamp with time zone ([see migration notes below](https://www.npgsql.org/efcore/release-notes/6.0.html?tabs=annotations#migrating-columns-from-timestamp-to-timestamptz)), and always use either DateTime with Kind=Utc or DateTimeOffset with offset 0.
```

We are using DateTime with Kind=Utc. Which _should_ work. 

Since we are dealing with jsonb documents, which have a `DateTime` property serialized on them. I think this is an issue with how Marten is casting the data times in the sql the LINQ generates.

**Comment by ericgreenmix** [comment]
I was reading through the NPG sql 6 change docs about this change for the millionth time again. I think it would make sense for Marten to take the same approach that EF Core did with its DateTime LINQ queries, summarized by:

> By nature, EF Core must make mapping decisions solely based on the type (DateTime) and cannot take the Kind into account, so we have to pick one type or the other as the default. Since “UTC everywhere” should generally be preferred, we now map DateTime to timestamptz
(https://www.roji.org/postgresql-dotnet-timestamp-mapping)

**Comment by jeremydmiller** [comment]
@ericgreenmix That's a breaking change in Marten, so no go. We *could* try to be cute and be adaptive in the Linq layer and change the SQL construction in the Linq support based on the Kind, but that might be a pretty big change. 

TBH, for right now I just want a big note in the docs to favor DateTimeOffset or NodaTime. Either way, we've got a bunch of event store bug fixes ready to go, and this is too much context switching to deal with quickly, so I'm kicking it back.

**Comment by ericgreenmix** [comment]
Yes, any kind of mention of this in the documentation would be a huge win. As well as including it in the migration guide.

**Comment by jeremydmiller** [comment]
We can stick it in the docs, but thinking about it more today, I think we'll try to intercept the exception and explain the workarounds and the link up above in the exception text.

**Comment by ericgreenmix** [comment]
Even better
