### ISSUE TITLE
Inner properties are not deserliazed when using Select projections

### ISSUE THREAD

**Issue by egorpavlikhin** [JasperFx/marten#2211]
When trying to use a projection that expects an inner property to be passed as a whole object (as opposed to using just nested properties) projections fails with deserialization exceptions. See the code below:

Test to reproduce:
```csharp
/*class InnerTarget
{
    public InnerTarget(Target inner)
    {
        Inner = inner;
    }

    public Target Inner { get; set; }
}*/

var target = Target.Random(true);

theSession.Store(target);
theSession.SaveChanges();

var actual = theSession.Query<Target>()
    .Where(x => x.Id == target.Id)
    .Select(x => new InnerTarget(x.Inner))
    .First();

actual.Inner.Id.ShouldBe(target.Inner.Id);
actual.Inner.Number.ShouldBe(target.Inner.Number);
```

Exception:
```
Newtonsoft.Json.JsonSerializationException
Error converting value "{"Id": "2c571dcc-65b8-429a-bb42-9c45833c9604", "Date": "2005-12-29T00:00:00+11:00", "Flag": false, "Long": 1529706464, "Color": 1, "Float": 0.2573189, "Inner": null, "Double": 0.6195458437407138, "Number": 56753383, "String": "Gray", "UserId": "00000000-0000-0000-0000-000000000000", "Decimal": 0.0, "Children": null, "GuidArray": null, "OtherGuid": "00000000-0000-0000-0000-000000000000", "TagsArray": null, "DateOffset": "0001-01-01T00:00:00+00:00", "StringDict": {}, "StringList": [], "NumberArray": [7, 2, 3], "StringField": null, "TagsHashSet": null, "NullableEnum": null, "AnotherNumber": 1149552278, "AnotherString": "nine", "NullableColor": null, "NullableNumber": null, "NullableBoolean": null, "NullableDateTime": null}" to type 'Marten.Testing.Documents.Target'. Path 'inner', line 1, position 813.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Marten.Services.JsonNetSerializer.FromJson[T](DbDataReader reader, Int32 index) in C:\Source\marten\src\Marten\Services\JsonNetSerializer.cs:line 114
   at Marten.Linq.Selectors.SerializationSelector`1.Resolve(DbDataReader reader) in C:\Source\marten\src\Marten\Linq\Selectors\SerializationSelector.cs:line 18
   at Marten.Linq.QueryHandlers.OneResultHandler`1.Handle(DbDataReader reader, IMartenSession session) in C:\Source\marten\src\Marten\Linq\QueryHandlers\OneResultHandler.cs:line 51
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandler[T](IQueryHandler`1 handler) in C:\Source\marten\src\Marten\Linq\MartenLinqQueryProvider.cs:line 132
   at Marten.Linq.MartenLinqQueryProvider.Execute[TResult](Expression expression) in C:\Source\marten\src\Marten\Linq\MartenLinqQueryProvider.cs:line 56
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at DocumentDbTests.Reading.Linq.invoking_query_with_select_Tests.use_select_in_query_for_one_object_property() in C:\Source\marten\src\DocumentDbTests\Reading\Linq\invoking_query_with_select_Tests.cs:line 353

System.ArgumentException
Could not cast or convert from System.String to Marten.Testing.Documents.Target.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
```

**Comment by egorpavlikhin** [comment]
Smaller test:
```csharp
var target = Target.Random(true);

theSession.Store(target);
theSession.SaveChanges();

var actual = theSession.Query<Target>()
  .Where(x => x.Id == target.Id)
  .Select(x => new { Inner = x.Inner })
  .First();

actual.Inner.Number.ShouldBe(target.Inner.Number);
```

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/pull/2212
