### ISSUE TITLE
duplicate key value violates unique constraint "pk_mt_events_stream_and_version"

### ISSUE THREAD

**Issue by daniel-botero-cko** [JasperFx/marten#2260]
Hello,

When an event is being inserted into the mt_events table, I have this exception randomly. It seems I cannot do anything about it other than retrying until the event is inserted. This is a bit annoying because I have more than 300 errors in a few minutes showing up in my logs.

Is this a known issue?

My code is pretty simple:

```
Variable:

IDocumentStore _store (This is injected via Dependency Injection)

Method's body:

            using (var session = _store.OpenSession())
            {
                if (@event.IsBeginningOfStream)
                    session.Events.StartStream<XXXXX>(@event.StreamId, @event);
                else
                    session.Events.Append(@event.StreamId, @event);

                await session.SaveChangesAsync(cancellationToken);
            }
```
Am I doing something wrong?

I am using Marten 5.5.1.

```
Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "pk_mt_events_stream_and_version"

DETAIL: Key (stream_id, version)=(mt_tombstone, 1) already exists.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Datadog.Trace.ClrProfiler.CallTarget.Handlers.Continuations.TaskContinuationGenerator`4.ContinuationAction(Task`1 previousTask, TTarget target, CallTargetState state)
   at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
  Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "pk_mt_events_stream_and_version"
    Detail: Key (stream_id, version)=(mt_tombstone, 1) already exists.
    SchemaName: public
    TableName: mt_events
    ConstraintName: pk_mt_events_stream_and_version
    File: nbtinsert.c
    Line: 537
    Routine: _bt_check_unique
```

**Comment by daniel-botero-cko** [comment]
@ericgreenmix Is there any workaround that I can do to prevent this until it is fixed? Or do you know which version of Marten doesn't have this issue (other than V3)?

**Comment by ericgreenmix** [comment]
I believe this is present on V4+. I don't have a work around, other than to not have failures when events are saved :)
