### ISSUE TITLE
Async Daemon fails with `ConcurrencyException` when processing async projections with documents that use Optimistic Concurrency

### ISSUE THREAD

**Issue by ericgreenmix** [JasperFx/marten#2267]
It works fine when the projected document does not have OptimisticConcurrency turned on. As soon as you add Optimistic Concurrency, the daemon throws this exception:

Exception:
```
 ---> Marten.Exceptions.ConcurrencyException: Optimistic concurrency check failed for Marten.AsyncDaemon.Testing.TestingSupport.Trip #c9b286ac-2f67-4e98-99d1-2f379c7cd15d
   --- End of inner exception stack trace ---
   at Marten.Events.Daemon.ProjectionUpdateBatch.Marten.Internal.IUpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token) in /Users/ericgreen/OSS/marten/src/Marten/Events/Daemon/ProjectionUpdateBatch.cs:line 110
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token) in /Users/ericgreen/OSS/marten/src/Marten/Internal/Sessions/DocumentSessionBase.SaveChanges.cs:line 182
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token) in /Users/ericgreen/OSS/marten/src/Marten/Internal/Sessions/DocumentSessionBase.SaveChanges.cs:line 204
   at Marten.Events.Daemon.ShardAgent.ExecuteBatch(ProjectionUpdateBatch batch) in /Users/ericgreen/OSS/marten/src/Marten/Events/Daemon/ShardAgent.cs:line 431
   at Marten.Events.Daemon.ShardAgent.ExecuteBatch(ProjectionUpdateBatch batch) in /Users/ericgreen/OSS/marten/src/Marten/Events/Daemon/ShardAgent.cs:line 449
   at Marten.Events.Daemon.ShardAgent.<>c__DisplayClass44_0.<<processRange>b__2>d.MoveNext() in /Users/ericgreen/OSS/marten/src/Marten/Events/Daemon/ShardAgent.cs:line 228
--- End of stack trace from previous location ---
   at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters) in /Users/ericgreen/OSS/marten/src/Marten/Events/Daemon/ProjectionDaemon.cs:line 364
```

Failing test PR coming shortly

**Comment by ericgreenmix** [comment]
@jeremydmiller That makes sense for Async projections, however we have inline projections that we need optimistic concurrency on. If I go to rebuild an Inline projection that has optimistic concurrency set, I get this same error. That seems like a scenario that should work or ignore the OC setting.

**Comment by jeremydmiller** [comment]
I almost buy that, but there's existing optimistic concurrency checks at the event stream level too.

If this is really something you have to have, I'd say the answer is that in the aggregate projection codegen, it opts into using the Overwrite() operations instead of Store() whenever the document has optimistic concurrency turned on.
