### ISSUE TITLE
System.InvalidCastException: The GetTextReader method is not supported for type timestamp with time zone

### ISSUE THREAD

**Issue by jamiepenney** [JasperFx/marten#2283]
Hi team,

I've updated from v3 -> v5.6.0 and run into an issue reading DateTime fields back out. I've set the Npgsql handling back to legacy mode already and most of the code is working as expected, but the following code fails at runtime:

```
var minDate = await_session
    .Query<MyModel>()
    .Where(t => t.UserId == userId)
    .MinAsync(t => t.Date);
```

`Date` is a duplicated `DateTime` field on `MyModel`.

It throws the following exception:

```
System.InvalidCastException: The GetTextReader method is not supported for type timestamp with time zone
   at Npgsql.NpgsqlDataReader.GetTextReader(Int32 ordinal, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.GetTextReader(Int32 ordinal)
   at Marten.Services.JsonNetSerializer.FromJson[T](DbDataReader reader, Int32 index)
   at Marten.Services.JsonNetSerializer.FromJsonAsync[T](DbDataReader reader, Int32 index, CancellationToken cancellationToken)
   at Marten.Linq.Selectors.SerializationSelector`1.ResolveAsync(DbDataReader reader, CancellationToken token)
   at Marten.Linq.QueryHandlers.OneResultHandler`1.HandleAsync(DbDataReader reader, IMartenSession session, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token, ResultOperatorBase op)
   at <my code from here>
```

I've set the `storeOptions.Advanced.DuplicatedFieldUseTimestampWithoutTimeZoneForDateTime = false;` option, but all this does is change the error message to talk about `timestamp with time zone` instead of `without time zone`.

Any idea what's going wrong here?

**Comment by jeremydmiller** [comment]
@jamiepenney At this point, I just don't think it's feasible to use `DateTime` with Npgsql v6. I just put in this validation:

```
            if (innerField.FieldType == typeof(DateTime))
            {
                throw new InvalidDuplicatedFieldTypeException(
                    $"DateTime member {innerField.Members.Select(x => x.Name).Join(".")} cannot be a DuplicatedField. Consider using a computed index for query optimization, switching to DateTimeOffset or NodaTime wherever possible, or see https://www.npgsql.org/efcore/release-notes/6.0.html.");
            }
```

If you're only using the duplicated field for query optimization, then a computed index is more efficient overall anyway. Otherwise, I think it's bite the bullet and switch to DateTimeOffset.

Sorry there's not a better answer here if the Npgsql legacy mode thing doesn't work.

**Comment by jeremydmiller** [comment]
Belay that, can't do that. Too many test failures. Now I'm just trying for a better exception message.
