### ISSUE TITLE
Can't write CLR type System.Collections.Generic.List`1[System.Guid] with handler type UuidHandler

### ISSUE THREAD

**Issue by borgez** [JasperFx/marten#2357]
When i try
```
public class Some{
	public List<Guid> Members { get; set; } = new();
}

List<Guid> users = new (){guid1, guid2}

var query = session
  .Query<Some>()
  .Where(w => w.Members.In(users))
  .ToList();
```
I got exception
```
Can't write CLR type System.Collections.Generic.List`1[System.Guid] with handler type UuidHandler
   at Npgsql.Internal.TypeHandlers.UuidHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.Internal.TypeHandlers.ArrayHandler`1.ValidateAndGetLengthNonGeneric(ICollection value, NpgsqlLengthCache& lengthCache)
```

```
System.Exception
While trying to write an array, one of its elements failed validation. You may be trying to mix types in a non-generic IList, or to write a jagged array.
   at Npgsql.Internal.TypeHandlers.ArrayHandler`1.ValidateAndGetLengthNonGeneric(ICollection value, NpgsqlLengthCache& lengthCache)
   at Npgsql.Internal.TypeHandlers.ArrayHandler`1.ValidateAndGetLength(Object value, NpgsqlLengthCache& lengthCache)
   at Npgsql.Internal.TypeHandlers.ArrayHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Marten.NulloRetryPolicy.Execute[TResult](Func`1 operation)
   at Marten.Internal.Sessions.QuerySession.ExecuteReader(NpgsqlCommand command)
--- End of stack trace from previous location ---
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Baseline.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(NpgsqlCommand command, Exception exception)
   at Marten.Internal.Sessions.QuerySession.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Internal.Sessions.QuerySession.ExecuteReader(NpgsqlCommand command)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandler[T](IQueryHandler`1 handler)
--- End of stack trace from previous location ---
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Baseline.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandler[T](IQueryHandler`1 handler)
   at Marten.Linq.MartenLinqQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by jeremydmiller** [comment]
Can you try the Marten `IsOneOf()`? You just hit something that Marten's Linq support doesn't yet support

**Comment by oskardudycz** [comment]
@borgez, this is intentional; use `IsSubsetOf` instead. Because of how `params []` in C# work, it was possible to call `In` and `IsOneOf` for List or other generic collections. This is unintended usage. I restricted the `In` and `IsOneOf` LINQ operators to regular fields and also added missing tests in #2378. 

Unfortunately, the compiler will still allow it, but we'll get at least more meaningful error information.
