### ISSUE TITLE
CLI Exception: System.InvalidOperationException: Could not find color or style ''

### ISSUE THREAD

**Issue by AlexSuprunQuali** [JasperFx/marten#2373]
Hi
I get error when I try to run `dotnet run -- marten-assert` CLI command on the AspNetCoreWithMarten project in the Marten solution 

```
Database 'Marten' does not match the configuration!
ERROR: System.InvalidOperationException: Could not find color or style ''.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 13
   at Spectre.Console.MarkupParser.Parse(St
ring text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 26
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/An
siConsoleExtensions.Markup.cs:line 41
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 62
   at Spectre.
Console.AnsiConsole.MarkupLine(String value) in /_/src/Spectre.Console/AnsiConsole.Markup.cs:line 46
   at Weasel.CommandLine.AssertCommand.Execute(WeaselInput input)
   at Oakton.CommandExecutor.execute(CommandRun run)
```

**Comment by jeremydmiller** [comment]
@AlexSuprunQuali Do you by chance have brackets "[" or "]" in your database or schema names? Is that even possible?

**Comment by AlexSuprunQuali** [comment]
> @AlexSuprunQuali Do you by chance have brackets "[" or "]" in your database or schema names? Is that even possible?

No, I don't brackets

**Comment by jeremydmiller** [comment]
I'm making some changes to Weasel's usage of Spectre that might/should/maybe address whatever the underlying problem was here.

**Comment by jeremydmiller** [comment]
I'm saying that #2381 deals with the Spectre problem

**Comment by AlexSuprunQuali** [comment]
@jeremydmiller Do you plan to release a new nuget for Marten.CommandLine?
