### ISSUE TITLE
Command-line codegen attempts to connect to database when CreateDatabasesForTenants is used

### ISSUE THREAD

**Issue by Hawxy** [JasperFx/marten#2390]
~~Noticed this immediately within our docker build.~~
~~Regression of #2337~~

See: https://github.com/JasperFx/marten/issues/2390#issuecomment-1316743594

**Comment by jeremydmiller** [comment]
Did you update Npgsql to 7? We haven't done any hard testing on that yet, and new Npgsql drops **always** break Marten

**Comment by oskardudycz** [comment]
@Hawxy, could you check with alpha.3? I think that should be fixed now (at least based on the test suite).

**Comment by Hawxy** [comment]
Nup, still seeing the same thing with v6.
```
05:07:58 [DBG] ERROR: Npgsql.NpgsqlException (0x80004005): Failed to connect to [::1]:5432
  05:07:58 [DBG]  ---> System.Net.Internals.SocketExceptionFa
  05:07:58 [DBG] ctory+ExtendedSocketException (99): Cannot assign requested address [::1]:5432
  05:07:58 [DBG]    at System.Net.Sockets.Socket.DoConnect
  05:07:58 [DBG] (EndPoint endPointSnapshot, SocketAddress socketAddress)
  05:07:58 [DBG]    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
  05:07:58 [DBG]    a
  05:07:58 [DBG] t Npgsql.Internal.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
  05:07:58 [DBG]    at Npgsql.Internal.NpgsqlConnector.Connect(NpgsqlTim
  05:07:58 [DBG] eout timeout)
  05:07:58 [DBG]    at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, Cance
  05:07:58 [DBG] llationToken cancellationToken, Boolean isFirstAttempt)
  05:07:58 [DBG]    at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|204_1(Np
  05:07:58 [DBG] gsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean 
  05:07:58 [DBG] isFirstAttempt)
  05:07:58 [DBG]    at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cance
  05:07:58 [DBG] llationToken)
  05:07:58 [DBG]    at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean asyn
  05:07:58 [DBG] c, CancellationToken cancellationToken)
  05:07:58 [DBG]    at Npgsql.PoolingDataSource.<Get>g__RentAsync|28_0(NpgsqlConnection conn, Npg
  05:07:58 [DBG] sqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
  05:07:58 [DBG]    at Npgsql.NpgsqlConnection.<Open>g__OpenAsync
  05:07:58 [DBG] |45_0(Boolean async, CancellationToken cancellationToken)
  05:07:58 [DBG]    at Npgsql.NpgsqlConnection.Open()
  05:07:58 [DBG]    at Marten.Schema.Datab
  05:07:58 [DBG] aseGenerator.IsNotInPgDatabase(String catalog, String maintenanceDb)
  05:07:58 [DBG]    at Marten.Schema.DatabaseGenerator.<>c__DisplayC
  05:07:58 [DBG] lass6_0.<CreateDb>b__0()
  05:07:58 [DBG]    at Marten.Schema.DatabaseGenerator.CreateDb(Tenant tenant, TenantDatabaseCreationExpressions
  05:07:58 [DBG]  config)
  05:07:58 [DBG]    at Marten.Schema.DatabaseGenerator.CreateDatabases(ITenancy tenancy, Action`1 configure)
  05:07:58 [DBG]    at Marten.Docume
  05:07:58 [DBG] ntStore..ctor(StoreOptions options)
  05:07:58 [DBG]    at Marten.MartenServiceCollectionExtensions.<>c.<AddMarten>b__8_1(IServiceProvide
  05:07:58 [DBG] r s)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite ca
  05:07:58 [DBG] llSite, TArgument argument)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRo
  05:07:58 [DBG] otCache(ServiceCallSite callSite, RuntimeResolverContext context)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.Service
  05:07:58 [DBG] Lookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
  05:07:58 [DBG]    at Microsoft.Extensions.Dependen
  05:07:58 [DBG] cyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
  05:07:58 [DBG]   
  05:07:58 [DBG]  at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
  05:07:58 [DBG]    at System.Collec
  05:07:58 [DBG] tions.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInj
  05:07:58 [DBG] ection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
  05:07:58 [DBG]    at Microso
  05:07:58 [DBG] ft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type se
  05:07:58 [DBG] rviceType)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServic
  05:07:58 [DBG] eProvider provider)
  05:07:58 [DBG]    at Marten.MartenServiceCollectionExtensions.<>c.<AddMarten>b__8_4(IServiceProvider s)
  05:07:58 [DBG]    at Micro
  05:07:58 [DBG] soft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgumen
  05:07:58 [DBG] t argument)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceC
  05:07:58 [DBG] allSite callSite, RuntimeResolverContext context)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteV
  05:07:58 [DBG] isitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.Serv
  05:07:58 [DBG] iceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext contex
  05:07:58 [DBG] t)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite call
  05:07:58 [DBG] Site, TArgument argument)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRoot
  05:07:58 [DBG] Cache(ServiceCallSite callSite, RuntimeResolverContext context)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceLo
  05:07:58 [DBG] okup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
  05:07:58 [DBG]    at Microsoft.Extensions.Dependency
  05:07:58 [DBG] Injection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
  05:07:58 [DBG]    a
  05:07:58 [DBG] t Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
  05:07:58 [DBG]    at System.Collecti
  05:07:58 [DBG] ons.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjec
  05:07:58 [DBG] tion.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
  05:07:58 [DBG]    at Microsoft
  05:07:58 [DBG] .Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serv
  05:07:58 [DBG] iceType)
  05:07:58 [DBG]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceP
  05:07:58 [DBG] rovider provider)
  05:07:58 [DBG]    at LamarCodeGeneration.Commands.GenerateCodeCommand.Execute(GenerateCodeInput input)
  05:07:58 [DBG]    at Oakton.O
  05:07:58 [DBG] aktonCommand`1.Oakton.IOaktonCommand.Execute(Object input)
  05:07:58 [DBG]    at Oakton.CommandRun.Execute()
  05:07:58 [DBG]    at Oakton.CommandExecuto
  05:07:58 [DBG] r.execute(CommandRun run)
```

**Comment by oskardudycz** [comment]
@Hawxy, thanks for checking that out. I'll have a look what can be wrong. Would you mind sharing your Docker build configuration?

**Comment by Hawxy** [comment]
Sure, Dockerfile is just a slightly modified version of the default:
```
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Project.Api/Project.Api.csproj", "Project.Api/"]
COPY ["Project/Project.csproj", "Project/"]
RUN dotnet restore "Project.Api/Project.Api.csproj"
COPY . .
WORKDIR "/src/Project.Api"
RUN dotnet run -- codegen write
RUN dotnet build "Project.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Project.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Project.Api.dll"]
```

**Comment by Hawxy** [comment]
Gah, I did some additional testing and this doesn't appear to be a regression, rather the `CreateDatabasesForTenants` configuration option tries to create the database during codegen and fails. This appears to have never worked.

**Comment by oskardudycz** [comment]
Yes, that's my guess, as I didn't change much there, just fixed one bug related to it. Still, If you share the configuration, then I could see if I could fix it. I'm working on bugs related to multitenancy now.

**Comment by Hawxy** [comment]
This is the cut down version I was testing
```
var host = Host.CreateDefaultBuilder(args)
    .ConfigureServices((ctx, services) =>
    {
        services.AddMarten(_ =>
        {
            _.Connection(ctx.Configuration.GetConnectionString("Postgres")!);
            _.Policies.AllDocumentsAreMultiTenanted();
            _.UseDefaultSerialization(EnumStorage.AsString, serializerType: SerializerType.SystemTextJson);
            _.CreateDatabasesForTenants(c =>
            {
                c.ForTenant()
                    .CheckAgainstPgDatabase()
                    .WithEncoding("UTF-8")
                    .ConnectionLimit(-1);

            });

            _.Schema.For<SomeType>()
                .GinIndexJsonData();
        }).OptimizeArtifactWorkflow().ApplyAllDatabaseChangesOnStartup();

    })
    .ApplyOaktonExtensions()
    .Build();

await host.RunOaktonCommands(args);

public record SomeType(Guid Id);
```

**Comment by jeremydmiller** [comment]
Oh, ouchie, guys this is gonna take some thought. I'd propose some way to "know" that the system is being used for diagnostic/utility purposes and that there should be no attempt to connect.

**Comment by jeremydmiller** [comment]
Actually, I do have a relatively painless solution! In V6, let's move the whole `CreateDatabase()` business to a separate `IHostedService` and/or plug it into the Oakton "stateful resource" model. Move it completely out of `StoreOptions` and into a chained call after `AddMarten()`. That will enable Marten to spin up the `DocumentStore` without ever doing any IO to enable the codegen command to run cleanly **and** also have the benefit of not doing any synchronous database calls in the `DocumentStore` constructor.

**Comment by oskardudycz** [comment]
@jeremydmiller that sounds good to me 👍

**Comment by jeremydmiller** [comment]
I *have* fixed this in a local branch. I need to rebase and push the fix.

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/commit/011ab2f88dc498dec122e1062a14cf12570fab8e
