### ISSUE TITLE
upsert function does not exist when saving changes

### ISSUE THREAD

**Issue by bdelavega-maralytix** [JasperFx/marten#2393]
I don't know if this is a bug per se, as I might be missing something that's obvious to others.  Apologies in advance. 

Here's the error I'm seeing:
```
Marten.Exceptions.MartenCommandException: Marten Command Failure:$
select public.mt_upsert_activitycomment(:p0, :p1, :p2, :p3);select public.mt_upsert_activitycomment(:p4, :p5, :p6, :p7);select public.mt_upsert_activitycomment(:p8, :p9, :p10, :p11);select public.mt_upsert_activitycomment(:p12, :p13, :p14, :p15);select public.mt_upsert_activitycomment(:p16, :p17, :p18, :p19);select public.mt_upsert_activitycomment(:p20, :p21, :p22, :p23);select public.mt_upsert_activitycomment(:p24, :p25, :p26, :p27);$
$
42883: function public.mt_upsert_activitycomment(jsonb, character varying, text, uuid) does not exist

POSITION: 8
 ---> Npgsql.PostgresException (0x80004005): 42883: function public.mt_upsert_activitycomment(jsonb, character varying, text, uuid) does not exist

POSITION: 8
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
  Exception data:
    Severity: ERROR
    SqlState: 42883
    MessageText: function public.mt_upsert_activitycomment(jsonb, character varying, text, uuid) does not exist
    Hint: No function matches the given name and argument types. You might need to add explicit type casts.
    Position: 8
    File: parse_func.c
    Line: 621
    Routine: ParseFuncOrColumn
   --- End of inner exception stack trace ---
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Baseline.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(NpgsqlCommand command, Exception exception)
   at Marten.Internal.Sessions.QuerySession.handleCommandException(NpgsqlCommand cmd, Exception e)
   at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
   at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
   at Baseline.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
   ...
```

And the C# code that causes it:
```
        var docSession = GetDocumentSession(theScope);
        foreach (var item in items)
        {
            docSession.Store(item);
        }
        await docSession.SaveChangesAsync();
```
where `docSession` is an `IDocumentSession` and `items` is `IEnumerable<ActivityComment>`.

I have a few types of objects stored in Marten. I see the upsert functions
<img width="479" alt="image" src="https://user-images.githubusercontent.com/14293231/201362480-4e9ee9d3-8236-4c4d-b48d-e4b1d7b44175.png">

I can confirm that the mt_upsert_activity is working (at least i have no issue adding Activity records). I notice that the number of parameters in the upsert functions are different. Also mt_upsert_activity has 5 input parameters, but it looks like the error shows 4 arguments.

This is with PostgreSQL 11.14 and Marten 5.10.1.

Thanks for any pointers.

**Comment by bdelavega-maralytix** [comment]
I was able to resolve this issue by making all 4 objects share the same Marten metadata - they all implement `ITracking` and the issue went away.  Now all the upsert stored procedures look like the mt_upsert_activity and they all work fine.

**Comment by xperiandri** [comment]
test
