### ISSUE TITLE
Marten.Exceptions.InvalidDocumentException: Could not determine an 'id/Id' field or property for requested document type System.Linq.IGrouping`2[[System.String, System.Private.CoreLib

### ISSUE THREAD

**Issue by borgez** [JasperFx/marten#2395]
When i try
```
public class Some{
	public string SomeString{ get; set; };
}

var query = session
  .Query<Some>()
  .GroupBy(g => g.SomeString)
  .Select(s => new { s.Key, Count = s.Count() })
  .ToList();
```
I got exception

``` An unhandled exception has occurred while executing the request.
      Marten.Exceptions.InvalidDocumentException: Could not determine an 'id/Id' field or property for requested document type System.Linq.IGrouping`2[[System.String, System.Private.CoreLib,
         at Marten.Schema.DocumentMapping.CompileAndValidate()
         at Marten.Storage.DocumentTable..ctor(DocumentMapping mapping)
         at Marten.Schema.DocumentSchema..ctor(DocumentMapping mapping)
         at Marten.Schema.DocumentMapping.<.ctor>b__6_0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
      --- End of stack trace from previous location ---
         at System.Lazy`1.CreateValue()
         at Marten.Schema.DocumentMapping.get_Schema()
         at Marten.Internal.CodeGeneration.DocumentOperations..ctor(GeneratedAssembly assembly, DocumentMapping mapping, StoreOptions options)
         at Marten.Internal.CodeGeneration.DocumentProviderBuilder.AssembleTypes(GeneratedAssembly assembly)
         at LamarCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
         at Marten.Internal.ProviderGraph.StorageFor[T]()
         at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
         at Marten.Internal.Sessions.QuerySession.StorageFinder`1.Find(QuerySession session)
         at Marten.Internal.Sessions.QuerySession.StorageFor(Type documentType)
         at Marten.Linq.Parsing.LinqHandlerBuilder..ctor(MartenLinqQueryProvider provider, IMartenSession session, Expression expression, ResultOperatorBase additionalOperator, Boolean forCompiled)
         at Marten.Linq.MartenLinqQueryProvider.Execute[TResult](Expression expression)
         at Remotion.Linq.QueryableBase`1.GetEnumerator()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by mysticmind** [comment]
@borgez Please check docs https://martendb.io/documents/identity.html#document-identity.
> Marten's only other requirement for a .Net type to be a document is the existence of an identifier field or property that Marten can use as the primary key for the document type. The Id can be either a public field or property, and the name must be either id or Id or ID.

If you want to use a different property name as identifier then check https://martendb.io/documents/identity.html#overriding-the-choice-of-id-property-field
