### ISSUE TITLE
Linux issue  - LamarCompiler.ExpectedTypeMissingException : Could not load expected pre-built types for code file 

### ISSUE THREAD

**Issue by lamelyan** [JasperFx/marten#2421]
My code runs without issues on my Windows box. However, when I try to run it on a Linux docker container, I get the following error:

```
Error Message:
 LamarCompiler.ExpectedTypeMissingException : Could not load expected pre-built types for code file BuyerProvider466321713 (Marten.Internal.CodeGeneration.DocumentProviderBuilder)
Stack Trace:
   at LamarCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
 at Marten.Internal.ProviderGraph.StorageFor[T]()
 at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
 at Marten.Internal.Sessions.DocumentSessionBase.Insert[T](T[] entities)
```

The docker container contains all the files (as I copy the entire source directory).  

What could be the issue? Is Lamar having issues reading files on Linux OS?

**Comment by jeremydmiller** [comment]
@lamelyan First thing to do is check where those files were written to. The *should* be directly in your project root under /Internal/Generated. If not, there's an explicit config option to "force" the files to go to the right place.

**Comment by lamelyan** [comment]
@jeremydmiller yes, the files are pre-generated in my main project's /Internal/Generated folder. However, they are not found when tests are running. 

I found the spot where the error is thrown.  In the screenshot, I've set the TypeLoadMode to Dynamic.  I need to step through to see what exactly happens when it's Static.  It looks like on line  109, the types are loaded (via AttachTypesSynchronously) and they fail. 

![image](https://user-images.githubusercontent.com/1872686/208956983-4e313abd-f87a-441c-8f9d-7e72a207f6e0.png)

**Comment by jeremydmiller** [comment]
Can you tell if the expected types are compile in? Are you committing the generated files? Is the type name mismatched? Your error is just “I cannot find the type I expected in the main application assembly”Sent from my iPhoneOn Dec 21, 2022, at 10:41 AM, Leo Amelyan ***@***.***> wrote:﻿
@jeremydmiller yes, the files are pre-generated in my main project's /Internal/Generated folder. However, they are not found when tests are running.
I found the spot where the error is thrown.  In the screenshot, I've set the TypeLoadMode to Dynamic.  I need to step through to see what exactly happens when it's Static.  It looks like on line  109, the types are loaded (via AttachTypesSynchronously) and they fail.

**Comment by jeremydmiller** [comment]
Oh, and one more thing, **and this is annoying**, but next do a `Clean Solution` and `Rebuild Solution`. The IDE at least needs a little help sometimes to include the files that Marten/JasperFx.CodeGeneration are writing to file w/o the IDE being involved.

**Comment by appetere** [comment]
@lamelyan this is possibly because your entry assembly is the test-runner, and Marten is looking there for the generated code.

There's an example [in the docs](https://martendb.io/configuration/prebuilding.html#snippet-sample_using_set_application_project) where you can set the Application Assembly when it's not the entry assembly:

```c#
using var host = Host.CreateDefaultBuilder()
    .ConfigureServices(services =>
    {
        services.AddMarten(opts =>
        {
            opts.Connection("some connection string");
            opts.SetApplicationProject(typeof(User).Assembly);
        });
    })
    .StartAsync();
```

This fixed it for me, when I had a similar `ExpectedTypeMissingException`
