### ISSUE TITLE
Rollback failing when duplicate entry

### ISSUE THREAD

**Issue by jay-zahiri** [JasperFx/marten#2441]
Given the bare-bone setup:
```csharp
using Marten;
using Marten.Events;
using Marten.Events.Daemon.Resiliency;
using Marten.Schema;
using Weasel.Core;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost
	.UseDefaultServiceProvider((context, options) => {
		options.ValidateScopes = true;
	});

builder.Services
	.AddMarten(sp => {
		var options = new StoreOptions();
        var schemaName = Environment.GetEnvironmentVariable("SchemaName");

		options.Connection(builder.Configuration["Marten:ConnectionString"]);

        options.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
        options.Events.StreamIdentity = StreamIdentity.AsString;
        options.Events.DatabaseSchemaName = schemaName ?? builder.Configuration["Marten:WriteModelSchema"];
        options.DatabaseSchemaName = schemaName ?? builder.Configuration["Marten:ReadModelSchema"];

        options.UseDefaultSerialization(
            EnumStorage.AsInteger,
			Casing.SnakeCase,
            nonPublicMembersStorage: NonPublicMembersStorage.All
        );

		options.Projections.SelfAggregate<Entity>()
			.UniqueIndex(
				UniqueIndexType.DuplicatedField,
				org => org.Value
			);

		return options;
	})
	.ApplyAllDatabaseChangesOnStartup()
	.AddAsyncDaemon(DaemonMode.Solo);

var app = builder.Build();

app
    .UseRouting()
    .UseEndpoints(endpoints => {
		endpoints.MapPost("app/new", async (IDocumentSession documentSession) => {
			var @event = new NewEntityAdded(
				Guid.NewGuid().ToString(),
				"Test"
			);

			documentSession.Events.StartStream<Entity>(
				@event.Id,
				@event
			);

			await documentSession.SaveChangesAsync();

			return Results.Created(@event.Id, null);
		});
    });

app.Run();

public partial class Program { }

public class Entity {
	public string Id = String.Empty;
	public string Value = String.Empty;
	public int Version = 0;

	private Entity() { }

	public Entity(
		string id,
		string value
	) => Apply(new NewEntityAdded(id, value));

	private void Apply(NewEntityAdded @event) {
		Id = @event.Id;
		Value = @event.Value;
	}
};

public record NewEntityAdded(
	string Id,
	string Value
);
```

And running it with:
```sh
dotnet run -v
```

And then calling it twice with:
```sh
curl --location --request POST 'https://localhost:5051/app/new'
```

Gives me the following error
```sh
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:5051/app/new - 0
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'HTTP: POST app/new'
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      select appread.mt_upsert_entity(:p0, :p1, :p2, :p3, :p4);insert into appwrite.mt_streams (id, type, version, tenant_id) values (:p5, :p6, :p7, :p8);insert into appwrite.mt_events (data, type, mt_dotnet_type, seq_id, id, stream_id, version, timestamp, tenant_id) values (:p9, :p10, :p11, :p12, :p13, :p14, :p15, :p16, :p17);
        p0: Test
        p1: {"id":"1e3c6edd-02d0-410f-9cba-2c5118d7d089","value":"Test","version":1}
        p2: Entity
        p3: 1e3c6edd-02d0-410f-9cba-2c5118d7d089
        p4: 01856ef7-4456-4462-891f-ef9852635709
        p5: 1e3c6edd-02d0-410f-9cba-2c5118d7d089
        p6: entity
        p7: 1
        p8: *DEFAULT*
        p9: {"id":"1e3c6edd-02d0-410f-9cba-2c5118d7d089","value":"Test"}
        p10: new_entity_added
        p11: NewEntityAdded, app
        p12: 2
        p13: 01856ef7-4450-4079-aeca-f38a04eab394
        p14: 1e3c6edd-02d0-410f-9cba-2c5118d7d089
        p15: 1
        p16: 2023-01-01 20:12:56 +00:00
        p17: *DEFAULT*
      Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "mt_doc_entity_idx_value"
      
      DETAIL: Key (value)=(Test) already exists.
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|221_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
        Exception data:
          Severity: ERROR
          SqlState: 23505
          MessageText: duplicate key value violates unique constraint "mt_doc_entity_idx_value"
          Detail: Key (value)=(Test) already exists.
          Where: SQL statement "INSERT INTO appread.mt_doc_entity ("value", "data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (arg_value, doc, docDotNetType, docId, docVersion, transaction_timestamp())
        ON CONFLICT ON CONSTRAINT pkey_mt_doc_entity_id
        DO UPDATE SET "value" = arg_value, "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp()"
      PL/pgSQL function appread.mt_upsert_entity(character varying,jsonb,character varying,character varying,uuid) line 5 at SQL statement
          SchemaName: appread
          TableName: mt_doc_entity
          ConstraintName: mt_doc_entity_idx_value
          File: nbtinsert.c
          Line: 570
          Routine: _bt_check_unique
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.ObjectDisposedException: NpgsqlTransaction
         at Npgsql.NpgsqlTransaction.CheckDisposed()
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'NpgsqlConnection'.
         at Npgsql.NpgsqlConnection.Open(Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlConnection.OpenAsync(CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.EnsureConnectedAsync(CancellationToken token)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.BeginTransactionAsync(CancellationToken token)
         at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.tryApplyTombstoneEvents(CancellationToken token)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'HTTP: POST app/new'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Marten.Exceptions.DocumentAlreadyExistsException: Document already exists Entity: 1e3c6edd-02d0-410f-9cba-2c5118d7d089
       ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "mt_doc_entity_idx_value"
      
      DETAIL: Key (value)=(Test) already exists.
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|221_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
        Exception data:
          Severity: ERROR
          SqlState: 23505
          MessageText: duplicate key value violates unique constraint "mt_doc_entity_idx_value"
          Detail: Key (value)=(Test) already exists.
          Where: SQL statement "INSERT INTO appread.mt_doc_entity ("value", "data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (arg_value, doc, docDotNetType, docId, docVersion, transaction_timestamp())
        ON CONFLICT ON CONSTRAINT pkey_mt_doc_entity_id
        DO UPDATE SET "value" = arg_value, "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp()"
      PL/pgSQL function appread.mt_upsert_entity(character varying,jsonb,character varying,character varying,uuid) line 5 at SQL statement
          SchemaName: appread
          TableName: mt_doc_entity
          ConstraintName: mt_doc_entity_idx_value
          File: nbtinsert.c
          Line: 570
          Routine: _bt_check_unique
         --- End of inner exception stack trace ---
         at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
         at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
         at Program.<>c.<<<Main>$>b__0_4>d.MoveNext() in /xyz/Program.cs:line 59
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST https://localhost:5051/app/new - 0 - 500 - text/plain;+charset=utf-8 67.5319ms
```

Right after, Marten will start spamming the following in the console:
```sh
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      High Water agent is stale at 1
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      High Water agent is stale after threshold of 3 seconds, skipping gap to events marked after 01/01/2023 20:12:59 +00:00
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Daemon projection high water detection skipping a gap in event sequence, determined that the 'safe harbor' sequence is at (null)
```

It is expect that the exception `Npgsql.PostgresException` and `Marten.Exceptions.DocumentAlreadyExistsException` to be thrown, but the `System.ObjectDisposedException` being thrown at `Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync` and `Marten.Internal.Sessions.DocumentSessionBase.tryApplyTombstoneEvents`, coupled with the console spamming of `'safe harbor' sequence is at (null)` seems problematic.

Is all this expected behaviour? It seems like it's failing to do a rollback and tombstoning and event, and because of that starts spamming the console.

**Comment by jeremydmiller** [comment]
@jay-zahiri I tried to reproduce this today **outside** of a ASP.Net Core and it behaves exactly as it should.

I'm pointing at the Minimal API mechanics. This code:

```csharp
		endpoints.MapPost("app/new", async (IDocumentSession documentSession) => {
			var @event = new NewEntityAdded(
				Guid.NewGuid().ToString(),
				"Test"
			);

			documentSession.Events.StartStream<Entity>(
				@event.Id,
				@event
			);

			await documentSession.SaveChangesAsync();

			return Results.Created(@event.Id, null);
		});
```

Is very likely pulling the "Scoped" `IDocumentSession` directly out of the root IoC container (which is legal according to their rules about IoC behavioral compliance) instead of using a scoped container per request like MVC Core would. The behavior you're seeing is what happens when you try to reuse an `IDocumentSession` that's been disposed -- and the sessions dispose their connections in the face of Npgsql exceptions.

To prove this, either move your code to an MVC controller or inject `IDocumentStore` instead and create a session w/ `using var session = store.LightweightSession();`

But at this moment, **I do not believe this is a problem in Marten itself**. We *could* do something with documentation here to warn folks about Minimal API.
