### ISSUE TITLE
Allow LINQ Where - where property of object is not used

### ISSUE THREAD

**Issue by ncwilliams** [JasperFx/marten#251]
I am attempting to use Marten with a specification pattern that my applications currently use. The specification interface uses the following interface:

    public interface ISpecification<T>
    {
        bool IsSatisfiedBy(T entity);
        
        ISpecification<T> And(ISpecification<T> other);
        ISpecification<T> And(Expression<Func<T, bool>> expression);

        ISpecification<T> AndNot(ISpecification<T> other);
        ISpecification<T> AndNot(Expression<Func<T, bool>> expression);

        ISpecification<T> Or(ISpecification<T> other);
        ISpecification<T> Or(Expression<Func<T, bool>> expression);

        ISpecification<T> Not();

        ISpecification<T> OrderBy<TProperty>(Expression<Func<T, TProperty>> property);
        ISpecification<T> OrderByDescending<TProperty>(Expression<Func<T, TProperty>> property);
        ISpecification<T> Take(int amount);
        ISpecification<T> Skip(int amount);
    }

To build a specification the following is used:

    var spec = Specification<Entity>.All()
                               .And(x => x.Id == "something")
                               .And(x => x.Prop == "somthing-else");

The implementation of `All()` is like this:

    public static ISpecification<T> All()
    {
        return Where(x => true);
    }

For use with Marten the specification is converted into `Expression<Func<TEntity,bool>>` and used in a query like this:

    var expression = Specification<T>.ToExpression(specification);
    var queryableResults = Session.Query<T>().Where(expression);

The usage of `All()` causes the following exception to be thrown:

    System.NotSupportedException: Marten does not (yet) support this Linq query type
       at Marten.Linq.MartenExpressionParser.ParseWhereFragment(IDocumentMapping mapping, Expression expression)
          at Marten.Linq.DocumentQuery.buildWhereClause()
          at Marten.Linq.DocumentQuery.ConfigureCommand[T](IDocumentSchema schema, IDocumentStorage documentStorage, NpgsqlCommand command)
          at Marten.Linq.DocumentQuery.ConfigureCommand[T](IDocumentSchema schema, NpgsqlCommand command)
          at Marten.Linq.MartenQueryExecutor.BuildCommand[T](QueryModel queryModel, ISelector`1& selector)
          at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
          at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
          at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
          at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
          at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
          at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
          at Remotion.Linq.QueryableBase`1.GetEnumerator()
          at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
          at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

It would be great if Marten could support expressions which just return a Boolean. Is this use case acceptable, or should I look at changing how my specifications work?

I'm happy to look at making this change myself if it is something that would be acceptable when working.

**Comment by jeremydmiller** [comment]
"It would be great if Marten could support expressions which just return a Boolean" -- yeah, it's really not that simple. Marten's Linq support never actually executes those methods, and you can't get away with doing anything that general. You have to be able to parse and convert any method encountered in the Expression into a Sql statement.

Here's a blog post on extending the Linq support to custom methods: http://jeremydmiller.com/2016/03/08/an-example-of-the-openclosed-principle-in-action/

**Comment by schotime** [comment]
@ncwilliams Have you tried using the PredicateBuilder listed here. 
http://www.c-sharpcorner.com/UploadFile/c42694/dynamic-query-in-linq-using-predicate-builder/

It will allow you to start of with a true and then chain where statements to give you a statement that can be passed into Where(). It supports IQueryable.

**Comment by jeremydmiller** [comment]
@ncwilliams Hey, with @schotime 's workaround up there, I'm going to close this one as a "won't fix" thing just to clean off the issue list.
