### ISSUE TITLE
Code generations fails when duplicating a NodaTime property

### ISSUE THREAD

**Issue by ggmueller** [JasperFx/marten#2547]
Querying for a document having an `NodaTime.Instant` property fails with an Exception

````
System.InvalidOperationException : Compilation failures!

CS0234: The type or namespace name 'Instant' does not exist in the namespace 'Marten.NodaTime' (are you missing an assembly reference?)
CS1503: Argument 1: cannot convert from 'NodaTime.Instant?' to 'Marten.NodaTime.Instant?'
CS0234: The type or namespace name 'Instant' does not exist in the namespace 'Marten.NodaTime' (are you missing an assembly reference?)
CS1503: Argument 1: cannot convert from 'NodaTime.Instant?' to 'Marten.NodaTime.Instant?'

   at LamarCompiler.AssemblyGenerator.Generate(String code)
   at LamarCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at LamarCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
   at Marten.Internal.ProviderGraph.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFinder`1.Find(QuerySession session)
   at Marten.Internal.Sessions.QuerySession.StorageFor(Type documentType)
   at Marten.Linq.Parsing.LinqHandlerBuilder..ctor(MartenLinqQueryProvider provider, IMartenSession session, Expression expression, ResultOperatorBase additionalOperator, Boolean forCompiled)
   at Marten.Internal.CompiledQueries.QueryCompiler.BuildDatabaseCommand[TDoc,TOut](QuerySession session, ICompiledQuery`2 queryTemplate, QueryStatistics statistics, NpgsqlCommand& command)
   at Marten.Internal.CompiledQueries.QueryCompiler.BuildPlan[TDoc,TOut](QuerySession session, ICompiledQuery`2 query, StoreOptions storeOptions)
   at Marten.CompiledQueryCollection.GetCompiledQuerySourceFor[TDoc,TOut](ICompiledQuery`2 query, QuerySession session)
   at Marten.DocumentStore.GetCompiledQuerySourceFor[TDoc,TOut](ICompiledQuery`2 query, QuerySession session)
   at Marten.Internal.Sessions.QuerySession.QueryAsync[TDoc,TOut](ICompiledQuery`2 query, CancellationToken token)
   at Asf.Infrastructure.BaseAggregateRootRepository`2.ResultOf(ICompiledListQuery`1 query) in /home/georg/dev/asf/Asf/Infrastructure/BaseAggregateRootRepository.cs:line 38
   at Asf.Events.InvitationRepository.ByEventAndUser(EventRef event, EmployeeRef employee) in /home/georg/dev/asf/Asf/Events/InvitationRepository.cs:line 20
   at Asf.Events.InvitationHandler.CancelOpenInvitations(EventRef event, EmployeeRef attendee) in /home/georg/dev/asf/Asf/Events/InvitationHandler.cs:line 159
   at Asf.Events.InvitationHandler.Handle(AttendeeAddedEvent notification, CancellationToken cancellationToken) in /home/georg/dev/asf/Asf/Events/InvitationHandler.cs:line 53
   at MediatR.NotificationPublishers.ForeachAwaitPublisher.Publish(IEnumerable`1 handlerExecutors, INotification notification, CancellationToken cancellationToken)
   at Asf.Infrastructure.UnitOfWork.PublishEvents() in /home/georg/dev/asf/Asf/Infrastructure/UnitOfWork.cs:line 150
   at Asf.Infrastructure.UnitOfWork.Commit(Boolean publishEvents) in /home/georg/dev/asf/Asf/Infrastructure/UnitOfWork.cs:line 109
   at Asf.Tests.TestInfrastructure.IntegrationTestExtensions.Commit(IScopedTestFixture scopedTestFixture) in /home/georg/dev/asf/Asf.Tests/TestInfrastructure/IntegrationTestUtilities.cs:line 37
   at Asf.Tests.IntegrationTests.Events.EventTests.AttendEmployee_EmployeeNotAttending_Attends() in /home/georg/dev/asf/Asf.Tests/IntegrationTests/Events/EventTests.cs:line 85
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```` 

Generated code (shortened to the compilation error)

```csharp
// <auto-generated/>
#pragma warning disable
using Marten.Internal;
using Marten.Internal.Storage;
using Marten.Schema;
using Marten.Schema.Arguments;
using Asf.Events;
using Npgsql;
using System;
using System.Collections.Generic;
using Weasel.Core;
using Weasel.Postgresql;

namespace Marten.Generated.DocumentStorage
{
    // START: InvitationDataBulkLoader1147638260
    public class InvitationDataBulkLoader1147638260 : Marten.Internal.CodeGeneration.BulkLoader<Asf.Events.InvitationData, long>
    {
        private readonly Marten.Internal.Storage.IDocumentStorage<Asf.Events.InvitationData, long> _storage;

        public InvitationDataBulkLoader1147638260(Marten.Internal.Storage.IDocumentStorage<Asf.Events.InvitationData, long> storage) : base(storage)
        {
            _storage = storage;
        }


        public const string MAIN_LOADER_SQL = "COPY public.mt_doc_invitationdata(\"employee_email_address_email\", \"event_id\", \"hashed_id\", \"send_after\", \"uid\", \"mt_dotnet_type\", \"id\", \"mt_version\", \"tenant_id\", \"data\") FROM STDIN BINARY";

        public const string TEMP_LOADER_SQL = "COPY mt_doc_invitationdata_temp(\"employee_email_address_email\", \"event_id\", \"hashed_id\", \"send_after\", \"uid\", \"mt_dotnet_type\", \"id\", \"mt_version\", \"tenant_id\", \"data\") FROM STDIN BINARY";

        public const string COPY_NEW_DOCUMENTS_SQL = "insert into public.mt_doc_invitationdata (\"id\", \"tenant_id\", \"data\", \"mt_version\", \"mt_dotnet_type\", \"hashed_id\", \"event_id\", \"uid\", \"employee_email_address_email\", \"send_after\", \"mt_deleted\", \"mt_deleted_at\", mt_last_modified) (select mt_doc_invitationdata_temp.\"id\", mt_doc_invitationdata_temp.\"tenant_id\", mt_doc_invitationdata_temp.\"data\", mt_doc_invitationdata_temp.\"mt_version\", mt_doc_invitationdata_temp.\"mt_dotnet_type\", mt_doc_invitationdata_temp.\"hashed_id\", mt_doc_invitationdata_temp.\"event_id\", mt_doc_invitationdata_temp.\"uid\", mt_doc_invitationdata_temp.\"employee_email_address_email\", mt_doc_invitationdata_temp.\"send_after\", mt_doc_invitationdata_temp.\"mt_deleted\", mt_doc_invitationdata_temp.\"mt_deleted_at\", transaction_timestamp() from mt_doc_invitationdata_temp left join public.mt_doc_invitationdata on mt_doc_invitationdata_temp.id = public.mt_doc_invitationdata.id where public.mt_doc_invitationdata.id is null)";

        public const string OVERWRITE_SQL = "update public.mt_doc_invitationdata target SET tenant_id = source.tenant_id, data = source.data, mt_version = source.mt_version, mt_dotnet_type = source.mt_dotnet_type, hashed_id = source.hashed_id, event_id = source.event_id, uid = source.uid, employee_email_address_email = source.employee_email_address_email, send_after = source.send_after, mt_deleted = source.mt_deleted, mt_deleted_at = source.mt_deleted_at, mt_last_modified = transaction_timestamp() FROM mt_doc_invitationdata_temp source WHERE source.id = target.id";

        public const string CREATE_TEMP_TABLE_FOR_COPYING_SQL = "create temporary table mt_doc_invitationdata_temp as select * from public.mt_doc_invitationdata limit 0";


        public override void LoadRow(Npgsql.NpgsqlBinaryImporter writer, Asf.Events.InvitationData document, Marten.Storage.Tenant tenant, Marten.ISerializer serializer)
        {
            writer.Write(document.Employee?.EmailAddress?.Email, NpgsqlTypes.NpgsqlDbType.Text);
            writer.Write(GetNullable<System.Int64>(document.Event?.Id), NpgsqlTypes.NpgsqlDbType.Bigint);
            writer.Write(document.HashedId, NpgsqlTypes.NpgsqlDbType.Text);
// Compilation fails here
            writer.Write(GetNullable<NodaTime.Instant>(document.SendAfter), NpgsqlTypes.NpgsqlDbType.TimestampTz);
            writer.Write(document.Uid, NpgsqlTypes.NpgsqlDbType.Text);
            writer.Write(document.GetType().FullName, NpgsqlTypes.NpgsqlDbType.Varchar);
            writer.Write(document.Id, NpgsqlTypes.NpgsqlDbType.Bigint);

            var version = Marten.Schema.Identity.CombGuidIdGeneration.NewGuid();
            writer.Write(version, NpgsqlTypes.NpgsqlDbType.Uuid);
            document.Version = version;
            writer.Write(tenant.TenantId, NpgsqlTypes.NpgsqlDbType.Varchar);
            writer.Write(serializer.ToJson(document), NpgsqlTypes.NpgsqlDbType.Jsonb);
        }


        public override async System.Threading.Tasks.Task LoadRowAsync(Npgsql.NpgsqlBinaryImporter writer, Asf.Events.InvitationData document, Marten.Storage.Tenant tenant, Marten.ISerializer serializer, System.Threading.CancellationToken cancellation)
        {
            await writer.WriteAsync(document.Employee?.EmailAddress?.Email, NpgsqlTypes.NpgsqlDbType.Text, cancellation);
            await writer.WriteAsync(GetNullable<System.Int64>(document.Event?.Id), NpgsqlTypes.NpgsqlDbType.Bigint, cancellation);
            await writer.WriteAsync(document.HashedId, NpgsqlTypes.NpgsqlDbType.Text, cancellation);
// Compilation fails here
            await writer.WriteAsync(GetNullable<NodaTime.Instant>(document.SendAfter), NpgsqlTypes.NpgsqlDbType.TimestampTz, cancellation);
            await writer.WriteAsync(document.Uid, NpgsqlTypes.NpgsqlDbType.Text, cancellation);
            await writer.WriteAsync(document.GetType().FullName, NpgsqlTypes.NpgsqlDbType.Varchar, cancellation);
            await writer.WriteAsync(document.Id, NpgsqlTypes.NpgsqlDbType.Bigint, cancellation);

            var version = Marten.Schema.Identity.CombGuidIdGeneration.NewGuid();
            writer.Write(version, NpgsqlTypes.NpgsqlDbType.Uuid);
            document.Version = version;
            await writer.WriteAsync(tenant.TenantId, NpgsqlTypes.NpgsqlDbType.Varchar, cancellation);
            await writer.WriteAsync(serializer.ToJson(document), NpgsqlTypes.NpgsqlDbType.Jsonb, cancellation);
        }


        public override string MainLoaderSql()
        {
            return MAIN_LOADER_SQL;
        }


        public override string TempLoaderSql()
        {
            return TEMP_LOADER_SQL;
        }


        public override string CreateTempTableForCopying()
        {
            return CREATE_TEMP_TABLE_FOR_COPYING_SQL;
        }


        public override string CopyNewDocumentsFromTempTable()
        {
            return COPY_NEW_DOCUMENTS_SQL;
        }


        public override string OverwriteDuplicatesFromTempTable()
        {
            return OVERWRITE_SQL;
        }

    }

    // END: InvitationDataBulkLoader1147638260
}

```

The problem seems to be the reference to `NodaTime.Instant`, which in this case would reference to ` Marten.NodaTime.Instant` instead of `global::NodaTime.Instant`. Adding the `global::` to the code would allow it to compile (at least manually)

Marten Version: 5.11.0
Marten.NodaTime Version: 5.11.0

**Comment by ggmueller** [comment]
My initial description was not correct. This happens when the `NodaTime.Instant` property is duplicated as a column
