### ISSUE TITLE
DeleteWhere fails with multiple critera

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#257]
```
session.DeleteWhere<Comment>(x => x.Id == id);
session.DeleteWhere<Comment>(x => x.MemberId == CurrentMember.Id);
```

Both of these use `int` and work individually

`session.DeleteWhere<Comment>(x => x.Id == id && x.MemberId == CurrentMember.Id);`

When combined together for multiple criteria, it fails.

> System.NotSupportedException: Specified method is not supported.
 at Marten.Linq.ExpressionExtensions.Value(Expression expression)
 at Marten.Linq.MartenExpressionParser.buildSimpleWhereClause(IDocumentMapping mapping, BinaryExpression binary)
 at Marten.Linq.MartenExpressionParser.WhereClauseVisitor.VisitBinary(BinaryExpression binary)
 at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
 at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
 at Marten.Linq.MartenExpressionParser.WhereClauseVisitor.VisitBinary(BinaryExpression binary)
 at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
 at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
 at Marten.Linq.MartenExpressionParser.ParseWhereFragment(IDocumentMapping mapping, Expression expression)
 at Marten.Services.Delete.Configure(MartenExpressionParser parser, IDocumentStorage storage, IDocumentMapping mapping, UpdateBatch batch)
 at Marten.Services.UnitOfWork.<>c__DisplayClass23_3.<GetChanges>b__9(Delete id)
 at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
 at Marten.Services.UnitOfWork.<>c__DisplayClass23_0.<GetChanges>b__8(Type type)
 at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
 at Marten.Services.UnitOfWork.GetChanges(UpdateBatch batch)
 at Marten.Services.UnitOfWork.buildChangeSet(UpdateBatch batch)
 at Marten.Services.UnitOfWork.<ApplyChangesAsync>d__22.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Marten.DocumentSession.<SaveChangesAsync>d__19.MoveNext()

**Comment by nieve** [comment]
Yo, I'll be happy to look into it.

**Comment by jeremydmiller** [comment]
@nieve Go for it. I'm surprised that that's any kind of issue.

**Comment by nieve** [comment]
@jeremydmiller ha, You should have a peak at gitter. It's an odd one.

**Comment by jeremydmiller** [comment]
@nieve I'm gonna deal with this one this morning, then push a new nuget. I'll do what we discussed on Gitter about using a MartenQueryable underneath the covers

**Comment by nieve** [comment]
:+1:
