### ISSUE TITLE
Cannot store POCO document objects from a dynamically loaded assembly

### ISSUE THREAD

**Issue by Lele0037** [JasperFx/marten#2576]
I have the following situation: I have two projects in the same solution, let's call them Project A (a blazor web server) and Project B (a satellite module, which is a simple Razor Library where I have other pages, components, etc.).
Now, Project A is where the Marten service is instantiated: that's where I define the connection string, schema name etc., 

```
namespace ProjectA
{
    //...
            builder.Services.AddMarten(options =>
            {
                options.Connection("<my connection string>");
                options.AutoCreateSchemaObjects = AutoCreate.All;
            });
    //...
}
```

this way I just have to inject the IDocumentStore interface throughout the pages in order to access the database. Project B gets its IDocumentStore from Project A (though Project A does not know about Project B:  Project B's assembly is loaded dynamically at runtime in Project A).
Now, let's say I have a POCO object in Project B:

```
namespace ProjectB
{
    public class Test
    {
        public Guid Id { get; set; }

        // other properties
    }
}
```

and I want to save It in my database through the IDocumentStore injected from Project A. When I try to execute this save method,

```
namespace ProjectB
{
    //...
    private async Task SaveDoc ()
    {
        var obj = new Test();
        await using (var session = _store.LightweightSession())
        {
            session.Store(obj);

            session.SaveChanges();
        }
    }
}
```

it gives me the following error when `session.Store(obj)` tries to execute:

```
[2023-05-03T07:35:44.564Z] Error: System.IO.FileNotFoundException: Could not load file or assembly 'ProjectB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The specified module could not be found.
File name: 'ProjectB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'ProjectB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The specified module could not be found.
File name: 'ProjectB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.<InternalLoad>g____PInvoke|47_0(NativeAssemblyNameParts* pAssemblyNameParts, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Int32 throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at LamarCompiler.CustomAssemblyLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at LamarCodeGeneration.GeneratedAssembly.AttachAssembly(Assembly assembly)
   at LamarCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at LamarCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
   at Marten.Internal.ProviderGraph.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
   at Marten.Internal.Sessions.DocumentSessionBase.store[T](IEnumerable`1 entities)
   at Marten.Internal.Sessions.DocumentSessionBase.Store[T](T[] entities)
   at <mypath>\Component1.razor:line 18
   at <mypath>\Component1.razor:line 21
   at <mypath>\Component1.razor:line 10
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

I guess I know what's going on: Marten in ProjectA tries to pre-build the objects needed for the database, but, due to the fact that ProjectB is not referenced in ProjectA explicitly, it fails to find the object `Test` at runtime, thus giving me the error above.
I have already tried using parameters such as `GeneratedCodeMode = TypeLoadMode.Dynamic` or the other ones, but I keep getting the same error. I know it is due to how Marten works, but is there any workaround I can use?
Thank you very much.

**Comment by jeremydmiller** [comment]
@Lele0037 That's failing up above because the ProjectB assembly cannot be found in your application when you run. Very easy fix is to make the direct reference to ProjectB from your application and go on with your day. Otherwise, I guess you could try to manually load the ProjectB assembly in your application *before* using Marten so that Assembly.Load() can function correctly.

**Comment by Lele0037** [comment]
Hi @jeremydmiller , thank you for your response. Unfortunately, having ProjectB referenced in ProjectA is kind of a deal breaker: the whole purpose of this project is having ProjectA so that it does not know in advance which modules it will use (all the assemblies are loaded dynamically from a directory, so ProjectA cannot reference ProjectB).
I also tried adding an assembly pre-loading phase in Program.cs, like this:
```
var assembly = Assembly.LoadFrom("<path to dll>\\ProjectB.dll");
assembly.CreateInstance("ProjectB");
```

but it throws another error:

```
[2023-05-03T12:49:46.503Z] Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: ParameterExpression of type 'ProjectB.Test' cannot be used for delegate parameter of type 'ProjectB.Test'

   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at Baseline.Expressions.LambdaBuilder.SetProperty[TTarget,TProperty](PropertyInfo property)
   at Baseline.Expressions.LambdaBuilder.Setter[TTarget,TMember](MemberInfo member)
   at Marten.Internal.Storage.DocumentStorage`2..ctor(StorageStyle storageStyle, DocumentMapping document)
   at Marten.Internal.Storage.QueryOnlyDocumentStorage`2..ctor(DocumentMapping document)
   at Marten.Generated.DocumentStorage.QueryOnlyTestDocumentStorage1398299618..ctor(DocumentMapping document)
   at Marten.Generated.DocumentStorage.TestProvider1398299618..ctor(DocumentMapping mapping)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

   --- End of inner exception stack trace ---

   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Marten.Internal.CodeGeneration.DocumentProviderBuilder.BuildProvider[T]()
   at Marten.Internal.ProviderGraph.StorageFor[T]()
   at Marten.Internal.Sessions.QuerySession.StorageFor[T]()
   at Marten.Internal.Sessions.DocumentSessionBase.store[T](IEnumerable`1 entities)
   at Marten.Internal.Sessions.DocumentSessionBase.Store[T](T[] entities)
   at ProjectB.Component1.Save() in <my path>\Component1.razor:line 18
   at ProjectB.Component1.Save() in <my path>\Component1.razor:line 21
   at ProjectB.Component1.<BuildRenderTree>b__0_0() in <my path>\Component1.razor:line 10
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

```

It seems that it has been able to load the assembly, but the loaded one is not compatible with the one it should be using for creating the document.

**Comment by jeremydmiller** [comment]
You're in an older version, so the dependencies have changed underneath you. If you move up to Marten 6, I guess you could try a pull request to JasperFx.RuntimeCompiler's version of AttachAssembly() to try to find the assembly a different way than by name as it is today.

**Comment by Lele0037** [comment]
Hi again,
I finally made it work. I think I know what I was doing wrong: the assemblies were actually loaded twice by mistake. The first assembly load was taking place as above, in the `Assembly.LoadFrom("<path to dll>\\ProjectB.dll");` bit. However, in my Blazor project I was also loading the assemblies here:
```
        <Router AppAssembly="@typeof(App).Assembly" AdditionalAssemblies="_assemblies">
            <Found Context="routeData">
                <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
                <FocusOnNavigate RouteData="@routeData" Selector="h1" />
            </Found>
            <NotFound>
                <PageTitle>Not found</PageTitle>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p role="alert">Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>

@code {
    private List<Assembly> _assemblies = new();

    protected override void OnInitialized()
    {
        _assemblies = // here the assemblies where loaded for the second time by mistake, instead of being fetched from memory
        base.OnInitialized();
    }
}
```

This was causing the error I reported in my second response. Now everything works fine.
Thank you very much for your help.
