### ISSUE TITLE
DocumentStore fails upon applying schema updates in parallel

### ISSUE THREAD

**Issue by SeanKilleen** [JasperFx/marten#2577]
Hi all,

Very much aware that I might be doing something silly here but I cannot figure out what and it seems it might be an issue so I'm raising it here.

## Background

I am building a sample project for SpecFlow + TestContainers + Marten, which I plan to share and walk through with the larger community.

As part of this, I am using the above code in my `[BeforeScenario]` method:

```cs
    [BeforeScenario]
    public void BeforeScenario()
    {
        _documentStore = DocumentStore.For(_ =>
        {
            _.Connection($"host=localhost;database={TestContainerSupport.DatabaseName};password={TestContainerSupport.Password};username={TestContainerSupport.Username};Include Error Detail=true");

            _.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;

            _.Events.AddEventType<AccountCreated>();
            _.Events.AddEventType<BucketCreated>();
            _.Events.AddEventType<PoolFundsTransferredIntoBucket>();
        });
        
        _objectContainer.RegisterInstanceAs(_documentStore);
    }
```
And in the after scenario teardown:

```cs
    [AfterScenario]
    public async Task AfterScenario()
    {
        await _documentStore.Advanced.Clean.DeleteAllEventDataAsync();
    }
```

This works great, until I have more than one feature file, at which point things are run in parallel.

## Expected Behavior

Because I have set `AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate`, I expect that I will be able to invoke the document store without it attempting to auto-create schema objects that are already there.

## Actual Behavior

On some tests (depending on timing), I see an error `error: DDL Execution for 'All Configured Changes' Failed!` with a deeper `Npgsql.PostgresException` of `23505: duplicate key value violates unique constraint "pg_proc_proname_args_nsp_index"` with `DETAIL: Key (proname, proargtypes, pronamespace)=(mt_immutable_timestamp, 25, 2200) already exists.`

<details><summary>Full Stack trace output</summary>

```
Marten.Exceptions.MartenSchemaException
DDL Execution for 'All Configured Changes' Failed!

CREATE OR REPLACE FUNCTION public.mt_immutable_timestamp(value text) RETURNS timestamp without time zone LANGUAGE sql IMMUTABLE AS
$function$
select value::timestamp

$function$;


CREATE OR REPLACE FUNCTION public.mt_immutable_timestamptz(value text) RETURNS timestamp with time zone LANGUAGE sql IMMUTABLE AS
$function$
select value::timestamptz

$function$;


CREATE OR REPLACE FUNCTION public.mt_grams_vector(text)
        RETURNS tsvector		
        LANGUAGE plpgsql
        IMMUTABLE STRICT
AS $function$
BEGIN
        RETURN (SELECT array_to_string(mt_grams_array($1), ' ')::tsvector);
END
$function$;


CREATE OR REPLACE FUNCTION public.mt_grams_query(text)
        RETURNS tsquery		
        LANGUAGE plpgsql
        IMMUTABLE STRICT
AS $function$
BEGIN
        RETURN (SELECT array_to_string(mt_grams_array($1), ' & ')::tsquery);
END
$function$;


CREATE OR REPLACE FUNCTION public.mt_grams_array(words text)
        RETURNS text[]		
        LANGUAGE plpgsql
        IMMUTABLE STRICT
AS $function$
        DECLARE result text[];
        DECLARE word text;
        DECLARE clean_word text;
        BEGIN
                FOREACH word IN ARRAY string_to_array(words, ' ')
                LOOP
                     clean_word = regexp_replace(word, '[^a-zA-Z0-9]+', '','g');
                     FOR i IN 1 .. length(clean_word)
                     LOOP
                         result := result || quote_literal(substr(lower(clean_word), i, 1));
                         result := result || quote_literal(substr(lower(clean_word), i, 2));
                         result := result || quote_literal(substr(lower(clean_word), i, 3));
                     END LOOP;
                END LOOP;

                RETURN ARRAY(SELECT DISTINCT e FROM unnest(result) AS a(e) ORDER BY e);
        END;
$function$;



   at Marten.StoreOptions.Weasel.Core.Migrations.IMigrationLogger.OnFailure(DbCommand command, Exception ex)
   at Weasel.Postgresql.PostgresqlMigrator.executeDelta(SchemaMigration migration, DbConnection conn, AutoCreate autoCreate, IMigrationLogger logger)
   at Weasel.Core.Migrator.ApplyAll(DbConnection conn, SchemaMigration migration, AutoCreate autoCreate, IMigrationLogger logger)
   at Weasel.Core.Migrations.DatabaseBase`1.executeMigration(ISchemaObject[] schemaObjects, CancellationToken token)
   at Weasel.Core.Migrations.DatabaseBase`1.executeMigration(ISchemaObject[] schemaObjects, CancellationToken token)
   at Weasel.Core.Migrations.DatabaseBase`1.generateOrUpdateFeature(Type featureType, IFeatureSchema feature, CancellationToken token)
   at Weasel.Core.Migrations.DatabaseBase`1.ensureStorageExists(IList`1 types, Type featureType, CancellationToken token)
   at Weasel.Core.Migrations.DatabaseBase`1.ensureStorageExists(IList`1 types, Type featureType, CancellationToken token)
   at Weasel.Core.Migrations.DatabaseBase`1.ensureStorageExists(IList`1 types, Type featureType, CancellationToken token)
   at Marten.Events.EventGraph.ProcessEventsAsync(DocumentSessionBase session, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
   at BucketsOfMoney.Domain.Manager.CreateAccount(String accountName) in D:\Repositories\bucketsofmoney\src\BucketsOfMoney.Domain\Manager.cs:line 23
   at BucketsOfMoney.Domain.Manager.CreateAccount(String accountName) in D:\Repositories\bucketsofmoney\src\BucketsOfMoney.Domain\Manager.cs:line 24
   at BucketsOfMoney.Domain.Tests.Steps.GivenACustomerAccountIsCreatedFor(String accountName) in D:\Repositories\bucketsofmoney\test\BucketsOfMoney.Domain.Tests\Steps.cs:line 34
   at TechTalk.SpecFlow.Bindings.SynchronousBindingDelegateInvoker.<>c__DisplayClass2_0.<<InvokeBindingDelegateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at TechTalk.SpecFlow.Bindings.AsyncHelpers.<>c__DisplayClass1_0`1.<<RunSync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at TechTalk.SpecFlow.Bindings.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop()
   at TechTalk.SpecFlow.Bindings.AsyncHelpers.RunSync[T](Func`1 task)
   at TechTalk.SpecFlow.Bindings.SynchronousBindingDelegateInvoker.InvokeBindingDelegateAsync(Delegate bindingDelegate, Object[] invokeArgs)
   at TechTalk.SpecFlow.Bindings.SynchronousBindingDelegateInvoker.InvokeDelegateSynchronously(Delegate bindingDelegate, Object[] invokeArgs)
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at BucketsOfMoney.Domain.Tests.BasicBucketDistributionFeature.ScenarioCleanup()
   at BucketsOfMoney.Domain.Tests.BasicBucketDistributionFeature.BasicBucketSplits() in D:\Repositories\bucketsofmoney\test\BucketsOfMoney.Domain.Tests\BucketDistribution.feature:line 13

Npgsql.PostgresException
23505: duplicate key value violates unique constraint "pg_proc_proname_args_nsp_index"

DETAIL: Key (proname, proargtypes, pronamespace)=(mt_immutable_timestamp, 25, 2200) already exists.
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Weasel.Postgresql.PostgresqlMigrator.executeDelta(SchemaMigration migration, DbConnection conn, AutoCreate autoCreate, IMigrationLogger logger)

Given a customer account is created for seankilleen@gmail.com
-> error: DDL Execution for 'All Configured Changes' Failed!

CREATE OR REPLACE FUNCTION public.mt_immutable_timestamp(value text) RETURNS timestamp without time zone LANGUAGE sql IMMUTABLE AS
$function$
select value::timestamp

$function$;


CREATE OR REPLACE FUNCTION public.mt_immutable_timestamptz(value text) RETURNS timestamp with time zone LANGUAGE sql IMMUTABLE AS
$function$
select value::timestamptz

$function$;


CREATE OR REPLACE FUNCTION public.mt_grams_vector(text)
        RETURNS tsvector		
        LANGUAGE plpgsql
        IMMUTABLE STRICT
AS $function$
BEGIN
        RETURN (SELECT array_to_string(mt_grams_array($1), ' ')::tsvector);
END
$function$;


CREATE OR REPLACE FUNCTION public.mt_grams_query(text)
        RETURNS tsquery		
        LANGUAGE plpgsql
        IMMUTABLE STRICT
AS $function$
BEGIN
        RETURN (SELECT array_to_string(mt_grams_array($1), ' & ')::tsquery);
END
$function$;


CREATE OR REPLACE FUNCTION public.mt_grams_array(words text)
        RETURNS text[]		
        LANGUAGE plpgsql
        IMMUTABLE STRICT
AS $function$
        DECLARE result text[];
        DECLARE word text;
        DECLARE clean_word text;
        BEGIN
                FOREACH word IN ARRAY string_to_array(words, ' ')
                LOOP
                     clean_word = regexp_replace(word, '[^a-zA-Z0-9]+', '','g');
                     FOR i IN 1 .. length(clean_word)
                     LOOP
                         result := result || quote_literal(substr(lower(clean_word), i, 1));
                         result := result || quote_literal(substr(lower(clean_word), i, 2));
                         result := result || quote_literal(substr(lower(clean_word), i, 3));
                     END LOOP;
                END LOOP;

                RETURN ARRAY(SELECT DISTINCT e FROM unnest(result) AS a(e) ORDER BY e);
        END;
$function$;


 (1.3s)

The output has reached the limit and was truncated.
To view the full output use 'Show Stack Trace in a new window' action.
```
</details>

Is my understanding of `AutoCreate.CreateOrUpdate` incorrect in this case?

Thanks!

**Comment by SeanKilleen** [comment]
OK, it sounds like this is an issue that can be expected based on how the existing Marten migrations are used, I've got to update my understanding/usage or figure out a workaround.

`CREATE OR REPLACE` doesn't prevent a race condition, which I'm seeing because I'm utilizing the `IDocumentStore` multiple times in parallel against a DB and so the `CREATE OR REPLACE` is still hitting a race condition.

So I think the options are (but am happy to be corrected if I'm missing something):

* Quickest/Dirtiest: Reduce parallel execution of tests (run things sequentially at the `Feature` level)
* More work on Marten side: introduce the concept of [advisory locks](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS) into schema changes -- essentially protecting people like me against myself 😆 
* Find some way to programmatically change to `AutoCreate.None` when schema has been created
* Find some way to re-use the `IDocumentStore` across all features, which will (presumably) create the schema once.

I've looked around but can't seem to find common usage advice in these scenarios; apologies if I missed it. Also happy to contribute any surfaced solution back to the docs.

**Comment by SeanKilleen** [comment]
This may also be one to take up with the SpecFlow team; my code fails when using the `specflow.xunit` package but not the `specflow.nunit` package, so it may be something to do with how SpecFlow is adapting the scenario for xUnit specifically.

**Comment by oskardudycz** [comment]
@SeanKilleen, is it also happening in Marten v6? We added some improvements around that.

**Comment by SeanKilleen** [comment]
> You'd have to move to using full Host set up in your automated tests, but that's my strong preference anyway

@jeremydmiller yeah, I can dig that. I was avoiding it for a bit just because I didn't need it and was testing things outside of controllers etc. but I don't mind doing it that way. I'll look into it.

@oskardudycz yep, still happening in v6 -- but only with SpecFlow + xUnit, never with SpecFlow + NUnit.  So I'm not ruling out the combination of this setup + `SpecFlow.xunit` as the culprit. 

I made the repo public in case you want to play around (though please note it's just for an experiment and I'm not holding myself to any kind of standard 😆 though feedback is always welcome): https://github.com/SeanKilleen/bucketsofmoney

**Comment by SeanKilleen** [comment]
I'm going to close this for now since I think I have a current viable workaround (SpecFlow + NUnit) and a future direction (moving to the Host model).
