### ISSUE TITLE
Transient database fault makes async daemon a zombie

### ISSUE THREAD

**Issue by invertedtomato** [JasperFx/marten#2578]
We're using 'Azure Database for PostgreSQL servers' for a database, and following [Azure's recommendations](https://learn.microsoft.com/en-us/azure/azure-sql/database/troubleshoot-common-connectivity-issues?view=azuresql) we have a retry policy to avoid transitive errors being fatal. We have had several production outages though where async projections ceased being build. Restarting the service resolved the issue.

On investigation we can see the issue starting with a database timeout causing the following exception to be logged. When this occurs async daemon stops doing anything. It goes full zombie.

```
Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|222_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken)
   at Marten.Events.Daemon.HotColdCoordinator.tryToAttainLockAndStartShards()
```

Here is our Marten configuration block. Please note the `RetryPolicy(...)`
```
    services.AddMarten(options =>
            {
               // ...
                options.RetryPolicy(DefaultRetryPolicy.Times(3)); // <====== retry policy here
                // ..
            })
            .ApplyAllDatabaseChangesOnStartup()
            .InitializeWith();
```

I noted that the `DefaultRetryPolicy` uses `Npgsql.NpgsqlException.IsTransient` to determine if an exception should be retried. Furthermore [Npgsql lists timeouts as an example of a transient exception](https://www.npgsql.org/doc/api/Npgsql.NpgsqlException.html).

Reading `Marten.Events.Daemon.HotColdCoordinator.tryToAttainLockAndStartShards` does not seem to show the retry policy having been wired in here. Although in the context of a polling daemon, it seems that a retry policy is not the best logic. I expect a daemon to either retry indefinitely (logging any errors), or stop the process so that it can be restarted. In this scenario, retrying indefinitely appears to be the better approach. What are your thoughts?

**Comment by invertedtomato** [comment]
I've revised my message above with new findings. TLDR: It seems the retry policy isn't wired into `tryToAttainLockAndStartShards`. But even if it was, a daemon should really retry forever, or terminate the process so it can be restarted - not go zombie. Thoughts?

**Comment by invertedtomato** [comment]
After digging I found the issue was resolved in https://github.com/invertedtomato/marten/commit/4947a326ea54cd018ee79eafd7c4c9d5f8ee0826
