### ISSUE TITLE
`SingleStreamProjection` throws unexpected `InvalidProjectionException`

### ISSUE THREAD

**Issue by lofbacke** [JasperFx/marten#2627]
Hello, and apologies in advance for the holiday weekend bug report.

I am using Marten 6.0.2 with Wolverine 1.1.2. I recently set up some handlers that create and update a `User` domain aggregate. These operations work beautifully. However, I am now trying to implement a `UserDetails` read model using a `SingleStreamProjection` and I can't get it to work at all. Here's a look at my implementation, with some properties and events omitted for brevity:

```cs
public sealed class UserDetailsProjection : SingleStreamProjection<UserDetails>
{
    public UserDetails Create(RootUserCreated e) =>
        new UserDetails
        {
            Id = e.UserId,
            EmailAddress = e.EmailAddress,
            IsVerified = true
        };

    public async Task<UserDetails> Create(UserInvited e, IQuerySession session)
    {
        var invitedByUser = await session.LoadAsync<UserDetails>(e.InvitedByUserId);

        return new UserDetails
        {
            Id = e.UserId,
            EmailAddress = e.EmailAddress,
            InvitedByEmailAddress = invitedByUser?.EmailAddress,
            InvitedByUserId = e.InvitedByUserId
        };
    }

    public void Apply(object @event, UserDetails userDetails)
    {
        switch (@event)
        {
            case InvitationAccepted e:
                userDetails.IsVerified = true;
                break;
            case UserDisabled:
                userDetails.IsDisabled = true;
                break;
            case UserEnabled:
                userDetails.IsDisabled = false;
                break;
            //more events here
        }
    }
}


public sealed class UserDetails
{
    public Guid Id { get; set; }
    public string EmailAddress { get; set; } = null!;
    public string? InvitedByEmailAddress { get; set; }
    public Guid? InvitedByUserId { get; set; }
    public bool IsDisabled { get; set; }
    public bool IsVerified { get; set; }
    //more properties here
}
```

And here is how I am registering the projection with Marten in `Program.cs`:
```cs
builder.Services.AddMarten(options =>
    {
        //more options code here
        options.Projections.Snapshot<UserDetailsProjection>(SnapshotLifecycle.Inline);
    })
        .AddAsyncDaemon(DaemonMode.Solo)
        .IntegrateWithWolverine()
        .EventForwardingToWolverine()
        .UseLightweightSessions();
```

When I try to start the application, Marten throws the following exception:
```
Marten.Exceptions.InvalidProjectionException: Projection Marten.Events.Aggregation.SingleStreamProjection<Long.Namespace.Here.UserDetailsProjection> has validation errors:
Apply(object, UserDetails)
 - Parameter of type 'Long.Namespace.Here.UserDetails' is not supported. Valid options are System.Threading.CancellationToken, Marten.IQuerySession, Long.Namespace.Here.UserDetailsProjection, object, Marten.Events.IEvent, Marten.Events.IEvent<object>
Create(RootUserCreated) : UserDetails
 - Return type 'Long.Namespace.Here.UserDetails' is invalid. The valid options are System.Threading.CancellationToken, Marten.IQuerySession
Create(UserInvited, IQuerySession) : Task<Long.Namespace.Here.UserDetails>
 - Return type 'System.Threading.Tasks.Task<Long.Namespace.Here.UserDetails>' is invalid. The valid options are System.Threading.CancellationToken, Marten.IQuerySession

   at Marten.Events.Aggregation.GeneratedAggregateProjectionBase`1.AssembleAndAssertValidity()
   at Marten.Events.Projections.ProjectionOptions.singleStreamProjection[T](ProjectionLifecycle lifecycle, Action`1 asyncConfiguration)
   at Marten.Events.Projections.ProjectionOptions.Snapshot[T](SnapshotLifecycle lifecycle, Action`1 asyncConfiguration)
   at Program.<>c__DisplayClass0_0.<<Main>$>b__1(StoreOptions options) in C:\project\directory\here\Program.cs:line 105
   at Marten.MartenServiceCollectionExtensions.AddMarten(IServiceCollection services, Action`1 configure)
   at Program.<Main>$(String[] args) in C:\project\directory\here\Program.cs:line 95
```

My implementation seems to follow what's in the docs, but I wouldn't be surprised if I've made a newbie mistake and overlooked something obvious.

Thanks in advance!

**Comment by lofbacke** [comment]
I figured it out. My registration was incorrect. It needed to be:
```cs
options.Projections.Add<UserDetailsProjection>(ProjectionLifecycle.Inline);
```

**Comment by oskardudycz** [comment]
@lofbacke, thank you for the follow-up 👍
