### ISSUE TITLE
SingleOrDefault / FirstOrDefault fails for compiled queries

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#265]
Given the following query:

```csharp
public class VotesByUserOnPhotoQuery : ICompiledQuery<PhotoMemberCommentVotes>
{
    public int PhotoId { get; set; }

    public int MemberId { get; set; }

    public Expression<Func<IQueryable<PhotoMemberCommentVotes>, PhotoMemberCommentVotes>> QueryIs()
    {
        return query => query.Where(x => x.MemberId == MemberId)
                                .Where(x => x.PhotoId == PhotoId)
                                .SingleOrDefault();

    }
}
```

This currently throws an exception when no result is returned rather than returning null.

```
System.InvalidOperationException: Sequence contains no elements
 at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
 at Marten.Linq.CompiledQueryExecutor.<ExecuteQueryAsync>d__5`2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 at HyRes.Web.Modules.Actions.CommentModule.<<-ctor>b__0_0>d.MoveNext() in E:\github\HyRes\src\HyRes.Web\Modules\Actions\CommentModule.cs:line 27
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Nancy.Routing.DefaultRouteInvoker.<Invoke>d__b.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Nancy.Routing.DefaultRequestDispatcher.<Dispatch>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Nancy.NancyEngine.<InvokeRequestLifeCycle>d__9.MoveNext()
 --- End of inner exception stack trace ---
 at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

**Comment by nieve** [comment]
I can pick this up tomorrow, unless someone'll beat me to it.

**Comment by jeremydmiller** [comment]
Actually, I wanna take this one tomorrow. Got a refactoring I wanna do as part of this, plus hitting compiled query within the batch query support

**Comment by nieve** [comment]
cool, np.
