### ISSUE TITLE
Postgres authentication failure leads to null ref exception

### ISSUE THREAD

**Issue by arildboifot** [JasperFx/marten#2670]
Minimal repro:

```c#
var store = DocumentStore.For("****");
var session = store.LightweightSession();
var result = await session.QueryAsync<int>("select count(*) from mt_doc_foo");
Console.WriteLine($"Count: {result.First()}");
```

This leads to the following stack trace:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Marten.Exceptions.MartenCommandException..ctor(NpgsqlCommand command, Exception innerException)
   at Marten.Exceptions.MartenExceptionTransformer.<>c.<.cctor>b__1_2(NpgsqlException e)
   at JasperFx.Core.Exceptions.ExceptionTransform`1.TryTransform(Exception original, Exception& transformed)
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Internal.Sessions.QuerySession.QueryAsync[T](String sql, CancellationToken token, Object[] parameters)
   at Program.<Main>$(String[] args) in /Users/arild/dev/gamefraym/MartenDOTest/ConsoleApp1/Program.cs:line 34
   at Program.<Main>(String[] args)
```

**Comment by GKotfis** [comment]
The same happening when DB is inaccessible because of network problems etc. At first, I thought that something was wrong with my document schema. It turns out that docker with Postgres was not running.

**Comment by oskardudycz** [comment]
It should be fixed in [6.1 release](https://github.com/JasperFx/marten/milestone/93) by #2689.
