### ISSUE TITLE
Marten /Npsql transaction failure when rebuilding more than one projection at once

### ISSUE THREAD

**Issue by Richard87** [JasperFx/marten#2683]
Any advice on solving this issue when executing more than one transaction at once?

```
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      select d.data, d.type, d.mt_dotnet_type, d.seq_id, d.id, d.stream_id, d.version, d.timestamp, d.tenant_id, d.correlation_id, d.causation_id, d.headers, d.is_archived, s.type as stream_type from public.mt_events as d inner join public.mt_streams as s on d.stream_id = s.id where d.seq_id > :p0 and d.seq_id <= :p1 and d.type = ANY(:p2) and d.is_archived = FALSE order by d.seq_id
        p0: 0
        p1: 49
        p2: System.String[]
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.CancellationToken.ThrowIfCancellationRequested()
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
                                                           
```

**Comment by Richard87** [comment]
More logs :) 

In the end, the console was hanging, I'm expecting a timeout eventually...

```
dotnet run -- projections --rebuild
Building...
Searching 'JasperFx.CodeGeneration.Commands, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'Weasel.CommandLine, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'Marten.CommandLine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'Wolverine, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'Wolverine.Http.FluentValidation, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' for commands

info: Wolverine.Runtime.WolverineRuntime[0]
      Exporting Open Telemetry metrics from Wolverine with name Wolverine:Web, version 1.6.0.0

Overwriting the minimum log level to Error

── IDocumentStore ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      delete from public.mt_doc_deadletterevent as d where d.data ->> 'ProjectionName' = :p0;truncate table public.mt_doc_dogmemberview CASCADE;delete from public.mt_event_progression where name = :p1;
        p0: DogMemberView
        p1: DogMemberView:All
      Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to read/write dependencies among transactions
      
      DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
        Exception data:
          Severity: ERROR
          SqlState: 40001
          MessageText: could not serialize access due to read/write dependencies among transactions
          Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
          Hint: The transaction might succeed if retried.
          File: predicate.c
          Line: 4815
          Routine: OnConflict_CheckForSerializationFailure
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      delete from public.mt_doc_deadletterevent as d where d.data ->> 'ProjectionName' = :p0;truncate table public.mt_doc_contactlistview CASCADE;delete from public.mt_event_progression where name = :p1;
        p0: ContactListView
        p1: ContactListView:All
      Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to read/write dependencies among transactions
      
      DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
        Exception data:
          Severity: ERROR
          SqlState: 40001
          MessageText: could not serialize access due to read/write dependencies among transactions
          Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
          Hint: The transaction might succeed if retried.
          File: predicate.c
          Line: 4815
          Routine: OnConflict_CheckForSerializationFailure
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.ObjectDisposedException: NpgsqlTransaction
         at Npgsql.NpgsqlTransaction.CheckDisposed()
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.ObjectDisposedException: NpgsqlTransaction
         at Npgsql.NpgsqlTransaction.CheckDisposed()
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
                                                               
BreederView:All ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ⣷
    DogView:All ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ⣷
                                                               fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      delete from public.mt_doc_deadletterevent as d where d.data ->> 'ProjectionName' = :p0;truncate table public.mt_doc_memberbreederview CASCADE;delete from public.mt_event_progression where name = :p1;
        p0: MemberBreederView
        p1: MemberBreederView:All
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.CancellationToken.ThrowIfCancellationRequested()
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.ObjectDisposedException: NpgsqlTransaction
         at Npgsql.NpgsqlTransaction.CheckDisposed()
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)




^C%                                                                                                                                                                    (base) ➜  Web git:(backend/include-member-details-in-contact-list) ✗ 
```

**Comment by Richard87** [comment]
Yup, I agree, it seems there is some race condition going on, maybe repainting the terminal is overwriting some of the error logs :( 

Each time I run the command the output is slightly different.

This is the most complete output:
```

── IDocumentStore ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable.
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      delete from public.mt_doc_deadletterevent as d where d.data ->> 'ProjectionName' = :p0;truncate table public.mt_doc_dogmemberview CASCADE;delete from public.mt_event_progression where name = :p1;
        p0: DogMemberView
        p1: DogMemberView:All
      Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to read/write dependencies among transactions
      
      DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
        Exception data:
          Severity: ERROR
          SqlState: 40001
          MessageText: could not serialize access due to read/write dependencies among transactions
          Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
          Hint: The transaction might succeed if retried.
          File: predicate.c
          Line: 4815
          Routine: OnConflict_CheckForSerializationFailure
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      delete from public.mt_doc_deadletterevent as d where d.data ->> 'ProjectionName' = :p0;truncate table public.mt_doc_contactlistview CASCADE;delete from public.mt_event_progression where name = :p1;
        p0: ContactListView
        p1: ContactListView:All
      Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to read/write dependencies among transactions
      
      DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
        Exception data:
          Severity: ERROR
          SqlState: 40001
          MessageText: could not serialize access due to read/write dependencies among transactions
          Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
          Hint: The transaction might succeed if retried.
          File: predicate.c
          Line: 4815
          Routine: OnConflict_CheckForSerializationFailure
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.ObjectDisposedException: NpgsqlTransaction
         at Npgsql.NpgsqlTransaction.CheckDisposed()
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.ObjectDisposedException: NpgsqlTransaction
         at Npgsql.NpgsqlTransaction.CheckDisposed()
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
                                                               
BreederView:All ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ⣷
    DogView:All ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% ⣷
                                                               fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      delete from public.mt_doc_deadletterevent as d where d.data ->> 'ProjectionName' = :p0;truncate table public.mt_doc_memberbreederview CASCADE;delete from public.mt_event_progression where name = :p1;
        p0: MemberBreederView
        p1: MemberBreederView:All
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.CancellationToken.ThrowIfCancellationRequested()
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)
fail: Marten.IDocumentStore[0]
      Marten encountered an exception executing 
      
      
      System.ObjectDisposedException: NpgsqlTransaction
         at Npgsql.NpgsqlTransaction.CheckDisposed()
         at Npgsql.NpgsqlTransaction.CheckReady()
         at Npgsql.NpgsqlTransaction.Rollback(Boolean async, CancellationToken cancellationToken)
         at Marten.Internal.Sessions.MartenControlledConnectionTransaction.RollbackAsync(CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)




^C%                           
```

**Comment by Richard87** [comment]
I assume atleast one projection stream fails and breaks the db connection (but it's impossible to know what happend), then the other projections fails.

Then it hangs waiting for timeout or ctrl+c

**Comment by jeremydmiller** [comment]
Again, we've tested this from the get go with several projections at a time and never seen this issue. What's different about *your* particular usage? Do you wanna try for a reproduction repo? You aren't calling SaveChanges() somehow in one of your projections are you? Or using multiple projections that somehow target the same tables?

**Comment by jeremydmiller** [comment]
The different projections aren't sharing a single connection at any point

**Comment by Richard87** [comment]
Yes, I am building different projections for the same aggregate (private vs public views, and specialized views for auth controll).

All my projections are SingleStreamProjections with record views, no SaveChanges anywhere in my projections :) 

Without a proper error-log I have no idea where to start, but looking into a different log writer now for error logs, maybe I can figure something out, and hopefully create a repo testing it out! 👍

**Comment by jeremydmiller** [comment]
"Yes, I am building different projections for the same aggregate" -- different document types being output though, or the same document types across projections?

**Comment by Richard87** [comment]
Ah, no different documents, 1 document for each projection :)

**Comment by Richard87** [comment]
Closing this issue, as the problem is the scrambled log output, and probably not the Npsql errors (https://github.com/JasperFx/marten/issues/2682)
