### ISSUE TITLE
`ConcurrencyException` not being thrown during SaveChangesAsync

### ISSUE THREAD

**Issue by elexisvenator** [JasperFx/marten#2696]
Noticing this occasionally. Based on older discussions in discord, an `EventStreamUnexpectedMaxEventIdException` (which inherits from concurrency exception) should be thrown when this specific error happens. Looking at the code though I cannot find anywhere where the appropriate transformer is added to the list of operations. I tried rolling back the marten source code to 5.11 but I cannot find it there either.  The transformer is being used in a different path that only seems to be for linq queries and QuerySession. The UpdateBatch.ApplyChangesAsync does not appear to be on this path.

Stack Trace:
```
23505: duplicate key value violates unique constraint "pk_mt_events_stream_and_version"

DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information

   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Marten.Internal.UpdateBatch.ApplyCallbacksAsync(IReadOnlyList`1 operations, DbDataReader reader, IList`1 exceptions, CancellationToken token)
   at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
   at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
   at [application code]
```

**Comment by oskardudycz** [comment]
@elexisvenator, the error is thrown when UpdateBatch calls `ExecuteReaderAsync` method from `QuerySession` (it's a base class for all the document sessions). Could you provide more details on how you're appending events?

The tests for this scenario are placed here: https://github.com/JasperFx/marten/blob/4dafe48f4209a90b5c66ee8a9a2a60e15d7ca991/src/EventSourcingTests/EventStreamUnexpectedMaxEventIdExceptionTransformTest.cs#L11

**Comment by elexisvenator** [comment]
The query is a bulk import operation and 78 data entities were updated. Each one would have resulted in 2 stream each being appended with a single event. There would have been no overlapping here so each stream would have been appended to at most once.
All of this was queued into a single "SaveChangesAsync" command.

I do have a trace of the error so I can send that through if you want to see the marten call that was happening at the time. It looks pretty standard for a many-insert operation, involving 3 inline projections followed by stream updates and event inserts

**Comment by jeremydmiller** [comment]
I've got this one, not going to be a big deal
