### ISSUE TITLE
System.Exception: Cyclic dependency found

### ISSUE THREAD

**Issue by ekulakov** [JasperFx/marten#274]
```
theStore.Schema.Alter(_ => _.For<Issue>()
    .ForeignKey<User>(x => x.AssigneeId)
    .ForeignKey<User>(x => x.ReporterId));

theSession.Store(new Issue());
theSession.SaveChanges();
```
generates
```
System.Exception: Cyclic dependency found
   at Marten.Schema.DocumentSchema.<>c__DisplayClass13_0.<buildSchemaObjectsIfNecessary>b__1(Type documentType)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Schema.DocumentSchema.buildSchemaObjectsIfNecessary(IDocumentMapping mapping, Action`1 executeSql, ISet`1 documentTypes)
   at Marten.Schema.DocumentSchema.<>c__DisplayClass13_0.<buildSchemaObjectsIfNecessary>b__1(Type documentType)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Schema.DocumentSchema.buildSchemaObjectsIfNecessary(IDocumentMapping mapping, Action`1 executeSql, ISet`1 documentTypes)
   at Marten.Schema.DocumentSchema.buildSchemaObjectsIfNecessary(IDocumentMapping mapping)
   at Marten.Schema.DocumentSchema.<>c__DisplayClass11_0.<StorageFor>b__0(Type type)
```

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/pull/275
