### ISSUE TITLE
QueryRawEventDataOnly with StreamIdentity string fails when Id is selected with InvalidCastException

### ISSUE THREAD

**Issue by gfoidl** [JasperFx/marten#2777]
Repro for Marten version 6.3.0:
```c#
using Marten;
using Marten.Events;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

HostApplicationBuilder appBuilder = Host.CreateApplicationBuilder(new HostApplicationBuilderSettings
{
    EnvironmentName = "Development"
});

appBuilder.Services.AddMarten(options =>
{
    options.Connection("host=10.0.0.20;username=root;password=root;database=test_db");

    options.Events.StreamIdentity = StreamIdentity.AsString;
})
.UseLightweightSessions();

IHost app = appBuilder.Build();
await app.StartAsync();

using IDocumentStore store = app.Services.GetRequiredService<IDocumentStore>();
await store.Advanced.Clean.CompletelyRemoveAllAsync();

await using (IDocumentSession session = store.LightweightSession())
{
    session.Events.Append("a", new DummyEvent("a"));

    await session.SaveChangesAsync();
}

await using (IQuerySession session = store.QuerySession())
{
    var ids = await session.Events.QueryRawEventDataOnly<DummyEvent>()
        .Select(d => d.Id)          // This causes the operation to fail
        .ToListAsync();
}

await app.StopAsync();

public record DummyEvent(string Id);
```

```
Unhandled exception. System.InvalidCastException: Can't cast database type uuid to String
   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ReadCustom[TAny](NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
   at Npgsql.NpgsqlDataReader.GetFieldValueAsync[T](Int32 ordinal, CancellationToken cancellationToken)
   at Marten.Linq.SqlGeneration.ScalarStringSelectClause.ResolveAsync(DbDataReader reader, CancellationToken token)
   at Marten.Linq.QueryHandlers.ListQueryHandler`1.HandleAsync(DbDataReader reader, IMartenSession session, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token)
   at Program.<Main>$(String[] args)
```

**Comment by gfoidl** [comment]
I'm missing too much knowledge of the internal workings in Marten, so I'm not really able to fix that issue.
https://github.com/JasperFx/marten/commit/bb978cb964c958b7172eae9b58d62d6b3efb5d3f adds a test to repro the problem

## Analysis

From debugging I can see that the constructed `ListQueryHandler` is correct:
![grafik](https://github.com/JasperFx/marten/assets/5755834/16c06ec8-ca87-4994-b42e-010f340828a3)

But then the command text (SQL) seems wrong to me:
```sql
select
    d.id
from
    query_against_event_documents_tests.mt_events as d
where
    (d.type = 'string_id_event' and  d.is_archived = FALSE)
```
as it selects the `id` from the event, and not the (in Linq specified) the `id` of the event-type.

From the database
![grafik](https://github.com/JasperFx/marten/assets/5755834/1b5afa38-2370-4129-9830-1c0a53274e68)

and in the debugger at `ListQueryHandler<T>.Handle`:
![grafik](https://github.com/JasperFx/marten/assets/5755834/582ef605-5e1e-4da6-aef5-124a812aca93)

So a `string` is expected, but a `Guid` delivered because the SQL is wrong.

## Workarounds

* don't name the id property in the event `Id`, e.g. when named `MyId` then the SQL is correct
  ```sql
  select
      d.data ->> 'MyId'
  from
      query_against_event_documents_tests.mt_events as d
  where
      (d.type = 'string_id_event' and  d.is_archived = FALSE)
  ```
* use an anonymous type in the `Select`-clause, like `theSession.Events.QueryRawEventDataOnly<StringIdEvent>().Select(e => new { e.Id })`, then the SQL is also correct
  ```sql
  select
      jsonb_build_object(
          'Id', d.id
      ) as data
  from
      query_against_event_documents_tests.mt_events as d
  where
      (d.type = 'string_id_event' and  d.is_archived = FALSE)
  ```

**Comment by gfoidl** [comment]
With https://github.com/gfoidl/marten/commit/06358a37f2a1ddacf1f2a082a9007f62911e2103 both (new) tests fail.

If the `Id` and the stream or of type `Guid` the query passes, but you get a different value for the id as expected, namely the one from the stream and not the one from the event.
