### ISSUE TITLE
NpgsqlDataSource - System.ObjectDisposedException : The semaphore has been disposed.

### ISSUE THREAD

**Issue by krmapowel** [JasperFx/marten#2882]
After bump to 7.0-beta.3 we've started getting a lot of unstable tests, failing on connections pretty randomly.

Setup:
Azure Devops ubuntu-latest agent.
PGSQL 13.10 on docker running on this agent. Currently extended max connections to 500 to check if it helps (it didn't change much).
4 different xUnit Test Collections running in parallel after build, around 200 tests in total.
Asp.Net Test Server is used.
Each test collection creates its separate database, which is reused for all tests in given test collection.
Tests fail with this randomly, sometimes during database creation, sometimes during single query to database.
Oh, and locally I have PGSQL installed on my Windows machine and run it through Visual Studio test runner, and couldn't reproduce the issue.
My colleague running PGSQL locally on docker managed to reproduce it.

`services.AddMarten(opts =>
{
    var tenants = Configuration.GetSection("tenants").GetChildren();
    opts.MultiTenantedDatabases(x =>
    {
        foreach (var tenant in tenants)
        {
            x.AddSingleTenantDatabase(tenant.Value, tenant.Key);
        }
    });

    opts.ConfigureAll();
}).ApplyAllDatabaseChangesOnStartup();`

Within tests it's always single tenant with connection string to a database (one database name per test collection).
So, when starting test collection it starts test server and run database setup within ApplyAllDatabaseChangesOnStartup. I don't think I'm doing much else with databases here.

**Comment by jeremydmiller** [comment]
@krmapowel That's not enough information to be actionable. Is there anything else you can add? Stacktraces? How are you testing? Are you missing a `using` somewhere in your tests?

**Comment by krmapowel** [comment]
@jeremydmiller this is follow up for thread https://discord.com/channels/1074998995086225460/1187759160536858714 with @oskardudycz 
`  Error Message:
   System.ObjectDisposedException : The semaphore has been disposed.
  Stack Trace:
     at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSource.Bootstrap(NpgsqlConnector connector, NpgsqlTimeout timeout, Boolean forceReload, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>gRentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>gOpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Marten.Internal.Sessions.MartenControlledConnectionTransaction.EnsureConnectedAsync(CancellationToken token)
   at Marten.Internal.Sessions.ReadOnlyMartenControlledConnectionTransaction.ApplyAsync(NpgsqlCommand command, CancellationToken token)
   at Marten.Internal.Sessions.QuerySession.ExecuteReaderAsync(NpgsqlCommand command, CancellationToken token)`

This pops up randomly in tests. Sometimes during database creation (there are 4 test collections, and each one of them sets up its own database that gets reused).
I couldn't find any missing `using` in tests (almost all the tests use connection management from app IoC).

Adding default retry strategy for transient exceptions help mitigate the issue, as it retries for those exceptions. This was not needed prior to beta.3 version.

@jeremydmiller is there anything specific I can add about how tests are run? It's hard for me to figure out how much more detailed I should go with those explanations.

**Comment by jeremydmiller** [comment]
@krmapowel I don't have the faintest clue to be honest, and you're still the only person who has reported this. Can you try again with 7.beta.5? There were significant changes to the connection lifetime code and resiliency in that release that will probably have some impact here.

**Comment by krmapowel** [comment]
@jeremydmiller sorry for the long wait. I did try yesterday with most recent RC version.
And as previously worked with Retry strategy for transient exceptions, I just can't get reliable retry strategy with Polly.

**Comment by jeremydmiller** [comment]
@krmapowel You're doing something directly with `QuerySession.Connection` on top of or to the side of Marten operations? You have to be in order to even get Marten into the "sticky connection" mode.

**Comment by krmapowel** [comment]
I've checked both sticky connection and autoclosed connection.
```
  Error Message:
   System.ObjectDisposedException : The semaphore has been disposed.
  Stack Trace:
     at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.WaitAsync(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.WaitAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSource.Bootstrap(NpgsqlConnector connector, NpgsqlTimeout timeout, Boolean forceReload, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Marten.Internal.Sessions.TransactionalConnection.EnsureConnectedAsync(CancellationToken token)
   at Marten.Internal.Sessions.TransactionalConnection.ApplyAsync(NpgsqlBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.TransactionalConnection.ExecuteReaderAsync(NpgsqlBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.QuerySession.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Events.QueryEventStore.FetchStreamAsync(String streamKey, Int64 version, Nullable`1 timestamp, Int64 fromVersion, CancellationToken token)
   at Marten.Events.QueryEventStore.AggregateStreamAsync[T](String streamKey, Int64 version, Nullable`1 timestamp, T state, Int64 fromVersion, CancellationToken token)
```

With AutoClosingConnection

```
  Error Message:
   System.ObjectDisposedException : The semaphore has been disposed.
  Stack Trace:
     at System.Threading.SemaphoreSlim.CheckDispose()
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.Wait(TimeSpan timeout, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSource.Bootstrap(NpgsqlConnector connector, NpgsqlTimeout timeout, Boolean forceReload, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open()
   at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteReader(NpgsqlBatch batch)
   at Marten.Internal.Sessions.QuerySession.<>c.<ExecuteReader>b__64_0(BatchExecution e)
   at Polly.ResiliencePipeline.<>c__36`2.<Execute>b__36_0(ResilienceContext _, ValueTuple`2 state)
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.Execute[TResult,TState](Func`2 callback, TState state)
   at Marten.Internal.Sessions.QuerySession.ExecuteReader(NpgsqlBatch batch)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandler[T](IQueryHandler`1 handler)
--- End of stack trace from previous location ---
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandler[T](IQueryHandler`1 handler)
   at Marten.Linq.MartenLinqQueryProvider.Execute[TResult](Expression expression)
   at Marten.Linq.MartenLinqQueryable`1.GetEnumerator()
```

On Marten 7.0 it still happens, and I can't get to stabilize tests with any Polly retry strategy.
I also still can't get the problem reproduced locally (windows machine + postgres installed). But it happens pretty consistent (although in different tests each time) on azure ubuntu-latest agent with postgres in docker.

I'll be trying more things to get it to, at least, be reproduced.

**Comment by jeremydmiller** [comment]
@krmapowel Have you tried asking the Npgsql team about this? And how are you configuring Marten? Are you directly setting the NpgsqlDataSource or registering it to the DI container w/ Aspire or something? 

We're not getting this report from anyone else right now, so it's something unique to your setup

**Comment by krmapowel** [comment]
@jeremydmiller Nope, haven't try Npgsql team yet.
Right now I've tried again, updating from 6.x to 7.2.0, and this issue started to be fully reproducible locally, and it fails consistently for all tests. I would call that a success, because on 7.0.1 this happened only on build agent.

In tests I pass single tenant in configuration.
```csharp
services.AddMarten(opts =>
{
    var tenants = Configuration.GetSection("InvoicingTenants").GetChildren();
    opts.MultiTenantedDatabases(x =>
    {
        foreach (var tenant in tenants)
        {
            x.AddSingleTenantDatabase(tenant.Value, tenant.Key);
        }
    });

    opts.ConfigureAll();
}).ApplyAllDatabaseChangesOnStartup();
 ```
 
While ConfigureAll is extension method. I do share one project between multiple executables that get autogenerated code put into (hance  _.SetApplicationProject(typeof(DocumentStoreExtensions).Assembly);
```csharp
public static StoreOptions ConfigureAll(this StoreOptions _)
{
    _.Events.StreamIdentity = StreamIdentity.AsString;
    _.SetApplicationProject(typeof(DocumentStoreExtensions).Assembly);
    _.GeneratedCodeMode = TypeLoadMode.Static;
    _.AutoCreateSchemaObjects = AutoCreate.CreateOrUpdate;
    _.Storage.Add(new AgreementIdSequence(_, 1));

    _.ConfigureEvents();
    _.ConfigureInlineProjections();
    _.ConfigureDocuments();
    _.ConfigureLiveAggregates();
    return _;
}
```

This is exception, which I'm currently getting consistently locally:
```
System.ObjectDisposedException
Cannot access a disposed object.
Object name: 'Npgsql.PoolingDataSource'.
   at Npgsql.ThrowHelper.ThrowObjectDisposedException(String objectName)
   at Npgsql.NpgsqlDataSource.CheckDisposed()
   at Npgsql.PoolingDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Marten.Internal.Sessions.TransactionalConnection.EnsureConnectedAsync(CancellationToken token)
   at Marten.Internal.Sessions.TransactionalConnection.ApplyAsync(NpgsqlBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.TransactionalConnection.ExecuteReaderAsync(NpgsqlBatch batch, CancellationToken token)
   at Marten.Internal.Sessions.QuerySession.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Events.QueryEventStore.FetchStreamAsync(String streamKey, Int64 version, Nullable`1 timestamp, Int64 fromVersion, CancellationToken token)
   at Marten.Events.QueryEventStore.AggregateStreamAsync[T](String streamKey, Int64 version, Nullable`1 timestamp, T state, Int64 fromVersion, CancellationToken token)
```

This happens whenever I start a session through
```csharp
await using var session = _store.LightweightSession(_tenantId);
```
inside session.Connection there's already exception that Connection has been disposed.

Important part - for whatever reason **it does work correctly first time when test server handles request**.
Second time I get exception.

**Comment by jeremydmiller** [comment]
This all turned out to be because the DocumentStore was being unexpectedly disposed in some application code, which disposes the underlying NpgsqlDataSource, and you get this.
