### ISSUE TITLE
Querying based on an enum collection breaks when enums are stored as strings

### ISSUE THREAD

**Issue by rigtigeEmil** [JasperFx/marten#2946]
Querying against a document with a stored collection of enum values breaks. 
The option `enumStorage: EnumStorage.AsString` when configuring seralization causes the issue. 

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Marten.Linq.Members.EnumAsStringMember..ctor(IQueryableMember parent, Casing casing, MemberInfo member)
         at Marten.StoreOptions.CreateQueryableMember(MemberInfo member, IQueryableMember parent, Type memberType)
         at Marten.Linq.Members.ValueCollections.SelectManyValueCollection..ctor(ValueCollectionMember valueCollectionMember, MemberInfo parentMember, Type elementType, StoreOptions options)
         at Marten.Linq.Members.ValueCollections.ValueCollectionMember..ctor(StoreOptions storeOptions, IQueryableMember parent, Casing casing, MemberInfo member)
         at Marten.StoreOptions.CreateQueryableMember(MemberInfo member, IQueryableMember parent, Type memberType)
         at Marten.StoreOptions.CreateQueryableMember(MemberInfo member, IQueryableMember parent)
         at Marten.Linq.Members.DocumentQueryableMemberCollection.FindMember(MemberInfo member)
         at Marten.Linq.Parsing.LinqInternalExtensions.MemberFor(IHasChildrenMembers collection, Expression expression)
         at Marten.Linq.Parsing.Methods.EnumerableContains.Parse(IQueryableMemberCollection memberCollection, IReadOnlyStoreOptions options, MethodCallExpression expression)
         at Marten.Linq.Parsing.WhereClauseParser.VisitMethodCall(MethodCallExpression node)
         at Marten.Linq.SqlGeneration.Statement.ParseWhereClause(IReadOnlyList`1 wheres, IMartenSession session, IQueryableMemberCollection collection, IDocumentStorage storage)
         at Marten.Linq.CollectionUsage.BuildTopStatement(IMartenSession session, IQueryableMemberCollection collection, IDocumentStorage storage, QueryStatistics statistics)
         at Marten.Linq.Parsing.LinqQueryParser.BuildStatements()
         at Marten.Linq.Parsing.LinqQueryParser.BuildListHandler[T]()
         at Marten.Linq.MartenLinqQueryable`1.ToListAsync[TResult](CancellationToken token)
         at CreateEndpoint.GetWebhook(IQuerySession session) in C:\git\Gilbert\src\Test\Program.cs:line 73
         at Internal.Generated.WolverineHandlers.GET_.Handle(HttpContext httpContext)
         at Internal.Generated.WolverineHandlers.GET_.Handle(HttpContext httpContext)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

```cs
using Marten;
using Marten.Events;
using Marten.Services.Json;
using Oakton;
using Oakton.Resources;
using Weasel.Core;
using Wolverine;
using Wolverine.Http;
using Wolverine.Marten;

var builder = WebApplication.CreateBuilder(args);

builder.Host.ApplyOaktonExtensions();
builder.Host.UseWolverine();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddResourceSetupOnStartup();

builder.Services.AddMarten(options =>
    {
        options.Connection("User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=postgres;Persist Security Info=true;");
        options.UseDefaultSerialization(
            serializerType: SerializerType.SystemTextJson,
            casing: Casing.CamelCase,
            enumStorage: EnumStorage.AsString,
            nonPublicMembersStorage: NonPublicMembersStorage.All,
            collectionStorage: CollectionStorage.AsArray);

        options.AutoCreateSchemaObjects = AutoCreate.All;
        options.Events.StreamIdentity = StreamIdentity.AsString;
    })
    .UseLightweightSessions()
    .EventForwardingToWolverine()
    .ApplyAllDatabaseChangesOnStartup();

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();

app.MapWolverineEndpoints();

return await app.RunOaktonCommands(args);


public record MyDoc(string Id, EnumType[] Events);

public enum EnumType
{
    First,
    Second
}

public static class CreateEndpoint{
    [WolverinePost("/")]
    public static async Task CreateWebhook(IDocumentSession session)
    {
        session.Store(new MyDoc("1", [EnumType.First, EnumType.Second]));
        await session.SaveChangesAsync();
    }

    [WolverineGet("/")]
    public static async Task<IReadOnlyList<MyDoc>> GetWebhook(IQuerySession session)
    {
        var docs = await session.Query<MyDoc>()
            .Where(x => x.Events.Contains(EnumType.First))
            .ToListAsync();
        return docs;
    }
}
```

```yml
version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
```

```
<PackageReference Include="Marten" Version="7.0.0-beta.5" />
<PackageReference Include="Marten.AspNetCore" Version="7.0.0-beta.5" />
<PackageReference Include="WolverineFx" Version="2.0.0-alpha.1" />
<PackageReference Include="WolverineFx.Http" Version="2.0.0-alpha.1" />
<PackageReference Include="WolverineFx.Http.FluentValidation" Version="2.0.0-alpha.1" />
<PackageReference Include="WolverineFx.Marten" Version="2.0.0-alpha.1" />
```

**Comment by rigtigeEmil** [comment]
@jeremydmiller From your test it does indeed look like it. Thanks! I'll give it a go when a new beta version is out
