### ISSUE TITLE
clone and build using build.ps1 fails

### ISSUE THREAD

**Issue by AbhinavPradeep** [JasperFx/marten#2964]
Hey I am new to this community and keen to contribute. I run a windows machine and am using the powershell build script. I cloned the master branch and following instructions used .\build.ps1. Build fails with the below error:

````
Using net8.0


build: Starting... (default)
build: install: Starting...
build: C:\Program Files\nodejs\npm.cmd install
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @braintree/sanitize-url@3.1.0: Potential XSS vulnerability patched in v6.0.0.

changed 1722 packages, and audited 1683 packages in 3m

219 packages are looking for funding
  run `npm fund` for details

30 vulnerabilities (8 moderate, 22 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
build: install: Succeeded (3 m 18 s)
build: mocha: Starting...
build: C:\Program Files\nodejs\npm.cmd run test

> test
> mocha

node:internal/modules/cjs/loader:1152
  throw err;
  ^

Error: Cannot find module 'path-is-absolute'
Require stack:
- \marten\node_modules\glob\glob.js
- \marten\node_modules\mocha\lib\cli\lookup-files.js
- \marten\node_modules\mocha\lib\cli\collect-files.js
- \marten\node_modules\mocha\lib\cli\watch-run.js
- \marten\node_modules\mocha\lib\cli\run-helpers.js
- \marten\node_modules\mocha\lib\cli\options.js
- \marten\node_modules\mocha\bin\mocha.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\Abhin\OneDrive\Dev\marten\node_modules\glob\glob.js:50:18)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19) {
  code: 'MODULE_NOT_FOUND',

Node.js v21.6.1
build: mocha: SimpleExec.ExitCodeException: The command exited with code 1.
   at SimpleExec.Command.Run(ProcessStartInfo startInfo, Boolean noEcho, String echoPrefix, Func`2 handleExitCode, CancellationToken cancellationToken) in /_/SimpleExec/Command.cs:line 124
   at SimpleExec.Command.Run(String name, String args, String workingDirectory, Boolean noEcho, String echoPrefix, Action`1 configureEnvironment, Boolean createNoWindow, Func`2 handleExitCode, CancellationToken cancellationToken) in /_/SimpleExec/Command.cs:line 57
   at martenbuild.MartenBuild.<>c.<Main>b__3_3() in C:\Users\Abhin\OneDrive\Dev\marten\build\build.cs:line 49
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bullseye.Internal.ActionTarget.RunAsync(Output output, Func`2 messageOnly, IReadOnlyCollection`1 dependencyPath, Stopwatch stopWatch) in /_/Bullseye/Internal/ActionTarget.cs:line 44
build: mocha: FAILED! The command exited with code 1. (1.48 s)
build: ───────────────────────────────────
build: Target   Outcome    Duration
build: ───────  ─────────  ───────────────
build: install  Succeeded  3 m 18 s  99.3%
build: mocha    FAILED!    1.48 s    0.7%
build: ───────────────────────────────────
build: FAILED! (default) (3 m 19 s)

```

**Comment by mysticmind** [comment]
@AbhinavPradeep We will have a look and revert to you. For now, ignore the npm tests, you can try `.\build.ps1 compile` which compiles all the projects. Or `.\build.ps1 test` which compiles and run the tests.

I think there is an issue with some mocha deps, will check and revert.

**Comment by mysticmind** [comment]
Also additionally, what version of node.js are you running?

**Comment by AbhinavPradeep** [comment]
Thanks a lot for the response. I am using node v21.6.1. 

Yes will try the other commands. Have been directly using dotnet build on the project file which lets me debug through the tests.

**Comment by mysticmind** [comment]
I would suggest to use node v20.x which we use in our CI builds. Closing this.
