### ISSUE TITLE
V7 42601: cannot insert multiple commands into a prepared statement

### ISSUE THREAD

**Issue by pascalberger** [JasperFx/marten#2985]
After updating to Wolverine 2 / Marten 7 we receive the following exception

```
Marten.Exceptions.MartenCommandException : Marten Command Failure:$
$
$
42601: cannot insert multiple commands into a prepared statement
---- Npgsql.PostgresException : 42601: cannot insert multiple commands into a prepared statement
```

Stack trace:

```
at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
at Polly.ResiliencePipeline.<>c__2`1.<<ExecuteAsync>b__2_0>d.MoveNext()
--- End of stack trace from previous location ---
at Polly.Outcome`1.GetResultOrRethrow()
at Polly.ResiliencePipeline.ExecuteAsync[TState](Func`3 callback, TState state, CancellationToken cancellationToken)
at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
[at TenantInstance.IntegrationWorker.Tests.Handlers.RecycleBin.RestoreRecycleBinEntryHandlerTest.CreateContract(Guid contractTypeId, Guid organizationalUnitId, Boolean archived, Boolean deleted) in /__w/1/s/src/TenantInstance/TenantInstance.IntegrationWorker.Tests/Handlers/RecycleBin/RestoreRecycleBinEntryHandlerTest.cs:line 495](https://dev.azure.com/swissgrc/Swiss%20GRC/_git/d95d9248-6279-4c6d-93dc-60b836c00b95?path=%2F__w%2F1%2Fs%2Fsrc%2FTenantInstance%2FTenantInstance.IntegrationWorker.Tests%2FHandlers%2FRecycleBin%2FRestoreRecycleBinEntryHandlerTest.cs&version=GBfeature%2Fpbe%2Fwolverine2&_a=contents&line=495&lineEnd=496&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
[at TenantInstance.IntegrationWorker.Tests.Handlers.RecycleBin.RestoreRecycleBinEntryHandlerTest.Does_restore_individual_contract_folder_and_its_attachments_and_versions() in /__w/1/s/src/TenantInstance/TenantInstance.IntegrationWorker.Tests/Handlers/RecycleBin/RestoreRecycleBinEntryHandlerTest.cs:line 194](https://dev.azure.com/swissgrc/Swiss%20GRC/_git/d95d9248-6279-4c6d-93dc-60b836c00b95?path=%2F__w%2F1%2Fs%2Fsrc%2FTenantInstance%2FTenantInstance.IntegrationWorker.Tests%2FHandlers%2FRecycleBin%2FRestoreRecycleBinEntryHandlerTest.cs&version=GBfeature%2Fpbe%2Fwolverine2&_a=contents&line=194&lineEnd=195&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Marten.Internal.Sessions.OperationPage.ApplyCallbacksAsync(DbDataReader reader, IList`1 exceptions, CancellationToken token)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
```

**Comment by pascalberger** [comment]
I try to come up with a repro for the issue (we can reproduce it in our test cases, need to isolate it in something which I can share)

**Comment by jeremydmiller** [comment]
It's figuring out what combination of operations you were doing. Are you using a QueueSqlCommand w/ a semi-colon maybe?

**Comment by pascalberger** [comment]
> It's figuring out what combination of operations you were doing. Are you using a QueueSqlCommand w/ a semi-colon maybe?

Yes, that seems to be issue.

Here's the code which is building the statement:

```
public void QueueCommand()
{
    var rawSql = this.statements
        .Aggregate(
            string.Empty,
            (sql, statement) => $"{sql}{statement.RawSql};");

    var parameters = this.statements
        .Aggregate(
            Enumerable.Empty<object>(),
            (args, statement) => args.Concat(statement.Bindings));

    this.ops.QueueSqlCommand(rawSql, parameters.ToArray());
}
```

Resulting in this statement

```
DELETE FROM "public"."mt_tbl_mytable" WHERE "my_id" = ?;INSERT INTO "public"."mt_tbl_mytable" ("id", "my_id", "otherfields") VALUES (?, ?);
```

**Comment by jeremydmiller** [comment]
Fixed locally w/ a validation message
