### ISSUE TITLE
V7 System.InvalidOperationException : CommandText property has not been initialized

### ISSUE THREAD

**Issue by pascalberger** [JasperFx/marten#2986]
After updating to Wolverine 2 / Marten 7 we receive the following exception

```
System.InvalidOperationException : CommandText property has not been initialized
```

Stack trace:

```
at Npgsql.ThrowHelper.ThrowInvalidOperationException(String message)
at Npgsql.NpgsqlCommand.ProcessRawQuery(SqlQueryParser parser, Boolean standardConformingStrings, NpgsqlBatchCommand batchCommand)
at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteBatchPagesAsync(IReadOnlyList`1 pages, List`1 exceptions, CancellationToken token)
at Polly.ResiliencePipeline.<>c__2`1.<<ExecuteAsync>b__2_0>d.MoveNext()
--- End of stack trace from previous location ---
at Polly.ResiliencePipeline.ExecuteAsync[TState](Func`3 callback, TState state, CancellationToken cancellationToken)
at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
[at Core.Testing.AlbaHostExtensions.InternalSeedDataAsync(IAlbaHost host, String tenantName, IEnumerable`1 seeders) in /__w/1/s/src/Core/Core.Testing/AlbaHostExtensions.cs:line 149](https://dev.azure.com/swissgrc/Swiss%20GRC/_git/d95d9248-6279-4c6d-93dc-60b836c00b95?path=%2F__w%2F1%2Fs%2Fsrc%2FCore%2FCore.Testing%2FAlbaHostExtensions.cs&version=GBfeature%2Fpbe%2Fwolverine2&_a=contents&line=149&lineEnd=150&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
[at Core.Testing.AlbaHostExtensions.InternalSeedDataAsync(IAlbaHost host, String tenantName, IEnumerable`1 seeders) in /__w/1/s/src/Core/Core.Testing/AlbaHostExtensions.cs:line 146](https://dev.azure.com/swissgrc/Swiss%20GRC/_git/d95d9248-6279-4c6d-93dc-60b836c00b95?path=%2F__w%2F1%2Fs%2Fsrc%2FCore%2FCore.Testing%2FAlbaHostExtensions.cs&version=GBfeature%2Fpbe%2Fwolverine2&_a=contents&line=146&lineEnd=147&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
[at TenantInstance.QueryApi.Tests.Endpoints.Clm.Contracts.GetAllContractsEndpointTest.Returns_Ok_on_valid_request() in /__w/1/s/src/TenantInstance/TenantInstance.QueryApi.Tests/Endpoints/Clm/Contracts/GetAllContractsEndpointTest.cs:line 198](https://dev.azure.com/swissgrc/Swiss%20GRC/_git/d95d9248-6279-4c6d-93dc-60b836c00b95?path=%2F__w%2F1%2Fs%2Fsrc%2FTenantInstance%2FTenantInstance.QueryApi.Tests%2FEndpoints%2FClm%2FContracts%2FGetAllContractsEndpointTest.cs&version=GBfeature%2Fpbe%2Fwolverine2&_a=contents&line=198&lineEnd=199&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)
--- End of stack trace from previous location ---
```

**Comment by pascalberger** [comment]
I try to come up with a repro for the issue (we can reproduce it in our test cases, need to isolate it in something which I can share)

**Comment by pascalberger** [comment]
This issue was also fixed by replacing statements with `;` with separate calls to `QueueSqlCommand` as discussed in https://github.com/JasperFx/marten/issues/2985
