### ISSUE TITLE
Fix DateTimeZone serialization errors (regression issue)

### ISSUE THREAD

**Issue by JoshuaNitschke** [JasperFx/marten#2988]
I updated to Marten.NodaTime 7.0.0-beta.5 and am getting serialization errors in Unit Tests for DateTimeZone.  Beta.2 is fine.

```
System.NotSupportedException
Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'NodaTime.DateTimeZone'. Path: $.timeZone | LineNumber: 0 | BytePositionInLine: 435.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.TryRead[TArg](ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo, TArg& arg)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at Wolverine.Runtime.Serialization.SystemTextJsonSerializer.ReadFromData(Type messageType, Envelope envelope)
   at Wolverine.Runtime.HandlerPipeline.tryDeserializeEnvelope(Envelope envelope, IContinuation& continuation)
```

```
.Services.AddMarten(opts =>
    {
        var connString = builder.Configuration.GetConnectionString("marten");

        opts.Connection(connString!);
        opts.UseDefaultSerialization(
            serializerType: SerializerType.SystemTextJson,
            enumStorage: EnumStorage.AsInteger,
            casing: Casing.CamelCase,
            nonPublicMembersStorage: NonPublicMembersStorage.All
        );
        opts.UseNodaTime();
```

**Comment by jeremydmiller** [comment]
@JoshuaNitschke Just for fun, can you flip the order of UseNodaTime() and overriding the serializer?

**Comment by JoshuaNitschke** [comment]
Hi Jeremy, no problem, unfortunately it still fails :

```
builder
    .Services.AddMarten(opts =>
    {
        var connString = builder.Configuration.GetConnectionString("marten");

        opts.Connection(connString!);
        opts.UseNodaTime();
        opts.UseDefaultSerialization(
            serializerType: SerializerType.SystemTextJson,
            enumStorage: EnumStorage.AsInteger,
            casing: Casing.CamelCase,
            nonPublicMembersStorage: NonPublicMembersStorage.All
        );
```

**Comment by JoshuaNitschke** [comment]
Also, I think I made a mistake; I'm saw the same error on Beta.3 on my second computer, so I guess it is actually Beta.2 that last worked.  I must not have completely rebuilt the solution when I last tested on my primary PC.  - I will try to do a bit more testing later today if i have time to make sure.

**Comment by jeremydmiller** [comment]
@JoshuaNitschke What's the query or document you're using when you get this? Any way you could do a PR with a failing test?

**Comment by JoshuaNitschke** [comment]
@jeremydmiller let me see if I can get a PR with a failing test, I had that on my to do list and then got caught up with other stuff.

**Comment by JoshuaNitschke** [comment]
I couldn't get a test to fail in Marten.

I upgraded all my packages and it seems to be working fine now. 🤷🏻   a bit odd, but closing this as not reproducible anymore.
