### ISSUE TITLE
[BUG]: Can't rebuild projections when `Marten` used with `EfCore`

### ISSUE THREAD

**Issue by ParadiseFallen** [JasperFx/marten#2989]
## Description:
When project using `EfCore` with `Marten` it can't rebuild projections anymore.
`Marten` can't deserialize `headers` column.

## Setup:
Marten 6.4.1
```cs
services
   .AddMarten(provider =>
    {
        var options = new StoreOptions();

        options.Connection(connectionString);

        // Otherwise Schema Objects will be created at `public` schema
        options.DatabaseSchemaName = new NpgsqlConnectionStringBuilder(connectionString).Username!;
        options.AutoCreateSchemaObjects = AutoCreate.All;

        options.Events.MetadataConfig.HeadersEnabled = true; // this causes exception.
        options.Events.MetadataConfig.CausationIdEnabled = true;
        options.Events.MetadataConfig.CorrelationIdEnabled = true;
        
        // add projections & events ommited
        
        // marten won't log such exception by default for some reason
        options.Projections.OnException(x =>
        {
            Console.WriteLine(x);
            return true;
        }).DoNothing();

        return options;
    })
   .ApplyAllDatabaseChangesOnStartup()
   .AssertDatabaseMatchesConfigurationOnStartup()
   .AddAsyncDaemon(DaemonMode.HotCold)
   .OptimizeArtifactWorkflow()
   .UseLightweightSessions();
   
 
```
Just referencing
```xml
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2" />
```
in enough to break `Marten`

## Exception:
```sh
Marten.Events.Daemon.EventFetcherException: Failure while trying to load events for projection shard 'Identity: File:All@Marten'
 ---> System.InvalidCastException: Reading as 'System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' is not supported for fields having DataTypeName 'jsonb'
 ---> System.NotSupportedException: Type 'Dictionary`2' required dynamic JSON serialization, which requires an explicit opt-in; call 'EnableDynamicJson' on 'NpgsqlDataSourceBuilder' or NpgsqlConnection.GlobalTypeMapper (see https://www.npgsql.org/doc/types/json.html and the 8.0 release notes for more details). Alternatively, if you meant to use Newtonsoft JSON.NET instead of System.Text.Json, call UseJsonNet() instead.

   at Npgsql.Internal.ResolverFactories.JsonDynamicTypeInfoResolverFactory.ThrowIfUnsupported[TBuilder](Type type, Nullable`1 dataTypeName, PgSerializerOptions options)
   at Npgsql.Internal.ResolverFactories.UnsupportedTypeInfoResolver`1.GetTypeInfo(Type type, Nullable`1 dataTypeName, PgSerializerOptions options)
   at Npgsql.Internal.ChainTypeInfoResolver.GetTypeInfo(Type type, Nullable`1 dataTypeName, PgSerializerOptions options)
   at Npgsql.Internal.TypeInfoCache`1.<GetOrAddInfo>g__CreateInfo|6_3(Type type, Nullable`1 typeId, PgSerializerOptions options, Boolean defaultTypeFallback, Boolean validatePgTypeIds)
   at Npgsql.Internal.TypeInfoCache`1.<GetOrAddInfo>g__AddEntryById|6_2(Type type, TPgTypeId pgTypeId, ValueTuple`2[] infos, Boolean defaultTypeFallback)
   at Npgsql.Internal.TypeInfoCache`1.GetOrAddInfo(Type type, Nullable`1 pgTypeId, Boolean defaultTypeFallback)
   at Npgsql.Internal.PgSerializerOptions.GetTypeInfoCore(Type type, Nullable`1 pgTypeId, Boolean defaultTypeFallback)
   at Npgsql.Internal.PgSerializerOptions.GetTypeInfo(Type type, PostgresType pgType)
   at Npgsql.Internal.AdoSerializerHelpers.GetTypeInfoForReading(Type type, PostgresType postgresType, PgSerializerOptions options)
   --- End of inner exception stack trace ---
   at Npgsql.Internal.AdoSerializerHelpers.<GetTypeInfoForReading>g__ThrowReadingNotSupported|0_0(Type type, String displayName, Exception inner)
   at Npgsql.Internal.AdoSerializerHelpers.GetTypeInfoForReading(Type type, PostgresType postgresType, PgSerializerOptions options)
   at Npgsql.BackendMessages.FieldDescription.<GetInfo>g__GetInfoSlow|50_0(Type type, ColumnInfo& lastColumnInfo)
   at Npgsql.BackendMessages.FieldDescription.GetInfo(Type type, ColumnInfo& lastColumnInfo)
   at Npgsql.NpgsqlDataReader.<GetInfo>g__Slow|133_0(ColumnInfo& info, PgConverter& converter, Size& bufferRequirement, Boolean& asObject, <>c__DisplayClass133_0&)
   at Npgsql.NpgsqlDataReader.GetFieldValueCore[T](Int32 ordinal)
   at Npgsql.NpgsqlDataReader.GetFieldValueAsync[T](Int32 ordinal, CancellationToken cancellationToken)
   at Marten.Generated.EventStore.GeneratedEventDocumentStorage.ApplyReaderDataToEventAsync(DbDataReader reader, IEvent e, CancellationToken token) in <REDACTED>\Internal\Generated\EventStore\EventStorage.cs:line 135
   at Marten.Events.EventDocumentStorage.ResolveAsync(DbDataReader reader, CancellationToken token)
   at Marten.Events.Daemon.EventFetcher.handleEvent(EventRange range, CancellationToken token, DbDataReader reader)
   at Marten.Events.Daemon.RebuildingEventFetcher.handleEvent(EventRange range, CancellationToken token, DbDataReader reader)
   at Marten.Events.Daemon.EventFetcher.Load(EventRange range, CancellationToken token)
   at Marten.Events.Daemon.EventFetcher.Load(EventRange range, CancellationToken token)
   at Marten.Events.Daemon.EventFetcher.Load(EventRange range, CancellationToken token)
   --- End of inner exception stack trace ---
   at Marten.Events.Daemon.EventFetcher.Load(EventRange range, CancellationToken token)
   at Marten.Events.Daemon.ShardAgent.<>c__DisplayClass51_0.<<loadEvents>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Marten.Events.Daemon.ProjectionDaemon.TryAction(ActionParameters parameters)
   ```

**Comment by ParadiseFallen** [comment]
Simmilar to https://github.com/JasperFx/marten/issues/2912

**Comment by jeremydmiller** [comment]
@ParadiseFallen Can you try this with Marten 7? Marten 6.* does not support Npgsql 8, and I would guess that's part of the underlying issue here.

**Comment by ParadiseFallen** [comment]
Still intresting why just referencing it breaks whole app

**Comment by jeremydmiller** [comment]
@ParadiseFallen Because you brought in Npgsql through a transitive dependency of EF Core, and Marten 6 doesn't work with Npgsql 8.
