### ISSUE TITLE
Guids break Compiled Queries

### ISSUE THREAD

**Issue by BravoTango86** [JasperFx/marten#3005]
```c#
using var session = store.QuerySession();

var id = Guid.Parse("018df51a-d64c-4862-999b-945e3b891fc5");

var result = session.Query(new TestQuery(id));

public record Test(Guid Id, string Key, string Value);

public class TestQuery(Guid id) : ICompiledQuery<Test, Test?> {

    public Expression<Func<IMartenQueryable<Test>, Test?>> QueryIs() =>
        t => t.SingleOrDefault(t => t.Id == id);

}
```

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Compilation failures!

CS1002: ; expected
CS1002: ; expected
CS1002: ; expected
CS0103: The name 'f51a' does not exist in the current context
CS0103: The name 'd64c' does not exist in the current context
CS0103: The name 'b' does not exist in the current context
CS0103: The name 'b891fc5' does not exist in the current context
CS0201: Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement

Code:

// <auto-generated/>
#pragma warning disable
using Marten.Linq;
using Marten.Linq.QueryHandlers;
using System;

namespace Marten.Generated.CompiledQueries
{
    // START: QueryOnlyTestQueryCompiledQuery1476576754
    public class QueryOnlyTestQueryCompiledQuery1476576754 : Marten.Internal.CompiledQueries.ClonedCompiledQuery<Test, TestQuery>
    {
        private readonly Marten.Linq.QueryHandlers.IMaybeStatefulHandler _inner;
        private readonly TestQuery _query;
        private readonly Marten.Linq.QueryStatistics _statistics;

        public QueryOnlyTestQueryCompiledQuery1476576754(Marten.Linq.QueryHandlers.IMaybeStatefulHandler inner, TestQuery query, Marten.Linq.QueryStatistics statistics) : base(inner, query, statistics)
        {
            _inner = inner;
            _query = query;
            _statistics = statistics;
        }



        public override void ConfigureCommand(Weasel.Postgresql.ICommandBuilder builder, Marten.Internal.IMartenSession session)
        {
            var parameters1 = builder.AppendWithParameters(@"select d.data from public.mt_doc_test as d where d.id = ^ LIMIT ^;", '^');
            parameters1[0].Value = 018df51a-d64c-4862-999b-945e3b891fc5;
            parameters1[0].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Uuid;
            parameters1[1].Value = 2;
            parameters1[1].NpgsqlDbType = NpgsqlTypes.NpgsqlDbType.Integer;
        }

    }

    // END: QueryOnlyTestQueryCompiledQuery1476576754
    
    
    // START: QueryOnlyTestQueryCompiledQuerySource1476576754
    public class QueryOnlyTestQueryCompiledQuerySource1476576754 : Marten.Internal.CompiledQueries.CompiledQuerySource<Test, TestQuery>
    {
        private readonly Marten.Linq.QueryHandlers.IMaybeStatefulHandler _maybeStatefulHandler;

        public QueryOnlyTestQueryCompiledQuerySource1476576754(Marten.Linq.QueryHandlers.IMaybeStatefulHandler maybeStatefulHandler)
        {
            _maybeStatefulHandler = maybeStatefulHandler;
        }



        public override Marten.Linq.QueryHandlers.IQueryHandler<Test> BuildHandler(TestQuery query, Marten.Internal.IMartenSession session)
        {
            return new Marten.Generated.CompiledQueries.QueryOnlyTestQueryCompiledQuery1476576754(_maybeStatefulHandler, query, null);
        }

    }

    // END: QueryOnlyTestQueryCompiledQuerySource1476576754
    
    
}


  Source=JasperFx.RuntimeCompiler
  StackTrace:
   at JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(String code)
   at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
   at Marten.CompiledQueryCollection.GetCompiledQuerySourceFor[TDoc,TOut](ICompiledQuery`2 query, QuerySession session)
   at Marten.DocumentStore.GetCompiledQuerySourceFor[TDoc,TOut](ICompiledQuery`2 query, QuerySession session)
   at Marten.Internal.Sessions.QuerySession.Query[TDoc,TOut](ICompiledQuery`2 query)
   at Program.<Main>$(String[] args) in Program.cs:line 37

```

**Comment by jeremydmiller** [comment]
I'll take a look. It's not that Guids break per se I don't believe.  Might be because you used a record for the query type.

**Comment by BravoTango86** [comment]
'''c#
public class Test {
    public Guid Id { get; set; }
    public string Key { get; set; }
    public string Value { get; set; }
};
'''
Same error, though with further testing it seems to be due to the use of a primary constructor as this works fine:
```c#
using var session = store.QuerySession();

var id = Guid.Parse("018df51a-d64c-4862-999b-945e3b891fc5");

var result = session.Query(new TestQuery { Id = id});

public record Test(Guid Id, string Key, string Value);

public class TestQuery : ICompiledQuery<Test, Test?> {

    public Guid Id { get; set; }

    public Expression<Func<IMartenQueryable<Test>, Test?>> QueryIs() =>
        t => t.SingleOrDefault(t => t.Id == Id);

}
```

**Comment by jeremydmiller** [comment]
@BravoTango86 Sorry, all you're getting in V7 is come validation telling you to not use a primary constructor. The Reflection model is all weird and I don't see a quick way of beating that just at this moment.

**Comment by BravoTango86** [comment]
Cheers, can cope with that!
