### ISSUE TITLE
LongCountAsync fails on Marten 7.0

### ISSUE THREAD

**Issue by skarllot** [JasperFx/marten#3017]
Updating to version 7.0 the `LongCountAsync` throws an exception

```
[xUnit.net 00:00:17.55]     Raiqub.Expressions.Marten.Tests.Queries.MartenDbQueryTest.CountShouldReturnExpected(name: "Fourth", expected: 0) [FAIL]
[xUnit.net 00:00:17.55]       System.NotSupportedException : Marten does not know how to use result type long
[xUnit.net 00:00:17.55]       Stack Trace:
[xUnit.net 00:00:17.56]            at Marten.Linq.SqlGeneration.DataSelectClause`1.BuildHandler[TResult](IMartenSession session, ISqlFragment statement, ISqlFragment currentStatement)
[xUnit.net 00:00:17.56]            at Marten.Linq.Parsing.LinqQueryParser.buildHandlerForCurrentStatement[TResult](Statement top, SelectorStatement selector)
[xUnit.net 00:00:17.56]            at Marten.Linq.Parsing.LinqQueryParser.BuildHandler[TResult]()
[xUnit.net 00:00:17.56]            at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token, SingleValueMode valueMode)
[xUnit.net 00:00:17.56]            at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
[xUnit.net 00:00:17.56]            at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
[xUnit.net 00:00:17.56]            at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
[xUnit.net 00:00:17.56]            at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token, SingleValueMode valueMode)
```

The test runs the following code:
```csharp
var query = source
        .Where(b => b.Name == name)
        .SelectMany(b => b.Posts);

int count1 = await query.CountAsync();
long count2 = await query.LongCountAsync();
```

**Comment by jeremydmiller** [comment]
@skarllot We've got plenty of passing tests against the `LongCountAsync()` operator by itself. Do you have a more specific reproduction case?

**Comment by jeremydmiller** [comment]
Nevermind, I see the combination with SelectMany()

**Comment by jeremydmiller** [comment]
Started to think it was a wide ranging issue, but turned out to be just `LongCount`. There was a switch statement that looked for Any() or Count(), but not LongCount().
