### ISSUE TITLE
MatchesSql with "?" causes "Index was outside the bounds of the array"

### ISSUE THREAD

**Issue by kurtwarwick-new** [JasperFx/marten#3087]
Hi

I seem to be unable to use raw SQL that has a "?" symbol. When I do so, an `Index was outside the bounds of the array` exception is thrown.

SQL being used `WHERE data -> 'attributes' @? '$[*] ? (@.key == "someKey")'`.
Stack trace

```
   at Weasel.Postgresql.SqlGeneration.CustomizableWhereFragment.Apply(ICommandBuilder builder)
   at Marten.Linq.SqlGeneration.SelectorStatement.configure(ICommandBuilder sql)
   at Marten.Linq.SqlGeneration.Statement.Apply(ICommandBuilder builder)
   at Marten.Linq.QueryHandlers.ListQueryHandler`1.ConfigureCommand(ICommandBuilder builder, IMartenSession session)
   at Marten.Util.CommandExtensions.BuildCommand(IMartenSession session, IQueryHandler handler)
   at Marten.Linq.MartenLinqQueryProvider.<ExecuteHandlerAsync>d__17`1.MoveNext()
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
   at Marten.Linq.MartenLinqQueryProvider.<ExecuteHandlerAsync>d__17`1.MoveNext()
   at Marten.Linq.MartenLinqQueryable`1.<ToListAsync>d__29`1.MoveNext()
```

I have attempted to use `new CustomizableWhereFragment("WHERE data -> 'attributes' @? '$[*] ? (@.key == \"someKey\")", "^")`, and to use "??", to no avail.

Thanks

Kurt

**Comment by jeremydmiller** [comment]
Meh, little bit of detritus from the big Npgsql mechanic changes we did in 7.0. Fix coming up.
