### ISSUE TITLE
Exception while creating schema & tables & indexes

### ISSUE THREAD

**Issue by tomap** [JasperFx/marten#3101]
Hello,

I have two microservices starting conccurently

On one object, I have two indexes:
```
[DuplicateField]
public required DateTimeOffset Expiration { get; set; }
```
And another configured via
```
martenRegistry.For<docwrapqml>()
    .Index(d => d.Setup);

```
I was using 
`store.AutoCreateSchemaObjects = AutoCreate.All`

And in the middle of the startup, I have an error:

```
DDL Execution for 'All Configured Changes' Failed!

DO $$
BEGIN    IF NOT EXISTS(
        SELECT schema_name
          FROM information_schema.schemata
          WHERE schema_name = 'int'
      )
    THEN
      EXECUTE 'CREATE SCHEMA int';
    END IF;

END
$$;


CREATE INDEX mt_doc_docwrapqml_idx_expiration ON int.mt_doc_docwrapqml USING btree (expiration);
...
 ---> Npgsql.PostgresException (0x80004005): 42P07: relation "mt_doc_docwrapqml_idx_expiration" already exists
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
...
   at Weasel.Postgresql.PostgresqlMigrator.executeDelta(SchemaMigration migration, DbConnection conn, AutoCreate autoCreate, IMigrationLogger logger, CancellationToken ct)
  Exception data:
    Severity: ERROR
    SqlState: 42P07
    MessageText: relation "mt_doc_docwrapqml_idx_expiration" already exists
    File: index.c
    Line: 873
    Routine: index_create
   --- End of inner exception stack trace ---
   at Marten.StoreOptions.Weasel.Core.Migrations.IMigrationLogger.OnFailure(DbCommand command, Exception ex)
   at Weasel.Postgresql.PostgresqlMigrator.executeDelta(SchemaMigration migration, DbConnection conn, AutoCreate autoCreate, IMigrationLogger logger, CancellationToken ct)
   at Weasel.Core.Migrations.DatabaseBase`1.executeMigration(ISchemaObject[] schemaObjects, CancellationToken ct)
   at Weasel.Core.Migrations.DatabaseBase`1.executeMigration(ISchemaObject[] schemaObjects, CancellationToken ct)
   at Weasel.Core.Migrations.DatabaseBase`1.generateOrUpdateFeature(Type featureType, IFeatureSchema feature, CancellationToken token)
   at Weasel.Core.Migrations.DatabaseBase`1.ensureStorageExistsAsync(IList`1 types, Type featureType, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ensureStorageExists(LinqQueryParser parser)
   at Marten.Linq.MartenLinqQueryProvider.Execute[TResult](Expression expression)
   at Marten.Linq.MartenLinqQueryable`1.GetEnumerator()
```

I am not sure of the cause.

Should I declare all indexes together:

```
martenRegistry.For<docwrapqml>()
   .Duplicate(d => d.Expiration)
    .Index(d => d.Setup);
```

Or is it rather linked to the concurrency? 
One service is creating stuff, while the other only sees partially created tables & indexes, and restart from the ground up,...

Thank you

**Comment by jeremydmiller** [comment]
It could be concurrency, I suppose, yes. If you did it through the option to apply all changes on startup, it *should* work through a lock there. I'm changing this to a discussion fyi.
