### ISSUE TITLE
42P01: relation "mt_temp_id_list1 error when using Include and documents have one or more duplicated fields

### ISSUE THREAD

**Issue by bittercoder** [JasperFx/marten#3150]
I'm experiencing an issue with the current version of Marten (v7.8.0) similar to the issue reported on #3082 e.g. `42P01: relation "mt_temp_id_list1" does not exist.`

The key difference for me is it's when using just a single include, and the document being queried has a duplicated column (or possibly the child document) then subsequent queries (but not the first) fail.  I also notice the issue only occurs if not explicitly starting a transaction first (if you uncomment the BeginTransactionAsync call in my test it starts passing).

Reproduction included below that fails on the current commit on main https://github.com/JasperFx/marten/commit/b64b96c09b2a0c7446da4b08052033310f8cd5b9

```
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Marten;
using Marten.Schema;
using Marten.Testing.Harness;

namespace LinqTests.Bugs;

public class Bug_3150_trouble_with_repeated_include_and_document_with_duplicated_field : BugIntegrationContext
{
    [Fact]
    public async Task query_multiple_times()
    {
        // if you call BeginTransactionAsync then the issue goes away..
        //await theSession.BeginTransactionAsync(CancellationToken.None);

        async Task DoQuery()
        {
            var children = new Dictionary<Guid, Person3150>();
            await theSession.Query<Person3150>()
                .Include(x => x.ChildId!, children)
                .ToListAsync();
        }

        await DoQuery();

        // second invocation throws MartenCommandException "42P01: relation "mt_temp_id_list1" does not exist"
        await DoQuery();
    }
}

public class Person3150
{
    public Guid Id { get; set; }

    [DuplicateField]
    public string? Name { get; set; }
    public Guid? ChildId { get; set; }
}
```

And here's the stack trace from the failing test on my local:

```
Marten.Exceptions.MartenCommandException
Marten Command Failure:$
$
$
42P01: relation "mt_temp_id_list1" does not exist

POSITION: 73
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Exceptions/MartenExceptionTransformer.cs:line 63
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/MartenLinqQueryProvider.cs:line 131
   at Marten.Linq.MartenLinqQueryable`1.ToListAsync[TResult](CancellationToken token) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/MartenLinqQueryable.cs:line 132
   at LinqTests.Bugs.Bug_3xxx_trouble_with_repeated_include_and_document_with_duplicated_field.<query_multiple_times>g__DoQuery|0_0() in /Users/alexhenderson/dev/jasperfx/marten/src/LinqTests/Bugs/Bug_3xxx_trouble_with_include_and_document_with_duplicated_field.cs:line 23
   at LinqTests.Bugs.Bug_3xxx_trouble_with_repeated_include_and_document_with_duplicated_field.query_multiple_times() in /Users/alexhenderson/dev/jasperfx/marten/src/LinqTests/Bugs/Bug_3xxx_trouble_with_include_and_document_with_duplicated_field.cs:line 31
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 285
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90

Npgsql.PostgresException
42P01: relation "mt_temp_id_list1" does not exist

POSITION: 73
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteReaderAsync(NpgsqlBatch batch, CancellationToken token) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Internal/Sessions/AutoClosingLifetime.cs:line 182
   at Marten.Internal.Sessions.AutoClosingLifetime.ExecuteReaderAsync(NpgsqlBatch batch, CancellationToken token) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Internal/Sessions/AutoClosingLifetime.cs:line 191
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/MartenLinqQueryProvider.cs:line 126
```

**Comment by jeremydmiller** [comment]
You have no earthly idea how utterly sick to death I am of dealing with these kinds of permutation hell problems with the LINQ provider code. Again, it's just not permutation of inputs we've had tests for before. I'll try to get to this before 7.9, but anything around the Include() functionality has a tendency to cause regression problems and takes some time to address.

**Comment by bittercoder** [comment]
Thanks @jeremydmiller really appreciate it - I might take a look at it to see if I can figure it out if I have a spare moment - though that's definitely a fairly deep part of the marten codebase to wrap your head around 😀
