### ISSUE TITLE
Querying duplicated fields regression from 6.4.1

### ISSUE THREAD

**Issue by bittercoder** [JasperFx/marten#3151]
Hi Folks, just wanted to note a small regression we are seeing when upgrading from 6.4.1 to 7.x around duplicated fields and contains/in linq queries when the field is nullable.

So given this document: 

```
public class Person
{
    public Guid Id { get; set; }

    [DuplicateField]
    public Guid? ChildId { get; set; }
}
```

In 6.4.1 both of these tests pass, but in 7.8 they second one now fails.  Based on the error message I'm guessing this will be resolved at some point 😁 but just wanted to raise it as it's been an area where we've needed to update code in a few places as part of the upgrade to v7 for our codebase.

```
[Fact]
    public async Task filtering_by_null_ids_works()
    {
        var p1 = new Person { ChildId = Guid.NewGuid()};
        var p2 = new Person { ChildId = Guid.NewGuid()};
        theSession.Store(p1,p2);
        await theSession.SaveChangesAsync();
        Guid?[] ids = [p1.ChildId];
        var results = await theSession.Query<Person>()
            .Where(x => x.ChildId.In(ids))
            .ToListAsync();
        results.Single().ChildId.ShouldBe(p1.ChildId);
    }

    [Fact]
    public async Task filtering_by_non_null_ids_using_value_fails_regression_from_641()
    {
        var p1 = new Person { ChildId = Guid.NewGuid()};
        var p2 = new Person { ChildId = Guid.NewGuid()};
        theSession.Store(p1,p2);
        await theSession.SaveChangesAsync();
        Guid[] ids = [p1.ChildId.Value];
        var results = await theSession.Query<Person>()
            .Where(x => x.ChildId!.Value.In(ids))
            .ToListAsync();
        results.Single().ChildId.ShouldBe(p1.ChildId);
    }
```

Here's the error message & stack trace:

```
Marten.Exceptions.BadLinqExpressionException
Marten does not (yet) support the method Value in duplicated field querying
   at Marten.Linq.Members.DuplicatedField.FindMember(MemberInfo member) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/Members/DuplicatedField.cs:line 236
   at Marten.Linq.Parsing.LinqInternalExtensions.MemberFor(IHasChildrenMembers collection, Expression expression) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/Parsing/LinqInternalExtensions.cs:line 96
   at Marten.Linq.Parsing.Methods.IsOneOf.Parse(IQueryableMemberCollection memberCollection, IReadOnlyStoreOptions options, MethodCallExpression expression) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/Parsing/Methods/IsOneOf.cs:line 25
   at Marten.Linq.Parsing.WhereClauseParser.VisitMethodCall(MethodCallExpression node) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/Parsing/WhereClauseParser.cs:line 92
   at Marten.Linq.Parsing.WhereClauseParser.Visit(Expression node) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/Parsing/WhereClauseParser.cs:line 41
   at Marten.Linq.SqlGeneration.Statement.ParseWhereClause(IReadOnlyList`1 wheres, IMartenSession session, IQueryableMemberCollection collection, IDocumentStorage storage) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/SqlGeneration/Statement.WhereParsing.cs:line 57
   at Marten.Linq.CollectionUsage.BuildTopStatement(IMartenSession session, IQueryableMemberCollection collection, IDocumentStorage storage, QueryStatistics statistics) in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/CollectionUsage.Compilation.cs:line 38
   at Marten.Linq.Parsing.LinqQueryParser.BuildStatements() in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/Parsing/LinqQueryParser.Statements.cs:line 32
   at Marten.Linq.Parsing.LinqQueryParser.BuildListHandler[T]() in /Users/alexhenderson/dev/jasperfx/marten/src/Marten/Linq/Parsing/LinqQueryParser.Handlers.cs:line 70
   at Marten.Linq.MartenLinqQueryable`1.ToListAsync[TResult](CancellationToken token)
   at LinqTests.Bugs.Bug_3xxx_trouble_with_repeated_include_and_document_with_duplicated_field
```

**Comment by jeremydmiller** [comment]
It was just a gap in our existing test coverage. LINQ is the gift that never stops giving.

**Comment by bittercoder** [comment]
hehe I figured as much 😄  not super urgent as it can be worked around of course, just thought I would flag it up as a minor thing.  All that being said the LINQ support in Marten is amazing in what it does support!
