### ISSUE TITLE
`MaintenanceDatabase(...)` is required for create & drop database operations

### ISSUE THREAD

**Issue by vcaraulean** [JasperFx/marten#3367]
Example snippet:
```
        options.CreateDatabasesForTenants(x =>
        {
            x
                .ForTenant()
                .DropExisting(true)
```

Without specifying `.MaintenanceDatabase(maintenanceConnectionString)` the create or drop will fail:

```
      Npgsql.NpgsqlException (0x80004005): No password has been provided but the backend requires one (in MD5)
         at Npgsql.Internal.NpgsqlConnector.AuthenticateMD5(String username, Byte[] salt, Boolean async, CancellationToken cancellationToken)
         at Npgsql.Internal.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
         at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
         at Marten.Schema.DatabaseGenerator.IsNotInPgDatabase(String catalog, String maintenanceDb, CancellationToken ct) in C:\Dev\Temp\marten\src\Marten\Schema\DatabaseGenerator.cs:line 94
```

Thus, the docs for `MaintenanceDatabase()` are not correct saying
> Setup the maintenance database to which to connect to prior to database creation. If not specified, the store connection string with 'postgres' as database is used.

The `postgres` db is used, but the password is not picked up. The code responsible for that is trying to pull it out from a IDbConnection and the password is hidden there...

So, either docs require an amendment, or the code need to be adapted to build correctly connection string to default database...

**Comment by jeremydmiller** [comment]
@vcaraulean Just updated the docs on this to note that you will need to use Persist Security Info=True in your connection string from your previous issue. That was a change in behavior from the most recent Npgsql.

Why are you doing this btw? Why not just have the named database created as part of your docker compose file?

**Comment by vcaraulean** [comment]
Thanks for the doc update!

We were upgrading to latest Marten one of our 2-3 projects and found this (set of) breaking behavior(s).

We can create db as part of docker-compose, but what we were (traditionally) using is drop-create flow before running our integration tests. We are expecting an empty db when running any of our tests and that was the way we were doing it. I know that there are other ways of cleaning db, but at that time and as most reliable way of resetting the state is to drop the db.

**Comment by vcaraulean** [comment]
Still, thinking about it, doc updates are good but might be better to either throw a relevant exception explaining what need to be done or the code should handle that gracefully and pick the credentials and password to be able to execute the drop...

It will be the least surprise for the people who aren't actually reading the docs but are guided by the fluent API compositions.
