### ISSUE TITLE
"Sequence contains more than one element" exception when using lambda FirstOrDefaultAsync() rather than explicit Where()

### ISSUE THREAD

**Issue by moe-lawrence** [JasperFx/marten#3374]
The following Query fails when there are multiple MyAggregate records (using Marten v7.19.1)

```
        return await sessionContext.Session.Query<MyAggregate>()
            .OrderByDescending(r => r.SubmittedOn)
            .FirstOrDefaultAsync(r => r.Status == RequestStatus.Superseded, cancellationToken: cancellationToken);
```

```
System.InvalidOperationException: Sequence contains more than one element
   at Marten.Linq.QueryHandlers.OneResultHandler`1.HandleAsync(DbDataReader reader, IMartenSession session, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token, SingleValueMode valueMode)
   at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
   at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
   at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
   at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token, SingleValueMode valueMode)
```

when the criteria is instead put in an explicit **.Where()** as below, it works correctly.

```
        return await sessionContext.Session.Query<MyAggregate>()
            .Where(r => r.Status == RequestStatus.Superseded)
              .OrderByDescending(r => r.SubmittedOn)
              .FirstOrDefaultAsync(cancellationToken: cancellationToken);
```

**Comment by jeremydmiller** [comment]
@moe-lawrence "Works on my box" in master with this test:

```csharp
    [Fact]
    public async Task first_or_default_correct_hit_with_more_than_one_match_async_in_combo_with_order_by_2()
    {
        theSession.Store(new Target { Number = 1, AnotherNumber = 10});
        theSession.Store(new Target { Number = 2, Flag = true, AnotherNumber = 30, String = "Correct" });
        theSession.Store(new Target { Number = 2, AnotherNumber = 20, String = "Wrong"});
        theSession.Store(new Target { Number = 4 });
        await theSession.SaveChangesAsync();

        theSession.Logger = new TestOutputMartenLogger(_output);

        var target = await theSession.Query<Target>().OrderByDescending(x => x.AnotherNumber).FirstOrDefaultAsync(x => x.Number == 2, CancellationToken.None);
        target.String.ShouldBe("Correct");
    }
```

I think it's somewhat likely that this has been addressed by subsequent releases and I'd vote you just upgrade to the latest
