### ISSUE TITLE
StreamTypeMissingException when using UseMandatoryStreamTypeDeclaration with StartStream<T>

### ISSUE THREAD

**Issue by I4QvViGzUN0F** [JasperFx/marten#3482]
Hello. I'm having an issue with UseMandatoryStreamTypeDeclaration set to true. My understanding from the docs is that I then need to make sure to call StartStream<T> in the future. I'm doing that but still receiving a StreamTypeMissingException. Here's the code

```
public async Task CreateAggregateStreamAsync<TAggregate>(
    EventContainer eventContainer,
    CancellationToken cancellationToken)
    where TAggregate : class, IAggregate
{
    await using var session = store.LightweightSession(tenantId: eventContainer.Site.ToString());

    session.SetMetaData(eventContainer.Trace, eventContainer.Audit);

    session.Events.StartStream<TAggregate>(eventContainer.AggregateId, eventContainer.Event);

    await session.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

    log.LogInformation(
        "Stream Id {streamId} - Started with event of type {eventType}",
        eventContainer.AggregateId,
        eventContainer.Event.GetType().Name);
}
```

This StartStream call is making it through to Marten code `Marten.Events.EventGraph.StartStream(DocumentSessionBase session, Guid id, params object[] events)` which is then throwing on 

`if (this.UseMandatoryStreamTypeDeclaration) throw new StreamTypeMissingException();`

Here's the stack trace from our `CreateAggregateStreamAsync` down into the Marten code.

```
Marten.Exceptions.StreamTypeMissingException: A stream type declaration is required when starting a new event stream because of the UseMandatoryStreamTypeDeclaration settings. Please use one of the StartStream overloads that take in an stream type instead and supply the stream type (usually an aggregate type)
   at Marten.Events.EventGraph.StartStream(DocumentSessionBase session, Guid id, Object[] events)
   at Marten.Events.EventStore.StartStream(Type aggregateType, Guid id, Object[] events)
   at Marten.Events.EventStore.StartStream[T](Guid id, Object[] events)
   at AllInOne.Common.EventStorage.Marten.Infrastructure.Repositories.MartenAggregateRepository.CreateAggregateStreamAsync[TAggregate](EventContainer eventContainer, CancellationToken cancellationToken)
```

And here's our config code

```
        void Configure(StoreOptions options)
        {
            options.Connection(mtConfig.ConnectionString);

            options.UseSystemTextJsonForSerialization();

            options.DisableNpgsqlLogging = true;

            options.Events.MetadataConfig.CorrelationIdEnabled = true;
            options.Events.MetadataConfig.CausationIdEnabled = true;
            options.Events.MetadataConfig.HeadersEnabled = true;

            options.DatabaseSchemaName = schemaName;

            options.Policies.ForAllDocuments(
                opt =>
                {
                    opt.Metadata.CausationId.Enabled = true;
                    opt.Metadata.CorrelationId.Enabled = true;
                    opt.Metadata.Headers.Enabled = true;
                });

            options.Advanced.DefaultTenantUsageEnabled = false;
            options.Events.TenancyStyle = TenancyStyle.Conjoined;

            if (environment.IsDevelopment())
            {
                options.AutoCreateSchemaObjects = AutoCreate.All;
            }

            options.Events.StreamIdentity = StreamIdentity.AsGuid;

            options.Events.AppendMode = EventAppendMode.Quick;

            options.Events.UseMandatoryStreamTypeDeclaration = true;

            storeOptionsConfig?.Invoke(options);
        }

        return services
            .AddMarten(Configure)
            .UseLightweightSessions();
```

**Comment by jeremydmiller** [comment]
Fixed locally. Will be in next bug fix release. 7.30.3 or 7.31. Probably the first.
