### ISSUE TITLE
Same `type` column for different events from different namespaces when using similar concepts

### ISSUE THREAD

**Issue by pomianowski** [JasperFx/marten#3588]
Let's imagine such a scenario, i store three types of orders - internal, external and delayed. Each of them in their own directory and each of them has a DraftCreated event

```md
.
├── ...
├── InternalOrders
│   ├─├ Events
│   │   └── DraftCreated.cd
│   └─── InternalOrder.cd
├── ExternalOrders
│   ├─├ Events
│   │   └── DraftCreated.cd
│   └─── ExternalOrder.cd
├── DelayedOrders
│   ├─├ Events
│   │   └── DraftCreated.cd
│   └─── DelayedOrder.cd
└── ...
```

I store them using my custom aggregate base class with something like this:
```csharp
public abstract class Stream<TSelf> : IStream
    where TSelf : Stream<TSelf>
{
    [NonSerialized]
    [JsonIgnore]
    private readonly Queue<object> _uncommittedEvents = [];

    public virtual IEnumerable<object> DequeueUncommittedEvents()
    {
        IEnumerable<object> eventsToReturn = new Queue<object>(_uncommittedEvents);

        _uncommittedEvents.Clear();

        return eventsToReturn;
    }
}
```

```csharp
InternalOrder entityToAdd = InternalOrder.CreateDraft("name");

IEnumerable<object> events = entityToAdd.DequeueUncommittedEvents();
_ = session.Events.StartStream(entityToAdd.GetType(), entityToAdd.Id, events);
await session.SaveChangesAsync(cancellationToken);
```
```csharp
ExternalOrder entityToAdd = ExternalOrder.CreateDraft("name", "external-id");

IEnumerable<object> events = entityToAdd.DequeueUncommittedEvents();
_ = session.Events.StartStream(entityToAdd.GetType(), entityToAdd.Id, events);
await session.SaveChangesAsync(cancellationToken);
```

Then I download from the database and recreate them
```csharp
IReadOnlyList<IEvent> events = await session.Events.FetchStreamAsync(informationExchangeId, token: cancellationToken);
var myOrder = InternalOrder.Dequeue(events);
```
```csharp
IReadOnlyList<IEvent> events = await session.Events.FetchStreamAsync(informationExchangeId, token: cancellationToken);
var myOrder = ExternalOrder.Dequeue(events);
```

When trying to dequeue external order i got
```md
Marten.Exceptions.EventDeserializationFailureException: Event deserialization error on sequence = 28
2024-12-10T16:49:22        ---> System.Text.Json.JsonException: JSON deserialization for type 'Orders.InternalOrders.Events.DraftCreated' was missing required properties including: 'some-property', 'some-property', 'some-property', 'some-property', 'attachments'.
2024-12-10T16:49:22          at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
2024-12-10T16:49:22          at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
2024-12-10T16:49:22          at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
2024-12-10T16:49:22          at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
2024-12-10T16:49:22          at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
2024-12-10T16:49:22          at Marten.Services.SystemTextJsonSerializer.FromJsonAsync(Type type, Stream stream, CancellationToken cancellationToken)
2024-12-10T16:49:22          at Marten.Services.SystemTextJsonSerializer.FromJsonAsync(Type type, DbDataReader reader, Int32 index, CancellationToken cancellationToken)
2024-12-10T16:49:22          at Marten.Services.SystemTextJsonSerializer.FromJsonAsync(Type type, DbDataReader reader, Int32 index, CancellationToken cancellationToken)
2024-12-10T16:49:22          at Marten.Events.EventMapping.<>c__DisplayClass60_0.<<JsonTransformation>b__2>d.MoveNext()
```

Guess it is because in the `mt_events` table in the `type` column both have `draft_created`. But in the `dotnet_type` column are the correct types from namespace and assembly, like `Orders.InternalOrders.Events.DraftCreated, OrdersApp`

Is that why? Can I somehow add namespace to `type` column? Or is the error due to something else?

I may use `MapEventType`, and then it works, but some global option with prefix would be nice
```csharp
options.Events
    .MapEventType<Orders.InternalOrders.Events.DraftCreated>("draft_created_internal");
```

Marten is a great library that is a pleasure to work with, thanks in advance for your reply.

**Comment by jeremydmiller** [comment]
Duplicate with https://github.com/JasperFx/marten/issues/2482.

This hasn't come up in quite awhile, and I think I'd thought that this was beaten. Happy to have some kind of PR to override the event type name strategy, but this would have to be an "opt in" strategy. My normal advice is just "don't do that".

Not what you're here for, but I strongly recommend against any kind of custom `AggregateRootBase` like this:

```csharp
public abstract class Stream<TSelf> : IStream
    where TSelf : Stream<TSelf>
{
    [NonSerialized]
    [JsonIgnore]
    private readonly Queue<object> _uncommittedEvents = [];

    public virtual IEnumerable<object> DequeueUncommittedEvents()
    {
        IEnumerable<object> eventsToReturn = new Queue<object>(_uncommittedEvents);

        _uncommittedEvents.Clear();

        return eventsToReturn;
    }
}
```

Our official recommendation is using something more FP-ish like the "aggregate handler workflow" approach with Wolverine + Marten.

**Comment by pomianowski** [comment]
Hey @jeremydmiller, thanks for the quick reply, I would love some opt-in functionality that adds namespace to event `type`.

As for the aggregate base, I wanted to avoid references to Marten in the main domain csproj, hence the small abstraction, below
```csharp
namespace Orders.SeedWork;

public abstract class Stream<TSelf> : IStream
    where TSelf : Stream<TSelf>
{
    [NonSerialized]
    [JsonIgnore]
    private readonly Queue<object> _uncommittedEvents = [];

    public Guid Id { get; protected set; } = default!;

    protected void DequeueStream(IEnumerable<object> events)
    {
        foreach (object singleEvent in events)
        {
            When(singleEvent);
        }
    }

    public virtual IEnumerable<object> DequeueUncommittedEvents()
    {
        IEnumerable<object> eventsToReturn = new Queue<object>(_uncommittedEvents);

        _uncommittedEvents.Clear();

        return eventsToReturn;
    }

    protected TSelf AddDomainEvent(object @event)
    {
        Enqueue(@event);

        When(@event);

        return (TSelf)this;
    }

    protected virtual void When(object @event)
    {
        if (@event is IStreamEvent streamEvent)
        {
            if (Id != Guid.Empty)
            {
                if (streamEvent.Id != Guid.Empty && streamEvent.Id != Id)
                {
                    throw new InvalidOperationException("Event Id does not match entity Id.");
                }

                streamEvent.Id = Id;
            }
        }
    }

    protected void Enqueue(object @event)
    {
        _uncommittedEvents.Enqueue(@event);
    }
}

```
which results in something like

```csharp
public sealed class InternalOrder: Stream<InternalOrder>, IOrder
{
    public string? ProcessInstanceId { get; private set; }

    public InternalOrder AssignProcessInstanceId(string processInstanceId)
    {
        ArgumentNullException.ThrowIfNull(processInstanceId);

        ProcessInstanceIdAssigned @event = new() { ProcessInstanceId = processInstanceId };

        return AddDomainEvent(@event);
    }

    public static InternalOrder CreateDraft(
        Guid businessKey
    )
    {
        ArgumentNullException.ThrowIfNull(businessKey);

        InternalOrder order = new();

        DraftCreated @event =
            new()
            {
                Id = businessKey,
            };

        return order.AddDomainEvent(@event);
    }

    public static InternalOrder Dequeue(IEnumerable<IStreamEvent> events)
    {
        InternalOrder order = new();

        order .DequeueStream(events);

        return process;
    }

    protected override void When(object @event)
    {
        switch (@event)
        {
            case DraftCreated e:
                Id = e.Id;
                break;

            case ProcessInstanceIdAssigned e:
                ProcessInstanceId = e.ProcessInstanceId;
                break;

            default:
                throw new EventNotImplementedException(@event);
        }

        base.When(@event);
    }
}
```

As for your comment i see https://github.com/JasperFx/wolverine/issues/935,

Can I use this template like below without Marten/Wolverine references? Sorry if this is a trivial question but I don't know the whole ecosystem that well

```csharp
[AggregateHandler(typeof(SomeAggregate))]
public static class SomeAggregateHandler
{
    // To start the aggregate. Would be able to follow the same rules for message signatures 
    public static Events Start(command)
    {
         // Naming convention does a new stream
    }

    // Enable Wolverine to use the workflow w/o having to first build the aggregate. 
    // There's not *always* a need to do the validation
    // Might require a Marten FetchForWriting() that doesn't do the aggregation????
    public static IEnumerable<object> Handle(command)
    {

    }

    // IF the aggregate is updated through an Inline projection, make sure you don't
    // double fetch so that the aggregate is used for the projection as well
    public static IEnumerable<object> Handle(command, aggregate)
    {

    }
}
```
