### ISSUE TITLE
Periodic failure in LoadDocumentAsync()

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#375]
See this, only seems to happen when running the tests from the CLI, but happens often enough to be a pain:

```
System.InvalidOperationException: No row is available
   at Npgsql.NpgsqlDataReader.CheckRow()
   at Npgsql.NpgsqlDataReader.GetString(Int32 ordinal)
   at Marten.QuerySession.<>c__DisplayClass15_0`1.<<LoadDocumentAsync>b__0>d.MoveNext() in C:\code\marten\src\Marten\QuerySession.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Marten.Services.ManagedConnection.<ExecuteAsync>d__22`1.MoveNext() in C:\code\marten\src\Marten\Services\ManagedConnection.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Marten.Schema.Resolver`1.<>c__DisplayClass19_0.<<ResolveAsync>b__0>d.MoveNext() in C:\code\marten\src\Marten\Schema\Resolver.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Marten.Services.NulloIdentityMap.<GetAsync>d__5`1.MoveNext() in C:\code\marten\src\Marten\Services\NulloIdentityMap.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Marten.Testing.Events.Projections.inline_transformation_of_events.<<async_projection_of_events>b__7_2>d.MoveNext() in C:\code\marten\src\Marten.Testing\Events\Projections\inline_transformation_of_events.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.InvalidOperationException: An operation is already in progress.
   at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState)
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReaderInternalAsync>d__104.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReaderAsync>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Marten.QuerySession.<>c__DisplayClass15_0`1.<<LoadDocumentAsync>b__0>d.MoveNext() in C:\code\marten\src\Marten\QuerySession.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Marten.Services.ManagedConnection.<ExecuteAsync>d__22`1.MoveNext() in C:\code\marten\src\Marten\Services\ManagedConnection.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDeburake aborted!
Command failed with status (1): [packages/xunit.runner.console/tools/xunit....]
C:/code/marten/rakefile.rb:91:in `block in <top (required)>'
Tasks: TOP => default => test
(See full trace by running task with --trace)

C:\code\marten>
```

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/pull/409
