### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by tim-cools** [JasperFx/marten#482]
```
==============================
==============================
All ActiveProject views match!
==============================
==============================
All ActiveProject views match!
==============================
==============================
All ActiveProject views match!
==============================
==============================
All ActiveProject views match!
==============================
    Marten.Testing.Events.query_against_event_documents_Tests.can_fetch_all_events_before_now [FAIL]
      Shouldly.ShouldAssertException : results.Count
    should be
0
    but was
      4
      Stack Trace:
           at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
           at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
           at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected)
        Events\query_against_event_documents_Tests.cs(115,0): at Marten.Testing.Events.query_against_event_documents_Tests.can_fetch_all_events_before_now()
    Marten.Testing.Events.query_against_event_documents_Tests.can_fetch_all_events_after_now [FAIL]
      Shouldly.ShouldAssertException : results.Count
    should be
4
    but was
      0
      Stack Trace:
           at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
           at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
           at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected)
        Events\query_against_event_documents_Tests.cs(101,0): at Marten.Testing.Events.query_against_event_documents_Tests.can_fetch_all_events_after_now()
    Marten.Testing.Schema.DocumentSchemaOnOtherSchemaTests.fixing_bug_343_double_export_of_events [FAIL]
      System.UnauthorizedAccessException : Access to the path 'C:\_\Marten\git-tim-cools\src\Marten.Testing\bin\Debug\net46\win7-x64\bin\allsql\all.sql' is denied.
      Stack Trace:
           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
           at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
           at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
           at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
           at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
        C:\_\Marten\git-tim-cools\src\Marten\Schema\DocumentSchema.cs(414,0): at Marten.Schema.DocumentSchema.writeDatabaseSchemaGenerationScript(String directory, FileSystem system, ISchemaObjects[] schemaObjects)
        C:\_\Marten\git-tim-cools\src\Marten\Schema\DocumentSchema.cs(303,0): at Marten.Schema.DocumentSchema.WriteDDLByType(String directory)
        Schema\DocumentSchemaOnOtherSchemaTests.cs(289,0): at Marten.Testing.Schema.DocumentSchemaOnOtherSchemaTests.fixing_bug_343_double_export_of_events()
    Marten.Testing.Bugs.Bug_449_Cant_call_delete_with_guid.can_query_with_is_one_of_on_an_enum_type_with_jil [FAIL]
      Marten.Schema.InvalidDocumentException : Could not determine an 'id/Id' field or property for requested document type System.Guid
      Stack Trace:
        C:\_\Marten\git-tim-cools\src\Marten\StoreOptions.cs(122,0): at Marten.StoreOptions.<>c__DisplayClass34_0.<MappingFor>b__0(Type type)
           at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
        C:\_\Marten\git-tim-cools\src\Marten\StoreOptions.cs(112,0): at Marten.StoreOptions.MappingFor(Type documentType)
        C:\_\Marten\git-tim-cools\src\Marten\StoreOptions.cs(256,0): at Marten.StoreOptions.<>c__DisplayClass59_1.<FindMapping>b__0(Type type)
           at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
        C:\_\Marten\git-tim-cools\src\Marten\StoreOptions.cs(251,0): at Marten.StoreOptions.FindMapping(Type documentType)
        C:\_\Marten\git-tim-cools\src\Marten\Schema\DocumentSchema.cs(167,0): at Marten.Schema.DocumentSchema.MappingFor(Type documentType)
        C:\_\Marten\git-tim-cools\src\Marten\Schema\DocumentSchema.cs(191,0): at Marten.Schema.DocumentSchema.<>c__DisplayClass29_0.<StorageFor>b__0(Type type)
           at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
        C:\_\Marten\git-tim-cools\src\Marten\Schema\DocumentSchema.cs(189,0): at Marten.Schema.DocumentSchema.StorageFor(Type documentType)
        C:\_\Marten\git-tim-cools\src\Marten\DocumentSession.cs(54,0): at Marten.DocumentSession.Delete[T](T entity)
        Bugs\Bug_449_IsOneOf_query_with_enum_types - Copy.cs(22,0): at Marten.Testing.Bugs.Bug_449_Cant_call_delete_with_guid.can_query_with_is_one_of_on_an_enum_type_with_jil()
  Finished:    Marten.Testing
=== TEST EXECUTION SUMMARY ===
   Marten.Testing  Total: 1182, Errors: 0, Failed: 4, Skipped: 0, Time: 81.050s
SUMMARY: Total: 2 targets, Passed: 0, Failed: 2.
rake aborted!
Command failed with status (1): [dotnet test...]
C:/_/Marten/git-tim-cools/rakefile.rb:98:in `block in <top (required)>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by tim-cools** [comment]
I try to looking into them later when I can free some time.

**Comment by jeremydmiller** [comment]
@tim-cools You might try pulling the latest with this one: https://github.com/JasperFx/marten/pull/483.

DateTime/DateTimeOffset's have now surpassed Enum's as the biggest headache in Marten

**Comment by tim-cools** [comment]
@jeremydmiller thx, that did the trick for those tests! The first time I ran it I had another test failing: 

```
Marten.Testing.Linq.query_with_any_within_child_collection_Tests.can_query_with_an_any_operator_that_does_a_multiple_search_within_the_collection [FAIL]
      Shouldly.ShouldAssertException : d6f29b93-813e-4ccf-baa3-476be6408f97
    should be
476b544f-30d9-4c59-a731-5c6f37e108b1
    but was not
      Stack Trace:
           at Shouldly.ShouldlyCoreExtensions.AssertAwesomely[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Func`1 customMessage, String shouldlyMethod)
           at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected, Func`1 customMessage)
           at Shouldly.ShouldBeTestExtensions.ShouldBe[T](T actual, T expected)
        C:\_\Marten\git-tim-cools\src\Marten.Testing\SpecificationExtensions.cs(100,0): at Marten.Testing.SpecificationExtensions.ShouldHaveTheSameElementsAs(IList actual, IList expected)
        C:\_\Marten\git-tim-cools\src\Marten.Testing\SpecificationExtensions.cs(76,0): at Marten.Testing.SpecificationExtensions.ShouldHaveTheSameElementsAs[T](IEnumerable`1 actual, T[] expected)
        C:\_\Marten\git-tim-cools\src\Marten.Testing\Linq\query_with_any_within_child_collection_Tests.cs(71,0): at Marten.Testing.Linq.query_with_any_within_child_collection_Tests.can_query_with_an_any_operator_that_does_a_multiple_search_within_the_collection()
  Finished:    Marten.Testing
=== TEST EXECUTION SUMMARY ===
   Marten.Testing  Total: 1108, Errors: 0, Failed: 1, Skipped: 0, Time: 74,262s
Project Marten (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Marten.Testing.OtherAssembly (.NETFramework,Version=v4.6) was previously compiled. Skipping compilation.
Project Marten.Testing (.NETFramework,Version=v4.6) will be compiled because Input items removed from last build
```

The second time I ran it the the test didn't fail though.

**Comment by jeremydmiller** [comment]
@tim-cools That one's been failing periodically for awhile. I just need to go into that test and have it do some sorting before it compares data to make it consistent
