### ISSUE TITLE
Searching within Child Collections fails when used in Compiled Queries

### ISSUE THREAD

**Issue by kedarvaidya** [JasperFx/marten#503]
### Following code fails with KeyNotFoundException
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using Marten;
using Marten.Linq;

namespace MartenTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var store = DocumentStore.For(_ => {
             _.Connection("Host=localhost;Username=someuser;Password=mypassword;Database=marten-test");

                _.Logger(new ConsoleMartenLogger());
            }))
            {
                using (var session = store.OpenSession())
                {
                    var outer = new Outer();
                    outer.Inners.Add(new Inner() { Type = "T1", Value = "V11" });
                    outer.Inners.Add(new Inner() { Type = "T1", Value = "V12" });
                    outer.Inners.Add(new Inner() { Type = "T2", Value = "V21" });

                    session.Store(outer);
                    session.SaveChanges();
                }

                using (var session2 = store.OpenSession())
                {
                    // This works
                    var o1 = session2.Query<Outer>().FirstOrDefault(o => o.Inners.Any(i => i.Type == "T1" && i.Value == "V12"));
                    Console.WriteLine("Found using normal query: " + o1.Id);

                    // This throws KeyNotFoundException. Stacktrace added below
                    var o2 = session2.Query(new FindOuterByInner("T1", "V2"));
                    Console.WriteLine("Found using compiled query: " + o2.Id);
                }
            }
        }
    }

    public class Outer
    {
        public Guid Id { get; set; }

        public IList<Inner> Inners { get; } = new List<Inner>();
    }

    public class Inner
    {
        public string Type { get; set; }

        public string Value { get; set; }
    }

    public class FindOuterByInner : ICompiledQuery<Outer, Outer>
    {
        public string Type { get; private set; }

        public string Value { get; private set; }

        public FindOuterByInner(string type, string value)
        {
            this.Type = type;
            this.Value = value;
        }

        public Expression<Func<IQueryable<Outer>, Outer>> QueryIs()
        {
            return q => q.FirstOrDefault(o => o.Inners.Any(i => i.Type == Type && i.Value == Value));
        }
    }
}
```

### Console Output
```
select public.mt_upsert_outer(doc := :p0, docDotNetType := :p1, docId := :p2, docVersion := :p3);
Persisted 0 updates, 1 inserts, and 0 deletions
select d.data, d.id, d.mt_version from public.mt_doc_outer as d where d.data @> :arg0 LIMIT 1
Found using normal query: 2c1073a6-de4f-4d7f-9d44-f7703247e6f0

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Marten.Util.TypeMappings.GetPgType(Type memberType)
   at Marten.Schema.Field..ctor(MemberInfo[] members)
   at Marten.Schema.Field..ctor(MemberInfo member)
   at Marten.Schema.JsonLocatorField..ctor(StoreOptions options, EnumStorage enumStyle, MemberInfo member)
   at Marten.Schema.DocumentMapping.<>c__DisplayClass103_0.<FieldFor>b__0(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.Schema.DocumentMapping.FieldFor(MemberInfo member)
   at Marten.Schema.DocumentMapping.FieldFor(IEnumerable`1 members)
   at Marten.Linq.CompiledQueryMemberExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Marten.Linq.CompiledQueryMemberExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Marten.Linq.CompiledQueryMemberExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Marten.Linq.QueryHandlers.QueryHandlerFactory.findSetters(IQueryableDocument mapping, Type queryType, Expression expression, EnumStorage enumStorage)
   at Marten.Linq.QueryHandlers.QueryHandlerFactory.buildCachedQuery[TDoc,TOut](Type queryType, ICompiledQuery`2 query)
   at Marten.Linq.QueryHandlers.QueryHandlerFactory.HandlerFor[TDoc,TOut](ICompiledQuery`2 query)
   at Marten.QuerySession.Query[TDoc,TOut](ICompiledQuery`2 query)
   at MartenTest.Program.Main(String[] args)
```

**Comment by jeremydmiller** [comment]
Got it. I'll take a look at it tomorrow morning.

**Comment by jeremydmiller** [comment]
@kedarvaidya Ouch. This one's going to take some effort. I'm gonna try to do it now, but I'm timeboxed so it might be tomorrow instead.

**Comment by jenspettersson** [comment]
We have the same error, but when using a regular query and checking child objects for null:

```
public class Possible_Bug_query_on_null_complex_object : IntegratedFixture
{
    [Fact]
    public void should_not_blow_up_when_querying_for_null_object()
    {
        using (var sessionOne = theStore.OpenSession())
        {
            sessionOne.Store(new Target {String = "Something", Inner = new Target(), AnotherString = "first"});
            sessionOne.Store(new Target {String = "Something", Inner = null, AnotherString = "second"});
                
            sessionOne.SaveChanges();
        }

        using (var querySession = theStore.QuerySession())
        {
            //goes boom
            var targets = querySession.Query<Target>()
                .Where(x => x.String == "Something" && x.Inner != null)
                .ToList();

            targets.Count.ShouldBe(1);
            targets.First().AnotherString.ShouldBe("first");
        }
    }
}
```

But a quick fix in the `TypeMappings.cs` to default to `'jsonb'` instead of letting it throw on a KeyNotFound because the type didn't exist worked fine for us. Not sure what implications that might have for something else. The tests still passes however...

```
public static string GetPgType(Type memberType)
{
.
.
.
	if (PgTypes.ContainsKey(memberType))
		return PgTypes[memberType];

	return "jsonb";
}
```

Not tested with compiled queries however. Can always do a PR for this quick fix, but as I said, not sure it's good enough...

**Comment by jeremydmiller** [comment]
@jenspettersson I found the default type mapping problem you did and got past KeyNotFoundException, but the compiled query issue here is something else. This one's going to take some effort to address unfortunately.
