### ISSUE TITLE
support for queryable interfaces (query over different documents)

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#623]
If you can't use hierarchies / subclassed documents, we could introduce an interface to query for different kind of documents. Sample:
```
public interface IHasAddressID {
	int AddressID {get;set;}
}
public class Location: IHasAddressID {
	public ...
	public int AddressID {get;set;}
}

public class Person: IHasAddressID {
	public ...
	public int AddressID {get;set;}
}

IHasAddressID[] items = session.Query<IHasAddressID>().Where(x => x.AddressID == 100).ToArray();
```
the query should query all persistent documents that implement IHasAddressID, for example using a union sql query or a multiple resultset datareader.

**Comment by jeremydmiller** [comment]
@mdissel Have you tried this out and it didn't work? Using an interface should already be supported through the hierarchical persistence option. Pretty sure that's something that @nieve specifically tested against.

**Comment by mdissel** [comment]
no, does not work..

see https://github.com/mdissel/marten/blob/QueryInterfaces/src/Marten.Testing/query_by_interface_Tests.cs

```
at Marten.StoreOptions.<>c__DisplayClass34_0.<MappingFor>b__0(Type type) in D:\Source\GitHub\marten\marten\src\Marten\StoreOptions.cs:line 121
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.StoreOptions.MappingFor(Type documentType) in D:\Source\GitHub\marten\marten\src\Marten\StoreOptions.cs:line 111
   at Marten.StoreOptions.<>c__DisplayClass62_1.<FindMapping>b__0(Type type) in D:\Source\GitHub\marten\marten\src\Marten\StoreOptions.cs:line 277
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.StoreOptions.FindMapping(Type documentType) in D:\Source\GitHub\marten\marten\src\Marten\StoreOptions.cs:line 272
   at Marten.Schema.DocumentSchema.MappingFor(Type documentType) in D:\Source\GitHub\marten\marten\src\Marten\Schema\DocumentSchema.cs:line 176
   at Marten.Schema.DocumentSchema.EnsureStorageExists(Type documentType) in D:\Source\GitHub\marten\marten\src\Marten\Schema\DocumentSchema.cs:line 193
   at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel) in D:\Source\GitHub\marten\marten\src\Marten\Linq\MartenQueryExecutor.cs:line 71
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Marten.Testing.query_by_interface_Tests.query() in D:\Source\GitHub\marten\marten\src\Marten.Testing\query_by_interface_Tests.cs:line 59
Result Message:	Could not determine an 'id/Id' field or property for requested document type Marten.Testing.query_by_interface_Tests+IHasAddressID


```

**Comment by jeremydmiller** [comment]
@mdissel Can you please go read the documentation I linked to up above? It's not magic, you have to tell Marten about the types you want persisted under the interface.

**Comment by mdissel** [comment]
I register the interface as hierarchy, but be aware it is NOT a hierarchy.. Two different class, in two different tables, only sharing one ore more columns.
Changed the test, no exception, but not the correct result.
(change pushed to github)

**Comment by jeremydmiller** [comment]
You're really wanting something completely different here, right? You're looking for Marten to magically look over known document types that implement that interface and apply the query against each?

**Comment by mdissel** [comment]
Yes!.. 
For example:
Check if the address can be removed and see if it's anywhere referenced

**Comment by jeremydmiller** [comment]
And you know exactly what my reply is going to be:

_Sounds like a great pull request_

I'd make that be a semantically different operation. Something like:

```
session.UnionQuery<IHasAddress>().Where(x => ).ToList();
```

It'll make the implementation easier and you really need to let the user know that there's something unusual happening performance wise here.

**Comment by mdissel** [comment]
> And you know exactly what my reply is going to be:

Of course, but first agree if it's usefull and than how and than coding..

**Comment by jeremydmiller** [comment]
I do see the value. There's something conceptually similar in the StructureMap diagnostics.

**Comment by mysticmind** [comment]
Closing this. No recent activity.
