### ISSUE TITLE
Issue upgrading from 1.25 to 1.30

### ISSUE THREAD

**Issue by yetanotherchris** [JasperFx/marten#680]
Thanks for the great library, it's nice to finally have an API as easy to use as the MongoDB one but with less overhead (atleast with Docker).

 I've recently upgraded to 1.30 in a .NET Core 1.1 class library and now have the follwing issue in an integration test:

        System.ArgumentOutOfRangeException : Index and count must refer to a location within the string.
        Parameter name: destinationIndex
        at System.String.CopyTo(Int32 sourceIndex, Char[] destination, Int32 destinationIndex, Int32 count)
        at Marten.Services.CharArrayTextWriter.Write(String value)
        at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
        at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
        at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
        at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
        at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
        at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
        at Newtonsoft.Json.JsonSerializer.Serialize(TextWriter textWriter, Object value)
        at Marten.Services.JsonNetSerializer.ToJson(Object document, TextWriter writer)
        at lambda_method(Closure , SprocCall , EncryptedItem , UpdateBatch , DocumentMapping , Nullable`1 , Guid )
        at Marten.Schema.Resolver`1.RegisterUpdate(UpdateBatch batch, Object entity, String json)
        at Marten.Schema.Resolver`1.RegisterUpdate(UpdateBatch batch, Object entity)
        at Marten.Services.Upsert.Persist(UpdateBatch batch, IDocumentSchema schema)
        at Marten.Services.UnitOfWork.determineChanges(UpdateBatch batch)
        at Marten.Services.UnitOfWork.buildChangeSet(UpdateBatch batch)
        at Marten.Services.UnitOfWork.ApplyChanges(UpdateBatch batch)
        at Marten.DocumentSession.SaveChanges()
        at Letmein.Core.Repositories.Postgres.TextRepository.Save(EncryptedItem encryptedItem) in C:\code\letmein\src\Letmein.Core\Repositories\Postgres\TextRepository.cs:line 46
        at Letmein.Tests.Integration.TextRepositoryTests.Load_should_loads_entity_and_Save_should_store() in C:\code\letmein\src\Letmein.Tests\Integration\TextRepositoryTests.cs:line 36

The code in question is a really simple POCO repository:

    public void Save(EncryptedItem encryptedItem)
    {
        using (IDocumentSession session = _store.LightweightSession())
        {
            session.Store(encryptedItem);
            session.SaveChanges();
        }
    }

And the test (it's a big dodgy in that it tests both loading and testing):

    [Test]
    public void Load_should_loads_entity_and_Save_should_store()
    {
        // Arrange
        var encryptedItem = new EncryptedItem()
        {
            Id = Guid.NewGuid(),
            AlgorithmName = "AES",
            CipherJson = new string('a', 512 * 1024 * 2),
            FriendlyId = "foo",
            CreatedOn = DateTime.UtcNow
        };

        _repository.Save(encryptedItem);

        // Act
        EncryptedItem loadedItem = _repository.Load(encryptedItem.FriendlyId);

        // Assert
        Assert.NotNull(loadedItem);
        Assert.That(loadedItem.Id, Is.EqualTo(encryptedItem.Id));
        Assert.That(loadedItem.AlgorithmName, Is.EqualTo(encryptedItem.AlgorithmName));
        Assert.That(loadedItem.FriendlyId, Is.EqualTo(encryptedItem.FriendlyId));
        Assert.That(loadedItem.CreatedOn, Is.EqualTo(encryptedItem.CreatedOn));
    }

**Comment by jeremydmiller** [comment]
@Scooletz Do you have any thoughts on this one?

@yetanotherchris Does it happen consistently, or periodically?

**Comment by Scooletz** [comment]
A temporary fix: disable buffers on the store level. 
I'll take a look at it today/tomorrow.

**Comment by Scooletz** [comment]
This is the assertion that fails in `string.CopyTo`. Will update soon on progress.

```
if (destinationIndex > destination.Length - count || destinationIndex < 0)
        throw new ArgumentOutOfRangeException("destinationIndex", Environment.GetResourceString("ArgumentOutOfRange_IndexCount"));
```

**Comment by Scooletz** [comment]
Ping @jeremydmiller I issued the PR that fixes this behavior. Requires a fix release. 

Still, we should consider how do we want to handle docs that are 1MB long. Is a single buffer good enough? Or maybe I need to think about another `npgsql` PR that could use some kind of chaining for string params? Do you want to raise a separate issue @jeremydmiller ?

**Comment by jeremydmiller** [comment]
Addressed by https://github.com/JasperFx/marten/pull/682. 

@Scooletz I can't say that I understand the implications of that one offhand. I say we should wait and see if there are any issues in the wild first.
