### ISSUE TITLE
Marten fails to detect an index which already exists in the database

### ISSUE THREAD

**Issue by mariusin79** [JasperFx/marten#799]
Error message:

DDL Execution for 'SchemaDiff for Foss.Domain.Write.Schedule.Stream' Failed!

CREATE INDEX mt_doc_stream_idx_encoder_id ON foss.mt_doc_stream ("encoder_id");

The index is generated because of:

    public class ForeignKeys : MartenRegistry
    {
        public ForeignKeys()
        {
            For<Stream>().ForeignKey<EncoderSchedule>(s => s.EncoderId);
        }
    }

If I nuke the database and restart everything works as expected: The index is generated the first time the entity is used within a session. If I stop the program and restart it fails with the above exception the first time the entity is used within a session. If I drop the custom schema it works as expected so I am guessing that the bug is provoked by this nifty little creature:

                    return DocumentStore.For(options =>
                    {
                        options.DatabaseSchemaName = "foss";

**Comment by mariusin79** [comment]
Stacktrace:

   at Marten.Schema.DocumentSchema.Marten.Schema.IDDLRunner.Apply(Object subject, String ddl)
   at Marten.Schema.SchemaDiff.<>c__DisplayClass19_0.<CreatePatch>b__0(String x)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Schema.SchemaDiff.CreatePatch(StoreOptions options, SchemaPatch patch)
   at Marten.Schema.DocumentSchemaObjects.buildOrModifySchemaObjects(SchemaDiff diff, AutoCreate autoCreateSchemaObjectsMode, IDocumentSchema schema, SchemaPatch runner)
   at Marten.Schema.DocumentSchemaObjects.GenerateSchemaObjectsIfNecessary(AutoCreate autoCreateSchemaObjectsMode, IDocumentSchema schema, SchemaPatch patch)
   at Marten.Schema.DocumentSchema.<>c__DisplayClass57_0.<buildSchemaObjectsIfNecessary>b__2(IDocumentMapping x)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Schema.DocumentSchema.buildSchemaObjectsIfNecessary(IDocumentMapping mapping)
   at Marten.Schema.DocumentSchema.EnsureStorageExists(Type documentType)
   at Marten.Linq.MartenQueryable`1.executeAsync[TResult](Func`2 source, CancellationToken token)
   at Marten.Linq.MartenQueryable`1.ToListAsync[TResult](CancellationToken token)
   at Marten.QueryableExtensions.ToListAsync[T](IQueryable`1 queryable, CancellationToken token)

**Comment by jeremydmiller** [comment]
@mariusin79 What's the sql it's generating when it fails? And what does Stream and EncoderSchedule look like? Any way you could add a failing test as a PR to Marten for this?

**Comment by mariusin79** [comment]
The statement which it tries to execute is this:

CREATE INDEX mt_doc_stream_idx_encoder_id ON foss.mt_doc_stream ("encoder_id")

And the error is this:

"42P07: relation \"mt_doc_stream_idx_encoder_id\" already exists"

I think the problem is that the DDL diffing logic disregards the user specified db schema. If I remove the user specified schema, everything works as expected. Please note: As a test I manually patched the db using the generated sql (store.Schema.WriteDDL(@"..")) and turned off schema generation (options.AutoCreateSchemaObjects = AutoCreate.None;). This works fine with no user-specified schema and fails with:

    System.InvalidOperationException: 'No document storage exists for type Foss.Domain.Write.Schedule.Stream and cannot be created dynamically unless the StoreOptions.AutoCreateSchemaObjects is greater than "None". See http://jasperfx.github.io/marten/documentation/documents/ for more information

if a schema is specified. Theese errors are pointing in the direction that the DDL-logic fails to respect a user-specified schema in some cases.

**Comment by mariusin79** [comment]
This test fails if you name the custom schema with the same name as the database the schema resides in, note: any other custom schema name works.

        [Test]
        public void CustomSchemaFails()
        {
            var store = DocumentStore.For(options =>
            {
                options.DatabaseSchemaName = "namethiswiththesamenameasthedatabase";
                options.Connection("..");
                options.Schema.Include<ForeignKeys>();
            });

            using (var session = store.LightweightSession())
            {
                session.Store(new EncoderSchedule { Id = "a" });
                session.Store(new Stream { Id = Guid.NewGuid()});
                session.SaveChanges();
            }

            var store2 = DocumentStore.For(options =>
            {
                options.DatabaseSchemaName = "namethiswiththesamenameasthedatabase";
                options.Connection(..);
                options.Schema.Include<ForeignKeys>();
                options.AutoCreateSchemaObjects = AutoCreate.None;
            });

            using (var session = store2.LightweightSession())
            {
                var schedule = session.Load<EncoderSchedule>("a");
                schedule.Streams = session.Query<Stream>().Where(s => s.EncoderId == schedule.Id).ToArray();

                foreach (var doc in schedule.Streams)
                {
                    Console.WriteLine(doc.Id);
                }
            }


        }

        public class EncoderSchedule
        {
            public string Id { get; set; }

            [JsonIgnore]
            public IList<Stream> Streams { get; set; }
        }

        public class Stream
        {
            public Guid Id { get; set; }
            public string EncoderId { get; set; }
        }

        public class ForeignKeys : MartenRegistry
        {
            public ForeignKeys()
            {
                For<Stream>().ForeignKey<EncoderSchedule>(s => s.EncoderId);
            }
        }

**Comment by thomasrosdahl** [comment]
You also get the same behavior if the database username is the same as the schema name.

StackTrace:

Failed!

CREATE INDEX mt_doc_[entityName]_idx_data ON [schemaName].mt_doc_[entityName] USING gin (\"data\" jsonb_path_ops); ---> Npgsql.PostgresException: 42P07: relation \"mt_doc_[entityName]_idx_data\" already exists
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlDataReader.<NextResult>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<Execute>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Marten.ConnectionFactoryExtensions.RunSql(IConnectionFactory factory, String sql)
   at Marten.Schema.DocumentSchema.Marten.Schema.IDDLRunner.Apply(Object subject, String ddl)
   --- End of inner exception stack trace ---
   at Marten.Schema.DocumentSchema.Marten.Schema.IDDLRunner.Apply(Object subject, String ddl)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Schema.SchemaDiff.CreatePatch(StoreOptions options, SchemaPatch patch)
   at Marten.Schema.DocumentSchemaObjects.buildOrModifySchemaObjects(SchemaDiff diff, AutoCreate autoCreateSchemaObjectsMode, IDocumentSchema schema, SchemaPatch runner)
   at Marten.Schema.DocumentSchemaObjects.GenerateSchemaObjectsIfNecessary(AutoCreate autoCreateSchemaObjectsMode, IDocumentSchema schema, SchemaPatch patch)
   at Baseline.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Linq.MartenQueryable`1.executeAsync[TResult](Func`2 source, CancellationToken token)
   at Marten.Linq.MartenQueryable`1.ToListAsync[TResult](CancellationToken token)
   at Marten.QueryableExtensions.ToListAsync[T](IQueryable`1 queryable, CancellationToken token)

**Comment by rjrnation23** [comment]
Is there any work around or resolution to this error?  I am currently encountering the same error.

**Comment by jeremydmiller** [comment]
@rjrnation23 I've been bandwidth constrained lately. This wouldn't be that crazy a place for someone else to jump in if anybody one this issue are interested in taking it on

**Comment by droach282** [comment]
I volunteer as tribute!

**Comment by jeremydmiller** [comment]
@mariusin79 @rjrnation23 @thomasrosdahl -->

Not what any of you want to hear, but "works on my machine"

There was a change in 2.4 for how Marten went looking for existing schema objects based on the wacky authorization model we use at work. If you're getting this problem in 2.5, could you try dropping back to 2.3 and see if that changes anything? Or go forward if you're on an older version?

Failing that, I might just see if you could run this sql in your db:

```
SELECT
  U.usename                AS user_name,
  ns.nspname               AS schema_name,
  pg_catalog.textin(pg_catalog.regclassout(idx.indrelid :: REGCLASS)) AS table_name,
  i.relname                AS index_name,
  pg_get_indexdef(i.oid) as ddl,
  idx.indisunique          AS is_unique,
  idx.indisprimary         AS is_primary,
  am.amname                AS index_type,
  idx.indkey,
       ARRAY(
           SELECT pg_get_indexdef(idx.indexrelid, k + 1, TRUE)
           FROM
             generate_subscripts(idx.indkey, 1) AS k
           ORDER BY k
       ) AS index_keys,
  (idx.indexprs IS NOT NULL) OR (idx.indkey::int[] @> array[0]) AS is_functional,
  idx.indpred IS NOT NULL AS is_partial
FROM pg_index AS idx
  JOIN pg_class AS i
    ON i.oid = idx.indexrelid
  JOIN pg_am AS am
    ON i.relam = am.oid
  JOIN pg_namespace AS NS ON i.relnamespace = NS.OID
  JOIN pg_user AS U ON i.relowner = U.usesysid
WHERE 
  NOT nspname LIKE 'pg%' AND 
  i.relname like 'mt_%';
```

**Comment by jeremydmiller** [comment]
No recent activity on this, and "works on my box". I'm closing this.
