### ISSUE TITLE
Exception when inserting large number of records

### ISSUE THREAD

**Issue by dnnbuddy** [JasperFx/marten#811]
When we insert large number of records to a table we get the following exception. This is very uncommon, and we get the error with no clue. Please find the stack trace pasted below. Any clue is highly appreciated. Marten and Npsql versions used are mentioned below.

<package id="Marten" version="1.5.2" targetFramework="net462" />
<package id="Npgsql" version="3.2.4.1" targetFramework="net462" />

`
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlDataReader.<NextResult>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<Execute>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<ExecuteScalar>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteScalar()
   at Marten.Schema.Identity.Sequences.HiloSequence.AdvanceToNextHi()
   at Marten.Schema.Identity.Sequences.HiloSequence.NextLong()
   at Marten.Schema.Identity.Sequences.HiloSequence.NextInt()
   at Marten.Schema.Identity.Sequences.IntHiloGenerator.Assign(Int32 existing, Boolean& assigned)
   at Marten.Schema.Identity.IdAssigner`2.Assign(TDoc document, Boolean& assigned)
   at Marten.DocumentSession.Store[T](T[] entities)
   at Dimex.DataAccess.DataFacade.InsertImageData(ImageData imageData) in D:\Dialog_Project\Dialog\src\branches\current\Dimex.DataAccess\DataFacade.cs:line 204
   at ScannedDataAggregator.Program.BackgroundWorkerOnProgressChanged(Object sender, ProgressChangedEventArgs e) in D:\Dialog_Project\D1\src\branches\current\ScannedDataAggregator\Program.cs:line 173`

**Comment by jeremydmiller** [comment]
@dnnbuddy Hey, sorry for the slow response here. I don't know offhand why the HiloSequence would be giving you fits. You *could* try increasing the page size of the HiloSettings to fetch more id's at one time in order to at least reduce the number of times it has to do this. Failing that, maybe we get in and do a retry on the HiloSequence.AdvanceToNextHi()

**Comment by jeremydmiller** [comment]
No recent activity.
