### ISSUE TITLE
Marten.MartenCommandException - System.InvalidCastException

### ISSUE THREAD

**Issue by joakimjm** [JasperFx/marten#872]
Hey guys, I love the vision of Marten and I'm trying it out on a prototype project. However I keep getting this particular error when querying.

```
Marten.MartenCommandException: Marten Command Failure:

select column_name, data_type, character_maximum_length 
from information_schema.columns where table_schema = :arg0 and table_name = :arg1
order by ordinal_position;

select a.attname, format_type(a.atttypid, a.atttypmod) as data_type
from pg_index i
join   pg_attribute a on a.attrelid = i.indrelid and a.attnum = ANY(i.indkey)
where attrelid = (select pg_class.oid 
                  from pg_class 
                  join pg_catalog.pg_namespace n ON n.oid = pg_class.relnamespace
                  where n.nspname = :arg0 and relname = :arg1)
and i.indisprimary; 


SELECT
  U.usename                AS user_name,
  ns.nspname               AS schema_name,
  pg_catalog.textin(pg_catalog.regclassout(idx.indrelid :: REGCLASS)) AS table_name,
  i.relname                AS index_name,
  pg_get_indexdef(i.oid) as ddl,
  idx.indisunique          AS is_unique,
  idx.indisprimary         AS is_primary,
  am.amname                AS index_type,
  idx.indkey,
       ARRAY(
           SELECT pg_get_indexdef(idx.indexrelid, k + 1, TRUE)
           FROM
             generate_subscripts(idx.indkey, 1) AS k
           ORDER BY k
       ) AS index_keys,
  (idx.indexprs IS NOT NULL) OR (idx.indkey::int[] @> array[0]) AS is_functional,
  idx.indpred IS NOT NULL AS is_partial
FROM pg_index AS idx
  JOIN pg_class AS i
    ON i.oid = idx.indexrelid
  JOIN pg_am AS am
    ON i.relam = am.oid
  JOIN pg_namespace AS NS ON i.relnamespace = NS.OID
  JOIN pg_user AS U ON i.relowner = U.usesysid
WHERE 
  NOT nspname LIKE 'pg%' AND 
  i.relname like 'mt_%';

select constraint_name 
from information_schema.table_constraints as c
where 
  c.constraint_name LIKE 'mt_%' and 
  c.constraint_type = 'FOREIGN KEY' and 
  c.table_schema = :arg0 and
  c.table_name = :arg1;


select column_name, data_type, character_maximum_length 
from information_schema.columns where table_schema = :arg2 and table_name = :arg3
order by ordinal_position;

select a.attname, format_type(a.atttypid, a.atttypmod) as data_type
from pg_index i
join   pg_attribute a on a.attrelid = i.indrelid and a.attnum = ANY(i.indkey)
where attrelid = (select pg_class.oid 
                  from pg_class 
                  join pg_catalog.pg_namespace n ON n.oid = pg_class.relnamespace
                  where n.nspname = :arg2 and relname = :arg3)
and i.indisprimary; 


SELECT
  U.usename                AS user_name,
  ns.nspname               AS schema_name,
  pg_catalog.textin(pg_catalog.regclassout(idx.indrelid :: REGCLASS)) AS table_name,
  i.relname                AS index_name,
  pg_get_indexdef(i.oid) as ddl,
  idx.indisunique          AS is_unique,
  idx.indisprimary         AS is_primary,
  am.amname                AS index_type,
  idx.indkey,
       ARRAY(
           SELECT pg_get_indexdef(idx.indexrelid, k + 1, TRUE)
           FROM
             generate_subscripts(idx.indkey, 1) AS k
           ORDER BY k
       ) AS index_keys,
  (idx.indexprs IS NOT NULL) OR (idx.indkey::int[] @> array[0]) AS is_functional,
  idx.indpred IS NOT NULL AS is_partial
FROM pg_index AS idx
  JOIN pg_class AS i
    ON i.oid = idx.indexrelid
  JOIN pg_am AS am
    ON i.relam = am.oid
  JOIN pg_namespace AS NS ON i.relnamespace = NS.OID
  JOIN pg_user AS U ON i.relowner = U.usesysid
WHERE 
  NOT nspname LIKE 'pg%' AND 
  i.relname like 'mt_%';

select constraint_name 
from information_schema.table_constraints as c
where 
  c.constraint_name LIKE 'mt_%' and 
  c.constraint_type = 'FOREIGN KEY' and 
  c.table_schema = :arg2 and
  c.table_name = :arg3;


select column_name, data_type, character_maximum_length 
from information_schema.columns where table_schema = :arg4 and table_name = :arg5
order by ordinal_position;

select a.attname, format_type(a.atttypid, a.atttypmod) as data_type
from pg_index i
join   pg_attribute a on a.attrelid = i.indrelid and a.attnum = ANY(i.indkey)
where attrelid = (select pg_class.oid 
                  from pg_class 
                  join pg_catalog.pg_namespace n ON n.oid = pg_class.relnamespace
                  where n.nspname = :arg4 and relname = :arg5)
and i.indisprimary; 


SELECT
  U.usename                AS user_name,
  ns.nspname               AS schema_name,
  pg_catalog.textin(pg_catalog.regclassout(idx.indrelid :: REGCLASS)) AS table_name,
  i.relname                AS index_name,
  pg_get_indexdef(i.oid) as ddl,
  idx.indisunique          AS is_unique,
  idx.indisprimary         AS is_primary,
  am.amname                AS index_type,
  idx.indkey,
       ARRAY(
           SELECT pg_get_indexdef(idx.indexrelid, k + 1, TRUE)
           FROM
             generate_subscripts(idx.indkey, 1) AS k
           ORDER BY k
       ) AS index_keys,
  (idx.indexprs IS NOT NULL) OR (idx.indkey::int[] @> array[0]) AS is_functional,
  idx.indpred IS NOT NULL AS is_partial
FROM pg_index AS idx
  JOIN pg_class AS i
    ON i.oid = idx.indexrelid
  JOIN pg_am AS am
    ON i.relam = am.oid
  JOIN pg_namespace AS NS ON i.relnamespace = NS.OID
  JOIN pg_user AS U ON i.relowner = U.usesysid
WHERE 
  NOT nspname LIKE 'pg%' AND 
  i.relname like 'mt_%';

select constraint_name 
from information_schema.table_constraints as c
where 
  c.constraint_name LIKE 'mt_%' and 
  c.constraint_type = 'FOREIGN KEY' and 
  c.table_schema = :arg4 and
  c.table_name = :arg5;

select count(*) from information_schema.sequences where sequence_schema = :arg6 and sequence_name = :arg7;
SELECT pg_get_functiondef(pg_proc.oid) 
FROM pg_proc JOIN pg_namespace as ns ON pg_proc.pronamespace = ns.oid WHERE ns.nspname = :arg8 and proname = :arg9;

SELECT format('DROP FUNCTION %s.%s(%s);'
             ,n.nspname
             ,p.proname
             ,pg_get_function_identity_arguments(p.oid))
FROM   pg_proc p
LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace 
WHERE  p.proname = :arg9
AND    n.nspname = :arg8;

SELECT pg_get_functiondef(pg_proc.oid) 
FROM pg_proc JOIN pg_namespace as ns ON pg_proc.pronamespace = ns.oid WHERE ns.nspname = :arg10 and proname = :arg11;

SELECT format('DROP FUNCTION %s.%s(%s);'
             ,n.nspname
             ,p.proname
             ,pg_get_function_identity_arguments(p.oid))
FROM   pg_proc p
LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace 
WHERE  p.proname = :arg11
AND    n.nspname = :arg10;


Column is null ---> System.InvalidCastException: Column is null
   at Npgsql.BackendMessages.DataRowMessage.CheckNotNull()
   at Npgsql.NpgsqlDataReader.<ReadColumn>d__102`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.GetString(Int32 ordinal)
   at Marten.Storage.Function.fetchDelta(DbDataReader reader, DdlRules rules)
   at Marten.Storage.Function.CreatePatch(DbDataReader reader, SchemaPatch patch, AutoCreate autoCreate)
   at Marten.Schema.SchemaPatch.Apply(NpgsqlConnection conn, AutoCreate autoCreate, ISchemaObject[] schemaObjects)
   --- End of inner exception stack trace ---
   at Marten.Schema.SchemaPatch.Apply(NpgsqlConnection conn, AutoCreate autoCreate, ISchemaObject[] schemaObjects)
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
   at Marten.Events.EventStore.FetchStreamAsync(Guid streamId, Int32 version, Nullable`1 timestamp, CancellationToken token)
   at BCI.Prototype.WebAPI.Processing.MartenEventStore.<Get>d__6.MoveNext() in /agent/_work/9/s/BCI.Prototype/src/BCI.Prototype.WebAPI/Processing/MartenEventStore.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CQRSlite.Domain.Repository.<LoadAggregate>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at 

....
```

The calling code looks like this:

 ```
await _semaphore.WaitAsync(cancellationToken);

using (var session = _store.LightweightSession(IsolationLevel.RepeatableRead))
{
    try
    {
        var martenEvents = await session.Events.FetchStreamAsync(aggregateId, token: cancellationToken);

        return martenEvents.Select(x => (IEvent)x.Data)
                .Where(x => x.Version > fromVersion)
                .ToArray();
    }
    catch (Exception ex)
    {
        Log.Fatal(ex, "Marten failed Get({aggregateId}, {fromVersion}) with {type}: {message}", ex.GetType().Name, ex.Message, aggregateId, fromVersion);
        throw;
    }
    finally
    {
        _semaphore.Release();
    }
}
```

The semphore is to limit the connections to the database, because the system is highly concurrent. I can't reproduce locally but using any cloud provider (tried with hosted postgres in Azure, GCP and in an isolated postgres instance in kubernetes) it occassionally throws the above exception.

I've been looking through the documentation and I can't figure out what I'm doing wrong.

**Comment by jeremydmiller** [comment]
@joakimjm This one is going to be irritating because there's quite a bit of code to look through. You're blowing up when Marten is trying to validate the current state of the database objects for I'm guessing the event store. Somewhere in that giant pile of SQL statements, there's a place where Marten assumes the values from the metadata coming out of Postgresql can never be null, and they apparently are in that particular cloud setup.

As a workaround, can you generate all the database schema locally, then use that SQL script to set up your hosted database, then make sure that `StoreOptions.AutoCreate == AutoCreate.None` in the production configuration so Marten doesn't even try to run those queries?

I'll try to harden Marten itself for whatever the null thing is when I can.

- Jeremy

**Comment by joakimjm** [comment]
Hey Jeremy - thanks for your suggestion. I've started using `AutoCreate.None` and I haven't had any errors since.

**Comment by jeremydmiller** [comment]
Cool, I'm closing this for now.
