### ISSUE TITLE
DocumentMapping not finding members in Ubuntu 16.04

### ISSUE THREAD

**Issue by Chaddeus** [JasperFx/marten#874]
When deploying a .net core 2.0 app to Ubuntu 16.04, Marten DocumentMapping fails to find members.

I'm using .net core 2.0 identity and used [this Github project](https://github.com/karlssonsimon/AspNetCore.Identity.Marten) as reference to build my UserStore.

My user class is TsUser, it derives from MartenUser.

```
    public class TsUser : MartenUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public string CustomerId { get; set; }
    }
```

```
    public class MartenUser : MartenUser<Guid>
    {
        public MartenUser()
        {
            Id = Guid.NewGuid();
        }
    }

    public class MartenUser<TKey> where TKey : IEquatable<TKey>
    {
        public TKey Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public bool LockoutEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public int AccessFailedCount { get; set; }

        public IList<string> Roles { get; set; } = new List<string>();
        public IList<MartenUserClaim> Claims { get; } = new List<MartenUserClaim>();
        public IList<MartenUserLogin> Logins { get; } = new List<MartenUserLogin>();
    }
```

A call like `var member = DocumentMapping.FindIdMember(typeof(MartenUser));` will find the member fine in local Win10 dev... but will fail when published to Ubuntu 16.04.

I also attempted to remove generics, superclass, and base class of MartenUser, like so:

```
    public class MartenUser
    {
        public Guid Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public bool LockoutEnabled { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public int AccessFailedCount { get; set; }

        public IList<string> Roles { get; set; } = new List<string>();
        public IList<MartenUserClaim> Claims { get; } = new List<MartenUserClaim>();
        public IList<MartenUserLogin> Logins { get; } = new List<MartenUserLogin>();
    }
```

Again, local Win10 was fine, Ubuntu failed to find the member.

**Stacktrace:**

```
 Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at TokyoSpark.Pages.Account.LoginModel.OnGet() in Login.cshtml.cs:line 59
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.ActionResultHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeHandlerMethodAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeNextPageFilterAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.<InvokeInnerFilterAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

Note: **Login.cshtml.cs:line 59** is where `var member = DocumentMapping.FindIdMember(typeof(MartenUser));` is called.

Possible issue with Marten published to Ubuntu on .net core 2.0?

**Comment by Chaddeus** [comment]
Quick update. I removed all the generics, base classes, and superclassing that was in the Identity code. Same result. `DocumentMapping.FindIdMember(typeof(MartenUser));` runs fine local Win10, fails when published to Ubuntu 16.04 host.

Also, a regular stand alone class fails too. I have an `Article` class that looks like this:

```
    public enum StatusType
    {
        Draft,
        Publish
    }

    public class Article
    {
        [Key]
        public Guid Id { get; set; }

        [MaxLength(150)]
        public string Slug { get; set; }

        [Required, MaxLength(150)]
        public string Title { get; set; }

        [Required, MaxLength(150)]
        public string SubTitle { get; set; }

        public string Content { get; set; }

        [MaxLength(255)]
        public string Excerpt { get; set; }

        [MaxLength(150)]
        public string Tags { get; set; }

        [MaxLength(150)]
        public string FeaturedImage { get; set; }

        public StatusType Status { get; set; }
        public DateTime DatePublished { get; set; }
        public DateTime DateLastModified { get; set; }
    }
```

**Comment by mysticmind** [comment]
@Chaddeus Note that Marten is targets .Net standard 1.3 and .Net 4.6. I have sent a PR for targetting .Net standard 2.0 which is yet to be merged. Let me check on this tomorrow and get back to you.

**Comment by Chaddeus** [comment]
@mysticmind Thanks. Interesting it runs fine local in .Net standard 2.0, but only breaks when published up to my Ubuntu host. Hmm... possibly the SDK on my dev box has more versions installed? (sorry, I'm not there to check right now).

Appreciate the comment, makes me more comfortable this can be solved in a timely manner. ;)

@jeremydmiller is .Net standard 2.0 on the road map "soon-ish?" Sorry, I'm not trying to rush things... just curious.

**Comment by Chaddeus** [comment]
I've never used Docker, but I'm curious if putting my app inside a Docker container and deploying that to my Ubuntu host would solve this somehow? 

Pardon my ignorance if Docker would do nothing here... I literally just started reading about it. :)

**Comment by mysticmind** [comment]
@Chaddeus I created a sample ASP.Net MVC targeting .Net Core 2.0 with some Marten code to insert a record. I had done a publish on a windows box, copied the publish folder to a Ubuntu 16.04 box and was able to run it fine without any issues.

I am not sure why you are running into issues. Could you provide a minimal sample app with the issue at your hand for me to check?

**Comment by Chaddeus** [comment]
Interesting @mysticmind . 

Here's something else. If I build the project using the ubuntu runtime target it creates a ton of files. I zip them up, push them to my host, and unzip them.

But when I run the app it throws an exception. I'm not at the console now to see it, but it was something like `System.Threading` doesn't match the manifest.

Perhaps there's something not right about the dotnet sdk installed on my host?

Hmm... makes me wonder. :)

**Comment by jeremydmiller** [comment]
I'm closing this one for now since it's gone stale. No evidence that this is Marten itself.
