### ISSUE TITLE
Cannot access a disposed object (System.Net.Sockets.NetworkStream)

### ISSUE THREAD

**Issue by afmuller** [JasperFx/marten#882]
I am having a intermittent problem with a new .Net Core 2 application I am developing - which uses Marten for persistence (Marten is an amazing product by the way). 
After my app (WebApi) has been running for a while I suddenly start getting the below exception: 

```
crit: Aerium.Velocity.Mgmt.Persistance.Repositories.BaseGuidMgmtRepository[0]
      Unable to find record
Marten.MartenCommandException: Marten Command Failure:

SELECT pg_get_functiondef(pg_proc.oid)
FROM pg_proc JOIN pg_namespace as ns ON pg_proc.pronamespace = ns.oid WHERE ns.nspname = :arg0 and proname = :arg1;

SELECT format('DROP FUNCTION %s.%s(%s);'
             ,n.nspname
             ,p.proname
             ,pg_get_function_identity_arguments(p.oid))
FROM   pg_proc p
LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
WHERE  p.proname = :arg1
AND    n.nspname = :arg0;


Exception while writing to stream ---> Npgsql.NpgsqlException: Exception while writing to stream ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at Npgsql.WriteBuffer.<Flush>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at Npgsql.WriteBuffer.<Flush>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<SendExecute>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<Execute>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Marten.Schema.SchemaPatch.Apply(NpgsqlConnection conn, AutoCreate autoCreate, ISchemaObject[] schemaObjects)
   --- End of inner exception stack trace ---
   at Marten.Schema.SchemaPatch.Apply(NpgsqlConnection conn, AutoCreate autoCreate, ISchemaObject[] schemaObjects)
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
   at Marten.Linq.MartenQueryable`1.executeAsync[TResult](Func`2 source, CancellationToken token)
   at Marten.Linq.MartenQueryable`1.SingleAsync[TResult](CancellationToken token)
   at Marten.QueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Aerium.Velocity.Shared.Persistance.BaseMartenRepository`2.<>c__DisplayClass10_0.<<GetByIdAsync>b__0>d.MoveNext() in D:\Data\Code\VSprod\Aerium.Velocity\src\Aerium.Velocity.Shared.Persistance\BaseMartenRepository.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Aerium.Velocity.Shared.Persistance.BaseMartenRepository`2.<>c__DisplayClass21_0`1.<<withRepositoryHandlingAsync>b__0>d.MoveNext() in D:\Data\Code\VSprod\Aerium.Velocity\src\Aerium.Velocity.Shared.Persistance\BaseMartenRepository.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Aerium.Velocity.Shared.Persistance.BaseMartenRepository`2.<withRepositoryHandlingAsync>d__22`1.MoveNext() in D:\Data\Code\VSprod\Aerium.Velocity\src\Aerium.Velocity.Shared.Persistance\BaseMartenRepository.cs:line 208
```
The factory class generating the DocumentStore is a singleton.
The factory class generating the DocumentSession is scoped.

From my startup file:
```
            services.AddSingleton<IMgmtDocumentStoreFactory, MgmtDocumentStoreFactory>();
            services.AddScoped<IMgmtDocumentSessionFactory, MgmtDocumentSessionFactory>();

```
My factory class generating the DocumentSession:

```
namespace Aerium.Velocity.Shared.Persistance.Factories
{
    public class MgmtDocumentStoreFactory : IMgmtDocumentStoreFactory
    {
        private IDocumentStore _documentStore;
        private readonly MgmtDatabaseConfig _config;
        private Object _dslock = new Object();

        public MgmtDocumentStoreFactory(IOptions<MgmtDatabaseConfig> config)
        {
            this._config = config.Value;
        }

        public IDocumentStore GetDocumentStore()
        {
            if (_documentStore == null)
            {
                lock (_dslock)
                {
                    if (_documentStore == null)
                        _documentStore = createDocumentStore();
                }
            }
            return _documentStore;
        }

        private IDocumentStore createDocumentStore()
        {
            return DocumentStore.For(_ =>
            {
                _.Connection(this._config.ConnectionString);
                _.AutoCreateSchemaObjects = AutoCreate.All;

            });
        }
    }
}
```
The factory generating the DocumentSession:

```
namespace Aerium.Velocity.Shared.Persistance.Factories
{
    public class MgmtDocumentSessionFactory : IMgmtDocumentSessionFactory
    {
        private readonly IMgmtDocumentStoreFactory mgmtDocumentStoreFactory;
        private Object _dslock = new Object();
        private IDocumentSession documentSession;

        public MgmtDocumentSessionFactory(IMgmtDocumentStoreFactory mgmtDocumentStoreFactory)
        {
            this.mgmtDocumentStoreFactory = mgmtDocumentStoreFactory ?? throw new ArgumentNullException(nameof(mgmtDocumentStoreFactory));
        }

        public IDocumentSession GetDocumentSession()
        {
            if (this.documentSession == null)
            {
                lock (_dslock)
                {
                    if (this.documentSession == null)
                        this.documentSession = mgmtDocumentStoreFactory.GetDocumentStore().LightweightSession();
                }
            }
            return this.documentSession;
        }
    }
}

```

I am running Marten 2.3.0. 
Developing on Windows 10 running Postgres as a Windows Service. 

Please assist me in tracing this problem. 
It is difficult to reproduce - as the application works fine until I start getting this exception. Then I normally need to restart it. However, this time it seemed to fix itself without a restart (wierd) - given some time it stopped giving the exception.

**Comment by afmuller** [comment]
I am now getting this exception - not sure if the two problems are related:

```
crit: Aerium.Velocity.Mgmt.Persistance.Repositories.BaseGuidMgmtRepository[0]
      Unable to find record
Npgsql.PostgresException (0x80004005): 53300: sorry, too many clients already
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadExpecting>d__154`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<Authenticate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnector.<Open>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.ConnectorPool.<AllocateLong>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnection.<Open>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlConnection.Open()
   at Marten.Storage.Tenant.generateOrUpdateFeature(Type featureType, IFeatureSchema feature)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
   at Marten.Storage.Tenant.ensureStorageExists(IList`1 types, Type featureType)
   at Marten.Linq.MartenQueryable`1.executeAsync[TResult](Func`2 source, CancellationToken token)
   at Marten.Linq.MartenQueryable`1.SingleAsync[TResult](CancellationToken token)
   at Marten.QueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Aerium.Velocity.Shared.Persistance.BaseMartenRepository`2.<>c__DisplayClass10_0.<<GetByIdAsync>b__0>d.MoveNext() in D:\Data\Code\VSprod\Aerium.Velocity\src\Aerium.Velocity.Shared.Persistance\BaseMartenRepository.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Aerium.Velocity.Shared.Persistance.BaseMartenRepository`2.<>c__DisplayClass21_0`1.<<withRepositoryHandlingAsync>b__0>d.MoveNext() in D:\Data\Code\VSprod\Aerium.Velocity\src\Aerium.Velocity.Shared.Persistance\BaseMartenRepository.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Aerium.Velocity.Shared.Persistance.BaseMartenRepository`2.<withRepositoryHandlingAsync>d__22`1.MoveNext() in D:\Data\Code\VSprod\Aerium.Velocity\src\Aerium.Velocity.Shared.Persistance\BaseMartenRepository.cs:line 208

```

**Comment by afmuller** [comment]
I found my problem causing the 'sorry, too many clients already' error. I was not disposing of the IDocumentSession - with this bug fixed, I do not have endless new sessions being opened to the database. 

Not sure if the first "Cannot access a disposed object " was also caused by my bug - will have to see if that problem goes away too.

**Comment by migajek** [comment]
when using ioc container, this might indicate invalid or inconsistent configuration of component lifetime. 

consider the case of webapp where 
* `IDocumentSession` is registered `per-request` 
* `FooRepository` is registered as `single instance`
* `FooRepository` is being injected with `IDocumentSession` instance

at the beginning of the first ever request, one `DocumentSession` and one `FooRepository` instances are being constructed. `FooRepository` receives the instance of `DocumentSession`. This instance of `DocumentSession` is being disposed by the container at the end of the request processing, as configured by `per-request`. From now on, FooRepository is referencing disposed `DocumentSession` and will always try to use it, ending up with the aforementioned exception
