### ISSUE TITLE
Query<T> with SQL command always assumes querying for JSON

### ISSUE THREAD

**Issue by jeffesp** [JasperFx/marten#911]
This block of code works:

```csharp
var result = session.QueryAsync<long>(
    "SELECT SUM(data->'SomeCount')) FROM mt_doc_item WHERE id = ? GROUP BY id", 
    CancellationToken.None,
    "key-value").GetAwaiter().GetResult();
```
Where this one does not:
```csharp
var result = session.Query<long>(
    "SELECT SUM(data->'SomeCount')) FROM mt_doc_item WHERE id = ? GROUP BY id", 
    "key-value");
```

It throws and `InvalidCastException` with the following stack trace:
```
GetTextReader() not supported for type int8
at Npgsql.NpgsqlDataReader.GetTextReader(Int32 ordinal)
at Marten.Linq.DeserializeSelector`1.Resolve(DbDataReader reader, IIdentityMap map, QueryStatistics stats)
at Marten.Linq.SelectorExtensions.Read[T](ISelector`1 selector, DbDataReader reader, IIdentityMap map, QueryStatistics stats)
at Marten.Linq.QueryHandlers.UserSuppliedQueryHandler`1.Handle(DbDataReader reader, IIdentityMap map, QueryStatistics stats)   at Marten.Services.CommandRunnerExtensions.<>c__DisplayClass2_0`1.<Fetch>b__0(NpgsqlCommand c)
at Marten.Services.ManagedConnection.Execute[T](NpgsqlCommand cmd, Func`2 func)   
at Marten.Services.CommandRunnerExtensions.Fetch[T](IManagedConnection runner, IQueryHandler`1 handler, IIdentityMap map, QueryStatistics stats, ITenant tenant)
at Marten.QuerySession.Query[T](String sql, Object[] parameters)   
at <snip>
```

It looks like the difference in the implementation of `Resolve` and `ResolveAsync` in [DeserializeSelector.cs](https://github.com/JasperFx/marten/blob/30b940da2c66a8d78f31c131408186f6ea11c515/src/Marten/Linq/DeserializeSelector.cs) causes the error. I think duplicating the check for `typeof(T).IsSimple()` between the two methods will fix this.

**Comment by mysticmind** [comment]
@jeffesp yes, your observation is right,  using the logic as in the async method will solve this issue. Essentially we have to add a failing test and then apply a fix for the same.

**Comment by jeffesp** [comment]
Do you prefer that to be in a specific bug test, or in with the other tests for `DeserializeSelector`?

**Comment by jeremydmiller** [comment]
I vote for a separate, bug specific test for now. Those things usually end up being kind of involved and it's often cleaner to see it in isolation

**Comment by jeffesp** [comment]
Thanks. I will see if I can get to this in the next couple days.

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/marten/pull/913. Thanks @jeffesp !
