### ISSUE TITLE
Foreign key to document with custom identity property throws exception when updating schema

### ISSUE THREAD

**Issue by gunndabad** [JasperFx/marten#961]
I have a document type that is using an overridden identity property. When creating a foreign key to this type I get an exception when Marten tries to update the schema since the generated DDL is using the overridden property name as the foreign key target instead of 'id'.

Repro:
```
using System;
using Marten;

namespace MartenFkToCustomIdentityBug
{
    public class FkTarget
    {
        public Guid SomeId { get; set; }
    }

    public class Document
    {
        public int Id { get; set; }
        public Guid TargetId { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var connStr = Environment.GetEnvironmentVariable("marten_conn_str");

            var store = DocumentStore.For(cfg =>
            {
                cfg.Connection(connStr);

                cfg.Schema.For<FkTarget>().Identity(x => x.SomeId);

                cfg.Schema.For<Document>().ForeignKey<FkTarget>(a => a.TargetId);
            });

            store.Schema.ApplyAllConfiguredChangesToDatabase();
        }
    }
}
```

Exception:
```
Marten.Schema.MartenSchemaException
  HResult=0x80131500
  Message=DDL Execution for 'All Configured Changes' Failed!

DO $$
BEGIN
    IF NOT EXISTS(
        SELECT schema_name
          FROM information_schema.schemata
          WHERE schema_name = 'public'
      )
    THEN
      EXECUTE 'CREATE SCHEMA public';
    END IF;

END
$$;

CREATE OR REPLACE FUNCTION public.mt_immutable_timestamp(value text) RETURNS timestamp with time zone LANGUAGE sql IMMUTABLE AS $function$
    select value::timestamptz
$function$;

DROP TABLE IF EXISTS public.mt_doc_fktarget CASCADE;
CREATE TABLE public.mt_doc_fktarget (
    id                  uuid CONSTRAINT pk_mt_doc_fktarget PRIMARY KEY,
    data                jsonb NOT NULL,
    mt_last_modified    timestamp with time zone DEFAULT transaction_timestamp(),
    mt_version          uuid NOT NULL default(md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar 
);
COMMENT ON TABLE public.mt_doc_fktarget IS 'origin:Marten.IDocumentStore, Marten, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null';

CREATE OR REPLACE FUNCTION public.mt_upsert_fktarget(doc JSONB, docDotNetType varchar, docId uuid, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
DECLARE
  final_version uuid;
BEGIN
INSERT INTO public.mt_doc_fktarget ("data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pk_mt_doc_fktarget
  DO UPDATE SET "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp();

  SELECT mt_version FROM public.mt_doc_fktarget into final_version WHERE id = docId;
  RETURN final_version;
END;
$function$;


CREATE OR REPLACE FUNCTION public.mt_insert_fktarget(doc JSONB, docDotNetType varchar, docId uuid, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
BEGIN
INSERT INTO public.mt_doc_fktarget ("data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (doc, docDotNetType, docId, docVersion, transaction_timestamp());

  RETURN docVersion;
END;
$function$;


CREATE OR REPLACE FUNCTION public.mt_update_fktarget(doc JSONB, docDotNetType varchar, docId uuid, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
DECLARE
  final_version uuid;
BEGIN
  UPDATE public.mt_doc_fktarget SET "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp() where id = docId;

  SELECT mt_version FROM public.mt_doc_fktarget into final_version WHERE id = docId;
  RETURN final_version;
END;
$function$;

DROP TABLE IF EXISTS public.mt_doc_document CASCADE;
CREATE TABLE public.mt_doc_document (
    id                  integer CONSTRAINT pk_mt_doc_document PRIMARY KEY,
    data                jsonb NOT NULL,
    mt_last_modified    timestamp with time zone DEFAULT transaction_timestamp(),
    mt_version          uuid NOT NULL default(md5(random()::text || clock_timestamp()::text)::uuid),
    mt_dotnet_type      varchar ,
    target_id           uuid 
);
COMMENT ON TABLE public.mt_doc_document IS 'origin:Marten.IDocumentStore, Marten, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null';

ALTER TABLE public.mt_doc_document
ADD CONSTRAINT mt_doc_document_target_id_fkey FOREIGN KEY (target_id)
REFERENCES public.mt_doc_fktarget (someid);

CREATE INDEX mt_doc_document_idx_target_id ON public.mt_doc_document ("target_id");

CREATE OR REPLACE FUNCTION public.mt_upsert_document(arg_target_id uuid, doc JSONB, docDotNetType varchar, docId integer, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
DECLARE
  final_version uuid;
BEGIN
INSERT INTO public.mt_doc_document ("target_id", "data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (arg_target_id, doc, docDotNetType, docId, docVersion, transaction_timestamp())
  ON CONFLICT ON CONSTRAINT pk_mt_doc_document
  DO UPDATE SET "target_id" = arg_target_id, "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp();

  SELECT mt_version FROM public.mt_doc_document into final_version WHERE id = docId;
  RETURN final_version;
END;
$function$;


CREATE OR REPLACE FUNCTION public.mt_insert_document(arg_target_id uuid, doc JSONB, docDotNetType varchar, docId integer, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
BEGIN
INSERT INTO public.mt_doc_document ("target_id", "data", "mt_dotnet_type", "id", "mt_version", mt_last_modified) VALUES (arg_target_id, doc, docDotNetType, docId, docVersion, transaction_timestamp());

  RETURN docVersion;
END;
$function$;


CREATE OR REPLACE FUNCTION public.mt_update_document(arg_target_id uuid, doc JSONB, docDotNetType varchar, docId integer, docVersion uuid) RETURNS UUID LANGUAGE plpgsql SECURITY INVOKER AS $function$
DECLARE
  final_version uuid;
BEGIN
  UPDATE public.mt_doc_document SET "target_id" = arg_target_id, "data" = doc, "mt_dotnet_type" = docDotNetType, "mt_version" = docVersion, mt_last_modified = transaction_timestamp() where id = docId;

  SELECT mt_version FROM public.mt_doc_document into final_version WHERE id = docId;
  RETURN final_version;
END;
$function$;

-- public.mt_get_next_hi Diff
DROP FUNCTION public.mt_get_next_hi(entity character varying) cascade;


-- public.mt_get_next_hi Diff
CREATE OR REPLACE FUNCTION public.mt_get_next_hi(entity varchar) RETURNS int AS $$
DECLARE
	current_value bigint;
	next_value bigint;
BEGIN
	select hi_value into current_value from public.mt_hilo where entity_name = entity;
	IF current_value is null THEN
		insert into public.mt_hilo (entity_name, hi_value) values (entity, 0);
		next_value := 0;
	ELSE
		next_value := current_value + 1;
		update public.mt_hilo set hi_value = next_value where entity_name = entity;
	END IF;

	return next_value;
END
$$ LANGUAGE plpgsql;






CREATE OR REPLACE FUNCTION public.mt_transform_patch_doc(doc JSONB, patch JSONB) RETURNS JSONB AS $$

  var module = {export: {}};

  'use strict';

function findDeep(doc, parts){
    var element = doc;

    for (var i = 0; i < parts.length; i++){
        var child = parts[i];
        if (!element.hasOwnProperty(child) || !element[child]){
            element[child] = {};
        }

        element = element[child];
    }

    return element;
}

function locate(doc, path){
    var parts = path.split('.');

    var element, prop;

    if (parts.length > 0){
        prop = parts.pop();
        element = findDeep(doc, parts);
    }
    else {
        prop = path;
        element = doc;
    }

    return {element: element, prop: prop};
}

function setValue(doc, patch, location){
    location.element[location.prop] = patch.value;

    return doc;
}

function deleteValue(doc, patch, location){
    delete location.element[location.prop];

    return doc;
}

function duplicateValue(doc, patch, location){
    var value = location.element[location.prop];
    for (var i = 0; i < patch.targets.length; i++) {
      var copyTo = locate(doc, patch.targets[i]);
      copyTo.element[copyTo.prop] = value;
    }

    return doc;
}

function incrementValue(doc, patch, location){
    var interval = 1;
    if (patch.increment){
        interval = parseInt(patch.increment);
    }

    var existing = 0;
    if (location.element[location.prop]){
        existing = parseInt(location.element[location.prop]);
    }

    location.element[location.prop] = existing + interval;

    return doc;
}

function incrementFloat(doc, patch, location){
    var interval = 1;
    if (patch.increment){
        interval = parseFloat(patch.increment);
    }

    var existing = 0;
    if (location.element[location.prop]){
        existing = parseFloat(location.element[location.prop]);
    }

    location.element[location.prop] = existing + interval;

    return doc;
}

function appendElement(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }

    location.element[location.prop].push(patch.value);

    return doc;
}

function appendElementIfNotExists(doc, patch, location){
     if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }

    var array = location.element[location.prop];
    var patchValueAsJSONString = JSON.stringify(patch.value);
    for(var i = 0; i < array.length; i++)
    {
        var elementAsJSONString = JSON.stringify(array[i])
        if (patchValueAsJSONString === elementAsJSONString)
            return doc;
    }

    location.element[location.prop].push(patch.value);

    return doc;
}

function insertElement(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }

    var array = location.element[location.prop];

    var index = 0;
    if (patch.index){
        index = parseInt(patch.index);
    }

    array.splice(index, 0, patch.value);

    return doc;
}

function insertElementIfNotExists(doc, patch, location){
    if (!location.element[location.prop]){
        location.element[location.prop] = [];
    }

    var array = location.element[location.prop];

    var index = 0;
    if (patch.index){
        index = parseInt(patch.index);
    }

    var patchValueAsJSONString = JSON.stringify(patch.value);
    var elementAsJSONString = JSON.stringify(array[index]);
    if (elementAsJSONString !== patchValueAsJSONString){
        array.splice(index, 0, patch.value);
    }

    return doc;
}

function rename(doc, patch, location){
    var actual = location.element[location.prop];
    delete location.element[location.prop];

    location.element[patch.to] = actual;

    return doc;
}

function removeElement(doc, patch, location){
    var array = location.element[location.prop];
    if (!array) return doc;

    var indices = [];
    array.every(function(element, index, _array) {
      if (!deepEquals(patch.value, element)) return true;
      indices.push(index);
      return patch.action === 1;
    });

    for (var i = indices.length - 1; i > -1; i--) {
      array.splice(indices[i], 1);
    }

    return doc;
}

function deepEquals(x, y) {
    if (x === null || x === undefined || y === null || y === undefined) { return x === y; }
    if (x === y || x.valueOf() === y.valueOf()) { return true; }
    if (Array.isArray(x) && x.length !== y.length) { return false; }

    if (!(x instanceof Object)) { return false; }
    if (!(y instanceof Object)) { return false; }

    var p = Object.keys(x);
    return Object.keys(y).every(function (i) { return p.indexOf(i) !== -1; }) &&
        p.every(function (i) { return deepEquals(x[i], y[i]); });
}

var ops = {
    'set': setValue,
    'delete': deleteValue,
    'duplicate': duplicateValue,
    'increment': incrementValue,
    'increment_float': incrementFloat,
    'append': appendElement,
    'append_if_not_exists': appendElementIfNotExists,
    'rename': rename,
    'insert': insertElement,
    'insert_if_not_exists' : insertElementIfNotExists,
    'remove': removeElement
}

module.exports = function(doc, patch){
    // TODO -- throw if not a handler
    var handler = ops[patch.type];

    var location = locate(doc, patch.path);

    return handler(doc, patch, location);
}


  var func = module.exports;

  return func(doc, patch);

$$ LANGUAGE plv8 IMMUTABLE STRICT;
  Source=Marten
  StackTrace:
   at Marten.Storage.TenantSchema.ApplyAllConfiguredChangesToDatabase()
   at MartenFkToCustomIdentityBug.Program.Main(String[] args) in c:\users\james\source\repos\MartenFkToCustomIdentityBug\MartenFkToCustomIdentityBug\Program.cs:line 33

Inner Exception 1:
PostgresException: 42703: column "someid" referenced in foreign key constraint does not exist
```

**Comment by jeremydmiller** [comment]
@gunndabad This is next up for me after lunch today.
