### ISSUE TITLE
OrderBy breaks AsPagedList

### ISSUE THREAD

**Issue by kasparkallas** [JasperFx/marten#988]
Repro in _Marten/Testing/Pagination/pagedlist_queryable_extension_Tests.cs_:
```
[Fact]
public void can_return_paged_result()
{
    var pageNumber = 2;
    var pageSize = 10;

    var pagedList = theSession.Query<Target>()
        .OrderBy(x => x) // <-- Repro code
        .AsPagedList(pageNumber, pageSize);

    pagedList.Count.ShouldBe(pageSize);
}
```

Error:
```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Marten.Schema.Field..ctor(MemberInfo[] members)
   at Marten.Schema.JsonLocatorField..ctor(String dataLocator, EnumStorage enumStyle, Casing casing, MemberInfo[] members)
   at Marten.Schema.FieldCollection.<>c__DisplayClass8_0.<FieldFor>b__1(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Marten.Schema.FieldCollection.FieldFor(IEnumerable`1 members)
   at Marten.Schema.DocumentMappingExtensions.JsonLocator(IQueryableDocument mapping, Expression expression)
   at Marten.Linq.Model.LinqQuery`1.writeOrderByFragment(CommandBuilder sql, Ordering clause)
   at Marten.Linq.Model.LinqQuery`1.writeOrderClause(CommandBuilder sql)
   at Marten.Linq.Model.LinqQuery`1.ConfigureCommand(CommandBuilder sql, Int32 limit)
   at Marten.Linq.Model.LinqQuery`1.ConfigureCommand(CommandBuilder command)
   at Marten.Linq.QueryHandlers.ListQueryHandler`1.ConfigureCommand(CommandBuilder builder)
   at Marten.Util.CommandBuilder.ToCommand(ITenant tenant, IQueryHandler handler)
   at Marten.Services.CommandRunnerExtensions.Fetch[T](IManagedConnection runner, IQueryHandler`1 handler, IIdentityMap map, QueryStatistics stats, ITenant tenant)
   at Marten.Linq.MartenQueryExecutor.Remotion.Linq.IQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Marten.Pagination.PagedList`1..ctor(IQueryable`1 superset, Int32 pageNumber, Int32 pageSize)
   at Marten.Pagination.PagedListQueryableExtensions.AsPagedList[T](IQueryable`1 queryable, Int32 pageNumber, Int32 pageSize)
   at Marten.Testing.Pagination.pagedlist_queryable_extension_Tests.can_return_paged_result() in C:\_Repositories\marten-master\src\Marten.Testing\Pagination\pagedlist_queryable_extension_Tests.cs:line 49
```

**Comment by jeremydmiller** [comment]
Why would you even try to do `.OrderBy(x => x)`? That's never going to work because Marten doesn't know what property to sort on. It wouldn't have any way of understanding the class's CompareTo() logic.

**Comment by kasparkallas** [comment]
I left the `.OrderBy(x => x)` in as a simplified example and in reality used a different selector. But it turns out there is a similar issue of selector logic not being understandable to Marten in my code. The exception message threw me off a bit. My bad, sorry I posted prematurely, thank you @jeremydmiller!
